### ISSUE TITLE
include logical structure sidebar navigation / outline view

### ISSUE THREAD

**Issue by maxheld83** [thomasjo/atom-latex#105]
just saw a [question on StackExchange](http://stackoverflow.com/questions/24455285/how-to-get-outline-view-of-latex-project-in-sublime-text) and thought this might be something to be done at *some* (distant?) point in the future in atom.

Would be nice to actually display the *logical* structure of the document, not merely all `\chapter{blah}` markers etc.

Much like here in the screen shot from the OP:

![outline view](http://i.stack.imgur.com/hJX3D.png)

**Comment by breschke** [comment]
This feature is the biggest thing I'm missing from Eclipse IDE.

**Comment by macmadness86** [comment]
I would really like to see this become a reality. I would like a flexible and easy way to add custom headings to the outline.  (for headings besides the typical \section, \subsection, and \subsubsection commands)

**Comment by cmmoenne** [comment]
The closest thing to a navigation panel for latex is the _navigation panel_ of the latex-friend package (https://github.com/ruivieira/latex-friend). It has its issues, but for now, it is the best alternative that I have found.

**Comment by yitzchak** [comment]
At the moment we are keeping `latex` focused on the building/processing of LaTeX documents. As @cmmoenne has commented the best option for this functionality is currently [latex-friend](https://atom.io/packages/latex-friend).
