### ISSUE TITLE
friendly use Latex-xelatex-lulatex etc 

### ISSUE THREAD

**Issue by chemotkbilo** [thomasjo/atom-latex#106]
it would be great if a feature, that when i start compiling, it asks what engine i want to compile with - like a drop menu or something. just for the ease of use. i am trying to comply a document with Xelatex- but not working. however, on sublime text 3, it is working fine after i add the following at the beginning of the document. 
"%-*- program: xelatex -*-        
%-*- program: biber -*-`        
%-*- program: xelatex -*- "

**Comment by redw0lf** [comment]
I was looking for sth like this too. It should be possible to easily integrate this using the magic comments. There is a parser for this already, it just has to be used in the right place.
e.g. using % !TEX TS-program = pdflatex

**Comment by thomasjo** [comment]
Yup, it's on my personal to-do list. I would like to improve the magic parser code first though, since now it only works if the magic comment is the very first line. It should work as long as there have been no LaTeX declarations/statements yet.

**Comment by thomasjo** [comment]
Thanks to @redw0lf this is now supported in v0.27.0 via "magic comments" functionality.
