### ISSUE TITLE
Latex compilation error

### ISSUE THREAD

**Issue by Rdbllx** [thomasjo/atom-latex#107]
Hello everyone, I need some help. 
I have installed this package and done all right but when I try to compile a .tex file
with ctrl+alt+b it doesn't work. 
I don't understand why I get this compilation error at the left bottom of atom.
Moreover, I am sure that my tex file contains no mistakes.
Thank's in advance for your answers.

**Comment by Rdbllx** [comment]
By the way, I use miktex, should i use texlive ?

**Comment by nscaife** [comment]
MikTeX is basically unsupported here, but I have gotten it to work.  Did you put the MikTeX binary directory in your Windows path?

You will most assuredly have more out-of-the-box luck with TeX Live.

**Comment by m0nhawk** [comment]
Actually, MiKTeX does supported with latest version. You need to change the "Builder" in the package config from default `latexmk` into `texify` (default for MiKTeX).

**Comment by Rdbllx** [comment]
Thank's m0nhawk it works perfectly after this modification :).
Just an other little thing, can I modify something so that after  compiling  the tex file, 
the pfd file automatically shows up ?

**Comment by m0nhawk** [comment]
You can put a direct path to the PDF viewer in the "Custom PDF viewer PATH". Currently, it's pretty vague for Windows, it don't support default Windows viewer.

**Comment by thomasjo** [comment]
@Rdbllx That is already supported. On Windows you've currently got two documented options;
 1.  Install SumatraPDF. If it's installed in the default location `C:\Program Files (x86)\SumatraPDF\SumatraPDF.exe` it will work automatically.  
     See https://github.com/thomasjo/atom-latex/wiki/Configuration#sumatrapath for the related configuration option for changing the path to where SumatraPDF is installed.
2. Install the [pdf-view](https://atom.io/packages/pdf-view) package.

**Comment by thomasjo** [comment]
> You can put a direct path to the PDF viewer in the "Custom PDF viewer PATH". Currently, it's pretty vague for Windows, it don't support default Windows viewer.

Windows only recently added support for opening PDF files by default, in addition it does not (to my knowledge) support SyncTeX functionality. Preview.app on OS X does, hence why it's a sensible platform default. Skim.app is the recommended application on OS X however, just as SumatraPDF is for Windows.

**Comment by thomasjo** [comment]
Since the original problem has been resolved, thanks to assistance by @m0nhawk, I'm closing this issue.
Hopefully whenever I implement #64, this type of issue will be a thing of history.
