### ISSUE TITLE
Check if output file is blocked

### ISSUE THREAD

**Issue by klicperajo** [thomasjo/atom-latex#119]
If I compile while the output file (pdf) is opened with Adobe Reader and therefore blocked, the compilation freezes. I need to restart Atom to remedy this error. This lock should be checked before compilation.

**Comment by m0nhawk** [comment]
This should be better done via [DDE](http://help.adobe.com/en_US/acrobat/acrobat_dc_sdk/2015/HTMLHelp/index.html#t=Acro12_MasterBook%2FIAC_API_DDE_Messages%2FIAC_API_DDE_Messages.htm), it supported in both Acrobat and Sumatra.

Thus, It'll require only `DocClose` before the build and `DocOpen` latter.

**Comment by thomasjo** [comment]
> This should be better done via DDE, it supported in both Acrobat and Sumatra.

Except there is, to my knowledge, no sensible way to work directly with DDE/OLE from Node.js. Simply put, there's no way I'm implementing any code for that in this package. However, if there exists a reasonable npm package that provides DDE/OLE interop, I'd likely merge a PR using it.

At the end of the day, I have to maintain all the code in this package, and DDE/OLE is a rabbit hole that I'd rather not venture into.

**Comment by yitzchak** [comment]
I am closing this since a DDE dependency is not a direction that we want to go. Will reopen if needed.
