### ISSUE TITLE
Biber ?

### ISSUE THREAD

**Issue by spartiot** [thomasjo/atom-latex#121]
Each time I compile a document, I get the following error : 
"Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                These
(biblatex)                and rerun LaTeX afterwards."

When I run Biber manually in the shell, it works.

Is it possible to automatize this ?

Thank you in advance !

**Comment by spartiot** [comment]
Any idea ?

**Comment by thomasjo** [comment]
@spartiot I'm currently on vacation, but I will look into this over the weekend once I've returned back home. In the meantime, if you could provide me with a minimal example that reproduces your problem, that would brilliant! Additionally if you could let me know what OS and LaTeX distribution you are using that would also be helpful in narrowing down the problem.

**Comment by spartiot** [comment]
Well... It seems that the problem solved itself.

Thank you, though. :)
