### ISSUE TITLE
Auto-close \begin{foo} with \end{foo}

### ISSUE THREAD

**Issue by devurandom** [thomasjo/atom-latex#122]
It would be great of whenever I type `\begin{foo}`, Atom would automatically close it with `\end{foo}`.

**Comment by nickgravish** [comment]
I believe the latexer package already does this. 

https://github.com/Focus/latexer

**Comment by DoctorBlue** [comment]
It does, yes. It's very useful :)

**Comment by devurandom** [comment]
So I should use the latexer package in addition and there are no plans to reduce the number of necessary packages?

**Comment by yitzchak** [comment]
At the moment we are keeping `latex` focused on the building/processing of LaTeX documents. For auto-completion functionality I would suggest [latex-autocomplete](https://atom.io/packages/latex-autocomplete) or [latexer](https://atom.io/packages/latexer).
