### ISSUE TITLE
Support xdg-open

### ISSUE THREAD

**Issue by devurandom** [thomasjo/atom-latex#123]
On modern Linux system (supporting the XDG specs), there is a tool called `xdg-open`, which can open arbitrary files with the viewer chosen by the user.

In case the editors supported by Atom/LaTeX are not available (i.e. when one does not use MacOSX or Windows), Atom could fallback to trying `xdg-open`. Only downside: The file will be opened multiple times, once for each invocation.

**Comment by yitzchak** [comment]
This feature has been added and will be in the next version.
