### ISSUE TITLE
Building causes a new sumatra-pdf window every time

### ISSUE THREAD

**Issue by mmoh** [thomasjo/atom-latex#125]
Every time I build a late file a new sumatra window is opened. This is quite annoying since you end up with many sumatra pdf windows open at the same time, unless you close it every time your done after a build.

**Comment by thomasjo** [comment]
Thanks for the report. I agree that this is annoying, and very unfortunate. I'll see if I can figure out a sensible way of fixing this problem.

**Comment by m0nhawk** [comment]
@mmoh As a workaround I can offer to set the "Use tabs" option in the Settings.

**Comment by mmoh** [comment]
@m0nhawk  I can't seem to find this option? 
@thomasjo  One thing that does work is to disable the option to automatically open the pdf file, open the file manually using sumatra, and then then sumatra automatically gets refreshed  when you build. 

I'm not sure what open results in the background does but on my computer in has no effect.

**Comment by m0nhawk** [comment]
@mmoh And what Sumatra version you use? I have 3.0 (latest). It's in the Advanced section.

![test](https://cloud.githubusercontent.com/assets/8220926/10140105/ab96fe72-660e-11e5-98d3-5bc4277af3f5.png)

**Comment by nscaife** [comment]
I'm not able to reproduce this.  My system refreshes the PDF in the same Sumatra window.

**Comment by mmoh** [comment]
@nscaife Are you on Windows?
@m0nhawk  I'm using version 3 like you. Ok thank's I see the setting now.

The sublime text latex plugin doesn't have this problem. So perhaps that could be used for inspiration to fix this issue.

**Comment by nscaife** [comment]
@mmoh I am on Windows, Sumatra v3.0.

**Comment by mmoh** [comment]
Ok so it looks like it works when I select  the use tabs option, which I normally don't use. Still this should be fixed so that it works in both cases. Perhaps a simple solution is on the first compilation to check if the pdf is loaded in sumatra, in subsequent compilations not to launch sumatra, since the pdf file will refresh and sumatra will detect these changes.

**Comment by nscaife** [comment]
In order to do that, I think the plugin would have to either:

1. Only open on first compile, which may be problematic if someone accidentally closes Sumatra. This could probably be made a config setting, though.
2. Scan window titles looking for a Sumatra instance with a title including the PDF file name, which may be problematic if you have multiple PDFs with the same name.

Perhaps another good solution would be to file a bug on the Sumatra repository, since it may not be expected behavior.

**Comment by mholzhauser** [comment]
Seems that there is a `-reuse-instance` command-line argument that should do the job. At least the `LaTeXTools` plugin for SublimeText uses it.

**Comment by thomasjo** [comment]
Just published v0.28.2 which resolves this issue. Huge thanks again to @m0nhawk and @mmoh for their help!

**Comment by mmoh** [comment]
Great thank you! On a related note, it looks like after building a tex file and after it opens up the pdf in  sumatra, the sumatra window always steals the cursor's focus even if `open result in background` is checked. Perhaps I should open up a new issue regarding this?

**Comment by thomasjo** [comment]
@mmoh Yeah, please do! Unless there is some other (undocumented) flag for that, it seems the only way to prevent that with Sumatra is by using DDE. DDE in Node.js seems like a royal pain, even with a wrapper such as [node-dde](https://www.npmjs.com/package/node-dde).

**Comment by joergweber** [comment]
This has been closed, but I still have the same issue with 0.42.3 and SumatraPDF 3.1.2 (tabs deactivated). 

I have simply added '-reuse-instance' to the arguments in sumatra-opener.js and now it works perfectly (open Sumatra if closed, but then refresh instance). I think this argument is necessary to have this working consistently.

**Comment by thomasjo** [comment]
@yitzchak Do you remember why you removed `-reuse-instance` in #265?

**Comment by yitzchak** [comment]
It doesn't appear to work with multiple documents plus the [documentation](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Command-line-arguments) appears to suggest it is only for DDE application. Not sure if there is an ideal solution. Maybe we should put it back in?

**Comment by thomasjo** [comment]
I guess if the provided functionality is better with the flag, then I suggest we put it back until we can find a better way.

**Comment by yitzchak** [comment]
I agree.

Just FYI, it displays an irritating dialog box for each open in the multiple document situation. Just remembered that. Very few people probably will ever use it that way though.

**Comment by joergweber** [comment]
I don't see what the problem with multiple documents is. I am using that right now, two different projects producing two different PDFs in two different SumatraPDF windows. With the '-reuse-instance' the correct window gets updated each time, and I don't see a dialog box.

**Comment by yitzchak** [comment]
I only saw it with the `jobnames = foo, bar`. Hopefully it works now.
