### ISSUE TITLE
Custom PDF viewer and output directory

### ISSUE THREAD

**Issue by f380cedric** [thomasjo/atom-latex#126]
Hi,
I have a problem, I have the output directory like this `build/` and the custom pdf like this `/usr/bin/evince`
When it build the tex file (and when "always open result" in Atom is checked), evince is correctly open but not in the right directory, it open evince in the current directory and not in the build/ directory... So it failed because pdf file is in the `build/` directory
An idea?
Thx

**Comment by f380cedric** [comment]
A friend of mine came with this version of the custom_opener.js that works using the configured output build dir. 

```javascript
"use babel";

import Opener from "../opener";
import child_process from "child_process";
import path from "path";

export default class CustomOpener extends Opener {
  // Custom PDF viewer cannot support texPath and lineNumber
  open(filePath, texPath, lineNumber, callback) {
    const command = `\"${atom.config.get("latex.viewerPath")}\" \"${this.getOutputPath(filePath)}\"`;
    child_process.exec(command, (error) => {
      if (callback) {
        callback((error) ? error.code : 0);
      }
    });
  }

  getOutputPath(filePath) {
    let outdir = atom.config.get("latex.outputDirectory");
    if (outdir) {
      const dir = path.dirname(filePath);
      outdir = path.join(dir, outdir);
      const file = path.basename(filePath);
      outdir = path.join(outdir, file);
    }
    return outdir;
  }
}
```

**Comment by Poeschl** [comment]
It also seems that the custom build output isn't used for the clear also ;)

**Comment by yitzchak** [comment]
This has been fixed along with the `clean` issue.
