### ISSUE TITLE
[Feature Request/Confirmation] Build on "parent" file when building on included child file

### ISSUE THREAD

**Issue by pydolan** [thomasjo/atom-latex#127]
I have a latex project with one "parent" tex file that contains everything except for the content of each section, which I have stored in separate tex files. I'd like to be able to call build when my editor's focused tab is one of the section tex files, but instead have it build on the parent tex file.

I vaguely remember this working at one point, but I could be misremembering. Currently when I run build, I get a Latex error about `\begin{document}` being missing (since the section tex file is just content). 

Assuming this feature doesn't exist, it would be nice to add it, perhaps by having an optional atom-latex setting that points to a target build file (maybe a Makefile?).  Thoughts?

**Comment by thomasjo** [comment]
This is supported via "magic comments". Please see https://github.com/thomasjo/atom-latex/issues/70#issuecomment-89025737.

---
**Note to self**: Improve documentation of supported functionality/features.

**Comment by pydolan** [comment]
Excellent, thanks!
