### ISSUE TITLE
/usr/local/sbin and /usr/local/bin missing in ENV[PATH] on mac, results in failure including eps as figure

### ISSUE THREAD

**Issue by balu-** [thomasjo/atom-latex#130]
Texlive supports the inclusion of eps files as figures.
If this is done the eps is converted to a pdf at compiletime of the tex file.
In the shell this works fine,
using atom-latex this fails.
The errorlog shows that the pdf is not beeing creadted.

I investigated the problem a bit and found out that /usr/local/sbin and /usr/local/bin is missing from process.env (builder.js line 30).
By adding this two folders to path using the texPath setting, the compilation of the tex file works quite nicely.

I'm not quite sure if this is a problem of atom-latex or atom.

**Comment by thomasjo** [comment]
This is unfortunately a problem in Atom (see https://github.com/atom/atom/issues/6956). Current workaround is to add some code to your `init.coffee` file to initialize `process.env.PATH`, always starting Atom from a terminal, or, as you discovered, expanding `latex.texPath` config option to include the paths.

Fixing this in Atom is on my list, but sadly it's a very long list. Sorry about the trouble!
