### ISSUE TITLE
Latest release is broken for me

### ISSUE THREAD

**Issue by danielchatfield** [thomasjo/atom-latex#132]
I upgraded to the latest release and it no longer builds anything.

"Compiling latex" appears briefly then disappears but nothing actually happened.

Reverting to previous version works.

**Comment by thomasjo** [comment]
Sorry about! What OS (including version) are you running, and which TeX distribution? In addition it would be great if you could provide a minimal example that reproduces the problem. I'm unable to reproduce the issue on my end, so I'm going to need some assistance from you to track down the problem.

Does any errors pop up in the developer console in Atom?

**Comment by danielchatfield** [comment]
osx with mactex 2015.

Trying to provide a minimal example and playing with some settings. I have observed:

 - It works when output directory setting is empty
 - when it is set to open the pdf in atom (with output directory set) then the atom window opens a blank file titled `test.pdf"` (note the additional quotation mark)

**Comment by danielchatfield** [comment]
Looking for changes introduced that could explain it and stumbled across [this](https://github.com/thomasjo/atom-latex/compare/v0.26.0...v0.27.0?diff=split&name=v0.27.0#diff-dde50c51d91de11d407f53423f3baeecL63). Was that intentional?

**Comment by thomasjo** [comment]
> Looking for changes introduced that could explain it and stumbled across this. Was that intentional?

Definitely not! I'll fix that right away. Thanks :heart:

**Comment by thomasjo** [comment]
Does your output folder contain spaces?

**Comment by danielchatfield** [comment]
My output folder doesn't, but the project folder does.

**Comment by danielchatfield** [comment]
Got it: https://github.com/thomasjo/atom-latex/commit/86228446896843c6ca273f894939028b1b98d435#diff-a3469148feb23f8296234a2f454b9351L39

**Comment by thomasjo** [comment]
Definitely seems like a regression has snuck in with regards to the log parser and spaces. Going to create a failing spec now to verify. In the meantime, can you navigate to your output folder, print the last few lines in the `.log` file. It should be wrapped in quotes.

**Comment by danielchatfield** [comment]
Double quote shouldn't have been replaced.

**Comment by thomasjo** [comment]
Excellent find, thanks again! Will publish a patch release within a few minutes.

**Comment by thomasjo** [comment]
v0.27.1 has been released which should resolve your problem. Sorry about the inconvenience!
