### ISSUE TITLE
Move result to Source Directory not working

### ISSUE THREAD

**Issue by Poeschl** [thomasjo/atom-latex#138]
The switch to move the output file to the source folder is not working correctly for me. I assume that it should move the .pdf and synctex file to same folder of the .tex file, right?

**Comment by thomasjo** [comment]
Yeah, that's correct. Can you provide some more details about your setup? In particular OS, TeX distribution, and Atom version. Thanks!

**Comment by Poeschl** [comment]
OS: Win 7 and Linux Mint 17.1
TeX: TeX Live 2013
Atom: 1.0.19

Hope this helps

**Comment by thomasjo** [comment]
Are you getting any errors in either the log file, or the developer console inside of Atom? I've been unable to reproduce this, but I haven't tried using TeX Live 2013 yet. Do you have a machine with a newer release you can test on? I've tried both 2014 and 2015 (the former is being used in the CI builds).

**Comment by Poeschl** [comment]
I updated to TeX Live 2015 and it seem to works fine.
Do you still want me to test on 2013?
