### ISSUE TITLE
Magic Comment Root File Search - Quotes and Upper/Lower Case of !TeX

### ISSUE THREAD

**Issue by EdJoPaTo** [thomasjo/atom-latex#139]
```
# !TeX root = "main.tex"
```
does not work properly:

* !TeX instead of !TEX:
the magic comment will be ignored. Instead of the main file the current file will be build.
(most of latex magic comment tutorials i found are written with !TeX)
* Quotes around the filename:
  * build will build the main file and show the warning "LatTeX compilation error" without any error. (Click on the warning does not open anything)
  * clean does not seem to work. Nothing happens.

@redw0lf added the multi magic comment finder (thanks for that!)
Maybe he knows best how to implement that in his code?

I changed my magic comments based on that but it would be nice if that would work ;)

(tested with Ubuntu, latexmk)

**Comment by thomasjo** [comment]
Making the matching of the magic comment marker case-insensitive is trivial. However, I've never seen it written as `!TeX` — I have only ever seen the all uppercase variant. Do you have any links to articles or similar where they are promoting the `!TeX` convention?

**Comment by EdJoPaTo** [comment]
https://duckduckgo.com/?q=latex+magic+comment
first 3 useful links all use or ask for !TeX:

* http://www.texdev.net/2011/03/24/texworks-magic-comments/
* http://tex.stackexchange.com/questions/256362/texmaker-magic-comment
* http://sourceforge.net/p/texstudio/feature-requests/182/
