### ISSUE TITLE
SumatraPDF steels cursor focus, even when `open result in background` is checked

### ISSUE THREAD

**Issue by musm** [thomasjo/atom-latex#142]
After building a tex file and after it opens up the pdf in sumatra, the sumatra window always steals the cursor's focus even if `open result in background` is checked in settings.

**Comment by m0nhawk** [comment]
This can be done via [`atom.focus()`](https://atom.io/docs/api/v1.1.0/Atom#instance-focus), but it is bugged in the Windows and didn't work [`#2867`](https://github.com/atom/electron/issues/2867).

**Comment by thomasjo** [comment]
@m0nhawk Not really, since when we launch Sumatra PDF, its process steals focus. There's no stable way of preventing that from Atom itself. We have to tell the Sumatra PDF process to **not** steal focus, and this is currently only possible via DDE commands.

**Comment by m0nhawk** [comment]
I actually just tried to run `atom.focus()` in the builder after the compilation is called, but it fails due to this bug (some other, like `atom.center()` works).

So it may be enough to just an optional call of `atom.focus()` in the builder (this may be cross-platform solution also).

**Comment by thomasjo** [comment]
Launching an opener is an asynchronous operation, so if the opening of e.g. Sumatra PDF is slow/delayed, it will steal focus regardless of what we do from within Atom. Hence my comment about there not being a good solution to this from within the plugin itself. We have no generic way of knowing when the file has been opened in the target application. If we did, we could steal focus back again (if lost) as you propose.

**Comment by yitzchak** [comment]
I am closing this since there is no reasonable way to steal the focus back and DDE dependency is not a direction that we want to go. Will reopen if needed.
