### ISSUE TITLE
Preview without re-opening the file

### ISSUE THREAD

**Issue by jugc** [thomasjo/atom-latex#149]
Hi, 

Great package! I think a nice feature for opening the file after a build, is that if the file is already open, it should update it instead of open it again.

This happens with okular in Ubuntu 14.04

Thanks,
Juan

**Comment by thomasjo** [comment]
I would have thought that this would be covered by the [`--unique` flag](https://github.com/thomasjo/atom-latex/blob/20e0efa1acfee2f9f0b7ef80fa3fc6cbcd033e20/lib/openers/okular-opener.js#L10).

**Comment by yitzchak** [comment]
This has been fixed by the `--unique` flag.
