### ISSUE TITLE
Many build needed

### ISSUE THREAD

**Issue by borisxXx** [thomasjo/atom-latex#151]
Since the last version, I have to build many times to get the entire compilation done.
It seem to correspond to the different build needed from pdflatex.
Is there a solution to get the entire compilation done when hitting the build shortcut once ?

**Comment by thomasjo** [comment]
Are you still able to reproduce this? Is yes, it would be great if you can provide a minimal example that reproduces the problem, as well as provide the following information
  1. Operating system (including version).
  2. TeX distribution (including version).
  3. Configuration options for this package. At least `latex.builder` and `latex.outputDirectory` if either of those have been customized.

Thanks!

**Comment by borisxXx** [comment]
OS : Ubuntu 14.04
Tex distribution and version : pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
I use latexmk, pdflatex and the output directory is blank.
I've changed the viewer path : /usr/bin/evince
And the Clean Extensions : .aux, .bbl, .blg, .fdb_latexmk, .fls, .log, .synctex.gz

Yes, it's still impossible to get a "one-shot compilation".
The tex file doesn't change anything, 
Maybe the problem came with the last package update.
Moreover, there is no "compiling" message in the status bar (bottom of the window) so I can't see when the compilation fail.

**Comment by glampr** [comment]
I have a similar problem in Mac OS X.

Most of the times (but not always), when I build, I get a "Latex compilation error" message at the status bar, but when I click on it, there are no error messages in the log. If I hit Cmd+B again then the build succeeds and the pdf is displayed in Skim. Actually the pdf gets build correctly from the first build command (if I do File => Revert in Skim I can see the changes), but for some reason, the package thinks the build failed, and I have to build again to see the new file in Skim, and make the "Latex compilation error" message go away.

OS: El Capitan 10.11.2
TeX 3.14159265 (TeX Live 2015)
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
latex.builder : latexmk
latex.outputDirectory: [blank]

**Comment by yitzchak** [comment]
@borisxXx and @glampr can you verify that this still occurs using version 0.36.0?

**Comment by glampr** [comment]
From a little experimenting I did, I see that this has now been resolved.

However, 
- in the case that there are warnings in the log (i.e. undefined references) there is no indication about this in Atom UI.
- in the case there were actual errors in the build, the 'Latex compilation error' link at the bottom right is not longer clickable.

**Comment by yitzchak** [comment]
Thanks for checking @glampr!

We are working on displaying warning and errors in a more meaningful way. This currently being tracked via #23.

I believe that the issue with broken error link has been resolved and will appear in the next version. It is being tracked via #160.
