### ISSUE TITLE
Inverse search from okular

### ISSUE THREAD

**Issue by siddhartha-gadgil** [thomasjo/atom-latex#158]

**Comment by thomasjo** [comment]
You should be able to set this up by going to Settings->Configure Okular->Editor and specifying a custom editor. I haven't got got access to a VM right now with Okular and Atom, but something like this should work

```
atom %f:%l
```

Let me know if that works or not, and I'll spin up a VM and figure it out. Also see e.g. [this thread](http://ubuntuforums.org/showthread.php?t=1088573) on the Ubuntu forums for reference.

**Comment by siddhartha-gadgil** [comment]
Works fine. Thanks.

**Comment by thomasjo** [comment]
Awesome!
