### ISSUE TITLE
Clean command with custom output directory not working

### ISSUE THREAD

**Issue by pedro93** [thomasjo/atom-latex#159]
I set the output directory to "bin", when I build the latex document it works, all generated files go there (except the pdf file which is correct for my setup) however when I call clean, the generated files in the bin folder are not deleted.

**Comment by thomasjo** [comment]
This was fixed in #156. I'm going to cut a new release now.

**Comment by thomasjo** [comment]
Just released v0.29.0 which fixes this. Thanks to @Poeschl for providing the fix!
