### ISSUE TITLE
Unable to open log from 'Latex compilation error' button

### ISSUE THREAD

**Issue by pedro93** [thomasjo/atom-latex#160]
I am unsure if this is an error in Atom's core feature or in this plugin but when I have a compilation error in my latex folder, it shows the Latex compilation error however on clicking it, no logs are shown.
I am using:
OS X 10.10.5
Atom version: 1.3.2
Latex Plugin: Latest
MacText: Version 3.14159265-2.6-1.40.16 (latest I think)

**Comment by timtro** [comment]
@pedro93  Does this happen to be a distributed (multi-file) document?

**Comment by pedro93** [comment]
@timtro Yes it is. The document is split into multiple chapter files

**Comment by thomasjo** [comment]
@pedro93 I haven't verified this, but I believe @timtro has indeed hit the nail on the head. Does the functionality behave as expected for you with a single-file document?

**Comment by pedro93** [comment]
I have not yet tried with a single-file document, I wil try it out soon. However the question remains, why can you not see the compilation logs in a multi-file doc?

**Comment by thomasjo** [comment]
Most likely an oversight/bug in the relevant code that associates the `.tex` file with the corresponding `.log` counterpart. See e.g. https://github.com/thomasjo/atom-latex/blob/5d919fa72af46f7999d17dfcdd674b22187e9f28/lib/builder.js#L72-L78

**Comment by timtro** [comment]
@thomasjo Thanks for taking over. Sorry I dropped of the planet for a week.

**Comment by BennyRe** [comment]
For me this error occurs on a single-file document.

Ubuntu 14.04
Atom 1.2.0
latex plugin 0.29.0
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)

**Comment by daudich** [comment]
I am also having this issue. However, the only time the logs won't open is if I build the tex file in a new window. If I build tex files in the first window it works. I have two windows (Ctrl+Shift+N) open.

**Comment by lujiwen** [comment]
I also have the similar problem.
For me this error occurs on a multi-file document 
win8 
atom 1.5.4
latex plugin 0.32.0
texlive

**Comment by Vigour-S** [comment]
I met this problem on single-file document
mac
atom1.3.2
mac 10.9.4
latex plugin 0.32.0
latex MacText

**Comment by daudich** [comment]
I was able to fix this by installing the latest version of Atom and updating all of my plugins.

**Comment by Cherkah** [comment]
me too i have the similar problem. on a onefile document 
win10
atom 1.5.4
latex plugin 0.33.0
miktex
builder texify/
engine  lualatex/pdftex

**Comment by yitzchak** [comment]
If you have observed this in the past please upgrade to v0.36.1 and confirm that you still see this behavior.

**Comment by yitzchak** [comment]
Closing as I believe this was fixed in v0.36.1. Will reopen if needed and reported using `latexmk` as we are deprecating `texify`.
