### ISSUE TITLE
Clean does not clean subdirectories (using latexmk)

### ISSUE THREAD

**Issue by orzechow** [thomasjo/atom-latex#161]
When including tex-files of subdirectories with

    \include{subdir/Chapter1}

and using the latexmk engine, at least all aux-files still remain in this subdirectory after cleaning.

To reproduce this, use my small test repo [orzechow/latexmk-clear-test](https://github.com/orzechow/latexmk-clear-test).

At first I thought it might be a latexmk bug and actually encoutered one with exactly the same behaviour. This latexmk bug has been confirmed, but as I saw in the code, atom-latex does not even call latexmk for cleaning. (Why not actually?)
So it seems to be an issue of atom-latex.

**Comment by thomasjo** [comment]
> To reproduce this, use my small test repo orzechow/latexmk-clear-test

Thanks for that! Really helpful.

> atom-latex does not even call latexmk for cleaning. (Why not actually?)

To have control over which files are cleaned.

> So it seems to be an issue of atom-latex.

Yeah, this is just a limitation of the somewhat naïve cleaning routine. I haven't really given it much thought as to the best way to implement this. Recursing through directions seems ill-advised, but could work as a stop-gap solution until a better approach is implemented. I'm a little bit concerned about accidentally nuking the wrong files though, even though they can easily be recreated.

**Comment by cbrnr** [comment]
Related to this, it would be nice to be able to specify a folder name (possibly including wildcards) in addition to file extension. For example, the `minted` package produces a temporary folder called `_minted-ROOT` (where `ROOT` is the file name of the `.tex` file). Or is this already possible?

**Comment by thomasjo** [comment]
Wildcard support is not supported as of now. I'm also unsure if that's even possible if/when #241 lands. /cc @yitzchak

**Comment by yitzchak** [comment]
I'll add `minted` to list the of scenarios to test with #241.
