### ISSUE TITLE
Mark editor with warnings and errors

### ISSUE THREAD

**Issue by Focus** [thomasjo/atom-latex#165]
Nice work on the package! I would very much like it if the lines with errors and warning were shown on the editor as a marker with a decoration (perhaps red for error and yellow for warning). Would it be possible to do this?

I have found the relevant documentation here:
https://atom.io/docs/api/v1.5.3/Decoration
https://atom.io/docs/api/v1.5.3/TextEditor#instance-markBufferRange

**Comment by thomasjo** [comment]
Fixed in #167
