### ISSUE TITLE
New settings not taking effect

### ISSUE THREAD

**Issue by daudich** [thomasjo/atom-latex#171]
After I change the engine to a `pdflatex`, and rerun build. When I open the logs it still tells me that the engine is XelaTex. I have tried restarting atom and running build. It still builds with `xelatex`. I have confirmed that I have both engines installed and can build directly from the commandline.

When I do try to build the tex file, nothing is generated (.aux, .log, etc). However, it does tell me that there is a "LaTeX compilation error".

**Comment by thomasjo** [comment]
In order to help you debug this I'm going to need a little bit more information. As a start, what version of Atom and the latex package are you using? Which OS and LaTeX distribution are you using?

It would be really helpful if you could provide a minimal example that reproduces your problem reliably.

**Comment by daudich** [comment]
Atom version: 1.3.2
Latex Engine: Pdflatex
OS: elementary OS 0.3.2 Freya
Pdflatex: pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
Xelatex: XeTeX 3.1415926-2.5-0.9999.3-2014012222 (TeX Live 2013/Debian)

Simple example:
`
\documentclass[11pt, letterpaper]{article}
\begin{document}
    \section{Lorem Ipsum}
    Some text here...
\end{document}
`

**Comment by thomasjo** [comment]
@daudich I'm not 100% sure this is the problem, but you're using a rather old version of Atom. Would you mind updating to the latest version (v1.5.4) to see if that resolves the problem?

The reason I think the version might be a problem is that in the v0.30.0 release of this package, the config schema got moved to the package.json file, and I don't think your version of Atom supports this, so there might be a config schema issue that is causing your problem.

**Comment by daudich** [comment]
That's it!!! Fixed it.

Cheers!
