### ISSUE TITLE
Cannot read property 'errors' of null

### ISSUE THREAD

**Issue by Poeschl** [thomasjo/atom-latex#174]
TeXLive: pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
Atom: 1.6
Plattform: Linux Mint 17.3

After a clean installation of atom and the latex-atom plugin I got this error by compiling an tex document.

![screen](https://cloud.githubusercontent.com/assets/5469257/13947948/92d998b0-f01d-11e5-9486-847cc8ca9a86.png)

**Comment by Poeschl** [comment]
Scratch that :( Forgot the latexmk package of texlive

**Comment by thomasjo** [comment]
Thanks for the report, regardless! That kind of error (uncaught `null` reference) is not something I want my users to suffer with.
