### ISSUE TITLE
Cannot find chktex?

### ISSUE THREAD

**Issue by tothzit** [thomasjo/atom-latex#175]
Hi, 
I just started to use Atom for my go-to latex editor, and encountered a strange issue. (The package is set up properly, including the path.)
After each compilation, I get the following error, even though the file does compile just doesn't open automatically. I get the same regardless of what tex file I'm trying to compile.

> Failed to spawn command chktex. Make sure chktex is installed and on your PATH
> Error: spawn chktex ENOENT
> Error: spawn chktex ENOENT
  >  at exports._errnoException (util.js:837:11)
  > at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  > at onErrorNT (internal/child_process.js:344:16)
  > at doNTCallback2 (node.js:441:9)
  > at process._tickCallback (node.js:355:17)

Again, I do get a pdf output despite all this, so the path should be specified right. I use the TexLive distribution.

There were very few cases when I did not get the message, and they all occurred without any settings change. Unfortunately I wasn't able to reproduce that (clean building does not help).

Would be grateful for any suggestions --- although it does not make the package useless, it makes the use of it very cumbersome.
Thank you!

**Comment by thomasjo** [comment]
Sorry you're having problems! Hopefully we can work it out quickly. For a start, if you could share the output of `which chktex`, and also whatever you've configured the package's `texPath` setting to.

**Comment by tothzit** [comment]
Thanks Thomas, appreciate the help. By the way, this is a *really* great package, and required very little configuration even for pretty complicated tex files. Thanks very much for it.

So, I'm very beginner here (not in Latex but in Atom), could you tell me what you need for "which chktex"? Not sure how to check that. Otherwise, the path is configured to /usr/local/texlive/2014/bin/universal-darwin (this is where everything is, I don't have the 2015 distribution).  Since I do get a pdf output, looks like it finds what it needs for that --- including bib engine, etc.
The other quoted text is what I get every time, even for an empty standard article file.

**Comment by thomasjo** [comment]
> could you tell me what you need for "which chktex"? Not sure how to check that

Execute that shell command from your terminal (Terminal, iTerm2 or whatever you use). I just want to check that `chktex` is installed in the expected location, to rule out some odd environmental issue.

> Otherwise, the path is configured to /usr/local/texlive/2014/bin/universal-darwin

That looks correct, but I'll withhold any further conclusions until you've responded with the output of `which chktex`.

Thanks for the kind words btw! :bow:

**Comment by tothzit** [comment]
> Execute that shell command from your terminal (Terminal, iTerm2 or whatever you use).

Yes, this is what I thought, but it doesn't give any output (no warnings either, just blank). But chktex *is* in that folder, or at least I see it... (And it should be; my texlive installation was just the default.)

**Comment by thomasjo** [comment]
The fact it doesn't produce any output is perhaps a tiny bit worrisome, but ultimately shouldn't matter if we assume that the child processes spawned by `latexmk` correctly inherits environment variables.

Would you mind executing the following commands, and sharing their respective outputs;
 1. `echo $PATH | tr ":" "\n"`
 2. `find /usr/local/texlive -name "chktex" -type fl -exec ls -l {} +`

**Comment by tothzit** [comment]
Honestly I do not quite know what these mean, but here they are:

> echo $PATH | tr ":" "\n"

The output:

> /usr/local/bin
> /usr/bin
> /bin
> /usr/sbin
> /sbin
> /usr/texbin

To the other:

> find /usr/local/texlive -name "chktex" -type fl -exec ls -l {} +

The output:

> -rwxr-xr-x  1 root  staff  256588 May 22  2014 /usr/local/texlive/2014/bin/universal-darwin/chktex
> -rwxr-xr-x  1 root  staff  140264 May 22  2014 /usr/local/texlive/2014/bin/x86_64-darwin/chktex

Is this what it should be?

**Comment by tothzit** [comment]
Dear Thomas,

Just wanted to let you know that interestingly, I have not had the problem lately. I changed nothing in the latex setup or in the settings, so not sure what happened. But perhaps until I can reproduce the error again, everything is good.
Thanks very much for the help though, and really for the package!

**Comment by thomasjo** [comment]
@tothzit Glad to hear the problem has been resolved, even if magically :smiley: 
I'll close this issue for now, but if you manage to reproduce the problem again, feel free to re-open.
