### ISSUE TITLE
Unable to use marked

### ISSUE THREAD

**Issue by kvchen** [thomasjo/atom-latex#176]
I'm attempting to use the `minted` package in my LaTeX file. I've enabled shell escape and installed `pygments` via pip, and I can see that `pygmentize` is in my PATH:

```
kevinchen@keff-mba ~/D/b/c/h/a/build> which pygmentize
/usr/local/bin/pygmentize
```

but when I try to compile the file from Atom, I get the following error:

```
runsystem(which "pygmentize" && touch "studyguide.aex")...executed.



./studyguide.tex:10: Package minted Error: You must have `pygmentize' installed to use this package.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...
```

**Comment by thomasjo** [comment]
This is unfortunately a side-effect of Atom not inheriting the "proper" environment variables of your interactive shell when launched from the Dock or similar means. E.g your shell environment variables such as `PATH` etc are not made available to Atom unless you launch from a shell via `atom`.

This has been fixed recently in Atom however (see https://github.com/atom/atom/pull/11054). Hence you have three workarounds/options available;
  1. Use a beta or developer version of Atom until the PR ships in a stable release.
  2. Update the `texPath` variable to include `/usr/local/bin/`. E.g. `/usr/local/bin:/your/tex/dist/here`.
  3. Until option 1 lands in stable, always launch Atom from a shell.

**Comment by kvchen** [comment]
Looks like switching to the Atom beta channel worked! I wasn't able to get it working by opening Atom via my terminal, but I assume that's a problem with interactive vs login shell that I don't really want to deal with at the moment. Thanks so much!
