### ISSUE TITLE
Feature request: Shortcut for build.

### ISSUE THREAD

**Issue by jbkr** [thomasjo/atom-latex#181]
Currently, the only way to build that is obvious is via the menu item. 

![screen shot 2016-05-25 at 13 00 00](https://cloud.githubusercontent.com/assets/6866798/15528698/ce0ba328-2278-11e6-9b83-10ea1004a462.png)

Is there any chance that a build shortcut could be added in a future release? For example: `ctrl+shift+L` or something.

**Comment by thomasjo** [comment]
There is a keyboard shortcut; you can use `ctrl + alt + b`, but it requires that you install the [language-latex package](https://atom.io/packages/language-latex) since the keymap is scoped to the `latex` grammar.

You can also enable automatic builds on save via the settings.
