### ISSUE TITLE
Suggested keybinding selectors

### ISSUE THREAD

**Issue by AustinConlon** [thomasjo/atom-latex#187]
In the keybindings part of settings when I click the clipboard icon for one it copies

```
'atom-text-editor[data-grammar~='latex']':
  'cmd-b': 'latex:build'
```

but I think it should be

```
'atom-text-editor[data-grammar~="latex"]':
  'cmd-b': 'latex:build'
```

**Comment by yitzchak** [comment]
It looks like the copy button in Atom's settings seems to assume keymaps are written in CSON
and does not escape single quotes. PR forthcoming.
