### ISSUE TITLE
Slow reflow of text

### ISSUE THREAD

**Issue by baggepinnen** [thomasjo/atom-latex#199]
Whenever I have a .tex file open and make any GUI change that causes a reflow of the text, atom freezes up for some time (seems to be proportional to the length of the tex-file and can be several seconds for a 6 page document). Changes that causes this behavior include
- Toggle tree view
- Zoom in/out text
- Resize tab
- Resize window

The problem disappear if I disable the latex package

I run fedora 23 and atom 1.6.2

**Comment by thomasjo** [comment]
This package does nothing with respect to rendering LaTeX documents, so it seems very peculiar that it should affect rendering performance. Are you sure it's caused by this package and not [language-latex](https://atom.io/packages/language-latex)? The latter provides syntax highlighting.

**Comment by yitzchak** [comment]
I am going to close since have not been able to reproduce this and in light the fact this package is not involved in rendering. If need I will reopen.
