### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by thomasjo** [thomasjo/atom-latex#216]
This is a tracking issue to help us improve the overall test coverage.

Some functionality currently has little to no spec coverage, and this is something that needs to be addressed. The list below is updated as we discover (and resolve) functionality which needs better coverage.
- ~~`TexifyBuilder` has zero coverage, which **must** be improved.~~
- `KnitrBuilder` has OK coverage, but **should** be improved.
  - `canProcess`.
- `LatexmkBuilder` has OK coverage, but **should** be improved.
  - `canProcess`.
  - `logStatusCode`.
  - All permutations supported by `constructArgs`.
- `DefaultLogger` has zero coverage, which **must** be improved.
- `LogParser` has reasonable coverage, but **can** be improved.
- `BuilderRegistry` has poor coverage, which **must** be improved.
  - `getAllBuilders`.
  - ~~All permutations of `resolveAmbiguousBuilders`.~~
- `Composer` has less than ideal coverage, which **should** be improved.
  - Try to test `sync` — might need too much mocking...
  - `moveResult`.
  - `resolveOutputFilePath`.
  - `showResult`
  - Status bar indicator functionality.
- `Latex` has OK coverage, but the tests **should** be improved.

**Comment by thomasjo** [comment]
This is being resolved in #224

**Comment by yitzchak** [comment]
Resolved by #301 pending fresh review.
