### ISSUE TITLE
Terminate stuck pdflatex instances

### ISSUE THREAD

**Issue by Nauhaie** [thomasjo/atom-latex#236]
Sometimes pdflatex gets stuck in a loop (due to mistakes in some .tex files), and a new instance is launched at every new attempt to compile, without terminating the previous one. We end up with dozens of pdflatex instances running at the same time and eating up all the CPU...

**Comment by yitzchak** [comment]
Thanks for feature request! We'll look into it.

**Comment by yitzchak** [comment]
Feature has been added and will be in next release.
