### ISSUE TITLE
Build opens file.pdfsync instead of file.pdf

### ISSUE THREAD

**Issue by atpz** [thomasjo/atom-latex#245]
When building a latex file, e.g. "file.tex" the corresponding pdf file is successfully built.
However, in certain situations, the package will try to open "file.pdfsync" instead of "file.pdf."
This doesn't happen every time, but very frequently (about 1/2 of the time).
I tried using my system's PDF viewer (skim on OSX) as well as a built-in pdf viewer in atom, and the same problem occurs in both situations.
Skim will display an error message when it is asked to open the .pdfsync file (as expected).

I have been using this package for a while, and this issue only started after the most recent update.

**Comment by yitzchak** [comment]
Do you have a sample LaTeX document that demonstrates the error (at least intermittently)?

**Comment by yitzchak** [comment]
Belay my last. I just reproduced it. We will have a patch release in a bit.

**Comment by yitzchak** [comment]
Fixed in released v0.37.1
