### ISSUE TITLE
The file “main.pdf” could not be opened.

### ISSUE THREAD

**Issue by samueljsb** [thomasjo/atom-latex#247]
When building a pdf using latexmk and pdflatex to build a pdf, Preview gives the following message when it tries to open the file:
"It may be damaged or use a file format that Preview doesn’t recognize."

This error started when I updated the package this afternoon.

**Comment by yitzchak** [comment]
Do have a simple LaTeX file that produces the error and was `main.pdf` the name of the original file?

**Comment by yitzchak** [comment]
Closing due to lack of reproduction/information. Will reopen if needed.
