### ISSUE TITLE
synctex does not work with knitr

### ISSUE THREAD

**Issue by harmsk** [thomasjo/atom-latex#251]
If an Rnw file is build with the concordance option and the synctex.gz file is patched, then ctrl-alt-s should work for Rnw files.

Attached is a working example: [knitr_synctex.tar.gz](https://github.com/thomasjo/atom-latex/files/522508/knitr_synctex.tar.gz)

Please note that because atom-latex does not yet support the concordance option and patching, you will need to do this with the Makefile in the example.

To test this out:
```sh
# install R library patchSynctex
make rSnapshot

# compile pdf
make
```

Now try to use synctex in Atom; ctrl-alt-s in the Rnw file. It should take you to the location in pdf-view. It doesn't do anything.

If you add Rnw as a file extension to this function in composer.js
```javascript
  isTexFile (filePath) {
    // TODO: Improve will suffice for the time being.
    return !filePath || filePath.search(/\.(tex|lhs|Rnw)$/) > 0
  }
```
It works. But I'm not sure this is the best way to fix this.

**Comment by yitzchak** [comment]
Thank for the issue report and thanks for tracking down the origin of the guard call.

We'll look into the best way to accomplish this when we get a chance.

**Comment by harmsk** [comment]
If you have an idea about the best approach to fixing this, I am more than happy to submit a pull request.

It doesn't feel right to add Rnw to isTexFile().
Should we have a separate function for isKnitrFile() maybe?
Or maybe a isSynctexable() function?

**Comment by yitzchak** [comment]
Any help is always appreciated so if you are up for submitting a PR then go right ahead! I would probably suggest `isKnitrFile` since we rely on `isTexFile` elsewhere.

Whatever you decide to do, your `Makefile` has given me enough information to see how to implement the SyncTeX patching. I've put it on my todo list.
