### ISSUE TITLE
dvi to pdf conversion is run multiple times when building

### ISSUE THREAD

**Issue by karyon** [thomasjo/atom-latex#255]
using XeTeX, Version 3.14159265-2.6-0.99996 (MiKTeX 2.9 64-bit)

when doing changes that require xetex to be run multiple times, it also runs the dvi to pdf conversion multiple times. what i see in the task manager is roughly this
```
1s biber
5s xetex
30s xdvipdfmx <- this seems unnecessary
1s biber
5s xetex
30s xdvipdfmx
```

i don't know whether xetex even allows to not run the pdf conversion. also it might be that latexmk is at fault here. i'm really not sure, but i thought i'd start here :)

**Comment by yitzchak** [comment]
This is internal to XeTeX. `latexmk` nor `atom-latex` has any control over when XeTeX runs xdvipdfm if it is told to generate a PDF. Probably because `latexmk` treats XeTeX as a pdflatex engine (not a latex engine) which means that it delegates the XDV to PDF conversion.

**Comment by karyon** [comment]
@yitzchak xelatex has the -no-pdf switch. can you tell me who is calling xelatex, latexmk or atom-latex?

**Comment by yitzchak** [comment]
Technically it is `latexmk` that is calling XeLaTeX. The `-no-pdf` just means generate of a XDVI file not a PDF. Probably equivalent to selecting DVI as the format.

**Comment by karyon** [comment]
that's exactly what i'm proposing, using -no-pdf on all but the last call to xetex, since the pdf is only needed in the last run and generating it takes a considerable amount of time, at least in my case.

unless you tell me i'm talking bs right now, i'll see whether i'll suggest this to latexmk.

**Comment by karyon** [comment]
i contacted the author of latexmk and he replied he'll likely implement it but not immediately.

**Comment by yitzchak** [comment]
Thanks for letting us know.
