### ISSUE TITLE
MacOS - overriding preview to use pdf-view

### ISSUE THREAD

**Issue by albeanth** [thomasjo/atom-latex#259]
@thomasjo thanks for this *awesome* latex tool. Quick question - on MacOS the default pdf viewer is preview (which works great). But, preview doesn't have SyncTex.... So, after looking over the options of the possible viewers, I wanted to give [pdf-view](https://atom.io/packages/pdf-view) a shot. I installed the package and can't seem to get atom to use it as the viewer - it still defaults to preview. 

I've looked through the settings of atom-latex and couldn't find anything that popped out to me. Any advice? 

Thanks!

**Comment by yitzchak** [comment]
Enabling `pdf-view` is done with the 'Open in atom setting`.

**Comment by albeanth** [comment]
@yitzchak Got it. Thanks!

...now if only there was a way to open pdf-view in a new window....

**Comment by yitzchak** [comment]
You might also consider the [Skim](http://skim-app.sourceforge.net/) viewer. It takes precedence over Preview.
