### ISSUE TITLE
Implement log parsing

### ISSUE THREAD

**Issue by thomasjo** [thomasjo/atom-latex#26]
- [x] Resolve output file.
- [x] Detect errors.
  - [x] Make sure we're detecting all possible errors.
- [x] Detect warnings.
- [ ] Display error and warning messages to the user in a friendly, convenient way.
  - [ ] Link error and warning messages to file and line number.

~~- [ ] If TeX file hasn't changed, parse log file instead?~~ (Requires way too much work due to root/master file support.)

**Comment by anicetojunior** [comment]
+1

**Comment by anicetojunior** [comment]
+1, this is a great feature...

**Comment by thomasjo** [comment]
I've got some holiday coming up in a couple of weeks, so I'm hoping to tackle this issue, as well as #64, #93 and possible more.

**Comment by thomasjo** [comment]
Thanks to #204, this has been greatly improved. Although there's still the task of making the whole experience more user-friendly.
