### ISSUE TITLE
Windows error: "No registered LaTeX builder can process ... " 

### ISSUE THREAD

**Issue by amir-11** [thomasjo/atom-latex#261]
Having trouble setting up the package on 64-bit windows 10, with MiKTeX. I have the latexmk package installed and have attached a picture of my settings section - I don't know what a binary is and hence don't know which path to tell the package to find the MiKTeX binaries - I just made the path the folder that has the most files / most important looking files in it. Thanks!
![capture](https://cloud.githubusercontent.com/assets/20912398/19369759/baf786e8-917d-11e6-8280-eb2a6245bde5.PNG)

**Comment by yitzchak** [comment]
Your TeX path is probably correct. The issue is most likely with executing `latexmk`. See [Using latexmk with MiKTeX](https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-with-MiKTeX) for more information regarding setting up `latexmk`. Specifically, you need a Perl interpreter.

**Comment by amir-11** [comment]
I have followed the instructions accordingly , although it says "The Perl binaries also need to be in the search path. The installers should take care of this automatically, but a system restart may be needed for the change to take effect."

I have downloaded and installed strawberry perl, installed latexmk in the miktex package installer and restarted my computer and it still doesn't work!

**Comment by yitzchak** [comment]
Try opening up a command prompt and executing `latexmk -v`

If that works it should tell you the version of `latexmk`. Then do

```bash
latexmk -cd -pdf bar.tex
```

where `bar.tex` is your LaTeX file.

**Comment by amir-11** [comment]
OK nice! I did so and it complied + built the pdf file I wanted. I tried then building it within atom and it says "No PDF opener found. For cross-platform viewing, consider installing the pdf-viewer package."

I can't find any package of that title in the miktex package installer program or from google. Also would I have to use this -cd -pdf business to change the directory of perl command line to my wanted tex file every time in order to set this up to work for atom? If so I may just retreat back to texmaker! :(

**Comment by yitzchak** [comment]
You need to install a PDF viewer or configure the custom view path. I
suggest SumatraPDF.

**Comment by amir-11** [comment]
OK awesome, downloaded sumatra and configured the installation path in options - now upon trying to build I get a red colored error stating "An error occurred while trying to run opener (1)"

**Comment by yitzchak** [comment]
Do a clean command.

**Comment by amir-11** [comment]
Didn't work!

**Comment by yitzchak** [comment]
Did you install the 32bit or 64bit version of Sumatra?

**Comment by amir-11** [comment]
I got the 64 bit version of Sumatra and made the path in the settings for sumatra pdf go to C:\Program Files\SumatraPDF

**Comment by yitzchak** [comment]
The path needs to be the complete path toe the executable. It should be `C:\Program Files\SumatraPDF\SumatraPDF.exe`

**Comment by amir-11** [comment]
Oh my god it works, thank you so much you're the best

**Comment by yitzchak** [comment]
Awesome! Also consider checking out [pdf-view](https://atom.io/packages/pdf-view).
