### ISSUE TITLE
Forward Sync don't recognise custom jobname

### ISSUE THREAD

**Issue by Poeschl** [thomasjo/atom-latex#263]
I'm building my latex document (named Masterarbeit.tex) with following magic comments:
```latex
% !TEX program = pdflatex
% !TEX jobnames = Mobile_Augmented_Book
```
When I'm trying to use the "sync" command it opens an empty pane with ``Masterarbeit.pdf`` as tab title.

It seems that the magic job comment don't work with the sync functionality.

System:
* Atom 1.10.2
* TeX Live 2016 - Version 3.14159265
* Linux Mint 17.3

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

This just got fixed and will show up in the next version.

Cheers!
