### ISSUE TITLE
Compilation problems after Update

### ISSUE THREAD

**Issue by V1nzi** [thomasjo/atom-latex#270]
After updating to version 0.38.1 I couldn't compile any tex-files from inside atom any more.
It mostly returns the same error message:

> Underfull \hbox (badness 10000) at file.tex at line n

where line n was always line 60.
Before the update I could compile everything from inside atom without problems.
I can still compile by using command line:

> pdflatex file.tex

Also, when trying to compile a document where no output-logs were I get the error message, that the parsing of the logs failed.
And in some documents, no errors are returned when hitting build, but nothing happens, no pdf gets created.
**My Setup:**
- Manjaro Linux
- Atom 1.10.2
- Latex package 0.38.1
- Using moderncv to write applications

**Settings in the package**
- Builder: latexmk
- Engine: pdflatex
- Output format: pdf

**Comment by V1nzi** [comment]
If the underfull messages are warnings and do not interfere with building, then the building process doesn't get invoked appearently, because nothing happens when I hit build (except for the warning).
Whenever there is no output from a previous build I get the errormessage saying "Parsing of log files failed".
I've included an example document (as .txt because github doesn't let me upload .tex):

[lebenslauf-anschreiben-1.0.txt](https://github.com/thomasjo/atom-latex/files/545719/lebenslauf-anschreiben-1.0.txt)

**Comment by yitzchak** [comment]
I have not been able to reproduce the issue with your file yet. Can you please do the following?

1. Tell me what are all of your settings in `atom-latex` are.
2. Try running `latexmk -v` from the command line to see what your version is.
3  Try running `latexmk -pdf lebenslauf-anschreiben-1.0.tex` or `latexmk -pdf -outdir=<build> lebenslauf-anschreiben-1.0.tex` if you are using an output directory where `<build>` is the name of your output directory.

**Comment by V1nzi** [comment]
latexmk -v gives the following:

> Latexmk, John Collins, 22 April 2016. Version 4.45

latexmk -pdf -outdir=latex-output lebenslauf-anschreiben-1.0.tex worked and created pdf correctly.
I've included three screenshots with the settings I use in atom-latex:
![atom-latex-settings1](https://cloud.githubusercontent.com/assets/21370345/19626353/f33c547a-992f-11e6-8ec5-939493941862.png)
![atom-latex-settings2](https://cloud.githubusercontent.com/assets/21370345/19626352/f33c6668-992f-11e6-8f5a-0e905430c94d.png)
![atom-latex-settings3](https://cloud.githubusercontent.com/assets/21370345/19626354/f3420096-992f-11e6-85b7-6791dc5daf6c.png)

**Comment by yitzchak** [comment]
Try removing the forward slash from the output directory settings. It should be a relative path.

**Comment by V1nzi** [comment]
Thank you, that did the trick.
But I can't remember, that I ever changed this path after initial installation and setup and it worked before.

**Comment by yitzchak** [comment]
I'm glad that worked.

We changed the way `outputDirectory` is passed to `latexmk` recently because absolute paths cause security issues for BibLaTeX.
