### ISSUE TITLE
Parsing of log files failed when using expanded root file

### ISSUE THREAD

**Issue by villermen** [thomasjo/atom-latex#273]
My LaTeX root file changes name when releasing. I worked around having to rename the magic root comment in all the input files by setting the comment to `% !TeX root = ../*.tex`. 

I noticed in atom-latex 0.38.1 that I always receive the following error after building from non-root files:

> Parsing of log files failed.

The build completes just fine however, so I guess atom-latex assumes the given root file can not contain wildcards when parsing the log. I have reverted versions, and it works again at version 0.37.1, so it probably broke in 0.38.0.

**Comment by yitzchak** [comment]
Thank you for reporting the issue!

Is there only one LaTeX file in the parent directory?

**Comment by villermen** [comment]
Yeah. I make sure to only have one there because of the asterisk.

**Comment by yitzchak** [comment]
Just out of curiosity, how are you changing the root file name with release? It may be possible to do that with jobnames.

**Comment by villermen** [comment]
I'm changing it manually once for every release. The tex file normally ends in Rxx, but then it will have e.g. R12, indicating the release number. After building once I switch it back. I'm working with LaTeX for a company which has a big template that I do not want to edit. I'm fairly new to LaTeX so I haven't done much besides some basic markup.

Since I usually only have to do small changes during release, switching the magic root comment to the Rxx.tex variant isn't really slowing me down that much anyway. I can still build from the root document when I rename it. I just had an asterisk because I tried it out and it worked.

**Comment by yitzchak** [comment]
I think it might be possible to accomplish the same thing by keeping the root file name fixed at `foo.tex` with a magic comment in the root file of

```
%!TeX jobnames = foo-R12
```

**Comment by villermen** [comment]
I have tried this, and this is indeed a (way) better option for renaming the output file. Thanks =)

I believe that matching a file using the magic root comment should either work fully or not work at all, to avoid confusion for others.

**Comment by yitzchak** [comment]
Glad it worked out. Thanks again!
