### ISSUE TITLE
Skim 1.4.22 "An error occured while trying to run opener (1)"

### ISSUE THREAD

**Issue by GhostGambler** [thomasjo/atom-latex#274]
With Skim in version 1.4.22 (96) the package always shows the error message 

> An error occured while trying to run opener (1)

 after compilation. The document is opened in Skim, but the cursor is not moved to the position the cursor is at in the latex document. Maybe some problem with the synchronisation...?

**Comment by yitzchak** [comment]
This is a known bug (SyncTeX is broken) in Skim that will fixed in their next version.

**Comment by GhostGambler** [comment]
@yitzchak Thank you for the fast response.
