### ISSUE TITLE
Switching to latexmk builder results in failed build and uniformative error message

### ISSUE THREAD

**Issue by pwrosa** [thomasjo/atom-latex#278]
Since texify is being deprecated I tried to switch to latexmk as my builder. I installed the package as described in: https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-with-MiKTeX

When I try to build from Atom, the build always fails with an error message that simply says: "Parsing of log files failed"

A few things I noted:
1. If the build directory has a .log file (i.e. from a previous build) this error does not occur. But building into a directory that only contains the .tex file cause the error
2. When I invoke the ctrl+alt+b in Atom, the spinner in the bottom right of the progress bar sometimes says "LaTeX Rebuild" rather than "LaTeX Build"

![env](https://cloud.githubusercontent.com/assets/7400761/19665449/ff9ec9d0-9a12-11e6-9ed9-114c0eda0185.png)
![error_message](https://cloud.githubusercontent.com/assets/7400761/19665448/ff9e699a-9a12-11e6-8b66-7b950e2e2821.png)
![settings](https://cloud.githubusercontent.com/assets/7400761/19665451/017c49d0-9a13-11e6-837f-4c7d8a8be4ae.png)

**Comment by yitzchak** [comment]
Try do a clean before you build. If that does not work open a command shell and first execute `latexmk -v` and see what version you have. Then try `latexmk -pdf foo.tex` where `foo.tex` is your source file.

**Comment by yitzchak** [comment]
By the way, the second item on your list is normal behavior. If you change any settings in `atom-latex` then the next build will be rebuild.

**Comment by pwrosa** [comment]
It looks like I didn't install `latexmk` correctly. Trying to run `latexmk -v` fails. Maybe when `atom-latex` tries to build my LaTeX file, it fails immediately, `atom-latex` catches the error and tries to go to the log file but can't find it because it was never generated? In any case, it looks like this is an issue with my `latexmk` install not the Atom package

**Comment by yitzchak** [comment]
What error message do you get with `latexmk -v`? Just curious.

**Comment by pwrosa** [comment]
This error is produced for any call to latexmk:
`C:\>latexmk -v
latexmk: The script could not be found.
latexmk: Data: scriptEngine="perl", name="latexmk", path="scripts/latexmk/perl/latexmk.pl"`

**Comment by yitzchak** [comment]
I got the same error with a fresh install. Please see https://sourceforge.net/p/miktex/bugs/2537/

**Comment by yitzchak** [comment]
What error message do you get with `latexmk -v`? Just curious.
