### ISSUE TITLE
SyncTeX not functioning in Evince

### ISSUE THREAD

**Issue by yitzchak** [thomasjo/atom-latex#279]
According to @cbrnr SyncTeX is not functioning in Evince:

I think I left all settings at their defaults. Shell escape is enabled, and so is SyncTeX. The output directory is blank, move result to source directory is enabled. Evince path is blank, i.e. set to the default.

Evince is opening automatically after I build the document, but I don't know how to sync. I tried right-clicking in Atom and selecting "LaTeX Sync", but this doesn't do anything. I tried ctrl-clicking in Evince, and this doesn't do anything either. I even activated the gedit SyncTeX plugin, but I don't think this is necessary (or is it?).

**Comment by yitzchak** [comment]
@cbrnr The gedit plugin will break our SyncTeX implementation.

Do you have a sample LaTeX file that I can try to reproduce this issue with?

**Comment by cbrnr** [comment]
Thanks @yitzchak, I'm happy to provide more information if needed.

**Comment by yitzchak** [comment]
I don't know for sure that it will break SyncTeX, I just don't want to add extra variables to the problem.

**Comment by cbrnr** [comment]
OK, there seem to be some specific issues with the manuscript I was testing. First of all, could it be that whitespace in the path name cannot be handled? I just tried with a file called `test this.tex`, and ctrl-clicking on the PDF in Evince opens an empty file called `test%20this.tex` in Atom...

**Comment by yitzchak** [comment]
Can you try with a file without spaces? Something with a page of content.

**Comment by yitzchak** [comment]
I have reproduced. Looks like it the spaces.

**Comment by yitzchak** [comment]
@cbrnr I have a fix in the works. Thanks providing the info!

**Comment by yitzchak** [comment]
@cbrnr Should be fixed in the next version. The opener logic has also changed in that version so it will be possible to explicitly specify Evince as the opener and it will not be necessary to provide the path to Evince.

**Comment by cbrnr** [comment]
Thanks @yitzchak, I'll let you know if it works on my machine. Also, I never provided any path in the settings - Atom just opened Evince by default without me doing anything.

**Comment by yitzchak** [comment]
That setting will go away in the next version. It's not really needed since the communication with Evince happens via dbus not the executable.
