### ISSUE TITLE
Use -xelatex option of latexmk

### ISSUE THREAD

**Issue by karyon** [thomasjo/atom-latex#284]
in https://github.com/thomasjo/atom-latex/issues/255 i noticed that dvi to pdf conversion is run multiple times. i contacted the author of latexmk (john collins) and he created a new version which does that better (and which is not released yet i think).

The thing is, that improvement will not work with the `-pdflatex=` option atom-latex is using when calling latexmk. specifically, john wrote

> To use it, either use the -xelatex or the -pdfxe options on the command line, or set the $pdf_mode variable to 5 in a configuration file. 

and

> But it would definitely be a good idea for them to switch to use -xelatex option.  [...] my motivation for defining that option was to allow the possibility that in a future version, latexmk could take special action when xelatex is used. 

so yeah, i suggest using `-xelatex` instead of `-pdflatex=` when calling latexmk :)

**Comment by yitzchak** [comment]
Thank for the enhancement request! We'll look into it.

**Comment by yitzchak** [comment]
@karyon This enhancement will be in the next version. Thanks again!
