### ISSUE TITLE
SyncTex Not Working with Skim

### ISSUE THREAD

**Issue by justinriddoch** [thomasjo/atom-latex#287]
When I try to compile my latex document using Skim I get the following error:

`An error occurred while trying to run "osascript -e " set theLine to \"<integer>\" as integer set theFile to POSIX file \"<file-path>\" set theSource to POSIX file \"<tex-path>\" set thePath to POSIX path of (theFile as alias) tell application \"<skim-path>\" if true then activate try set theDocs to get documents whose path is thePath if (count of theDocs) > 0 then revert theDocs end try open theFile tell front document to go to TeX line theLine from theSource end tell " " (1).`

The PDF is complied correctly but SyncTex is not working. I am running this on Mac OS X 10.10.5 with atom-latex 39.0 and Skim version 1.4.22. If I use Preview instead of Skim the error goes away but SyncTex still doesn't work (Although I don't think Preview supports SyncTex) and if I use pdf-view SyncTex does work. In the meantime I changed showError: true to showError: false on line 30 of skim-opener.js as turning off SyncTex in the settings doesn't fix the error.

**Comment by yitzchak** [comment]
This is a known bug with Skim. See [#1128](https://sourceforge.net/p/skim-app/bugs/1128/).

**Comment by justinriddoch** [comment]
Thanks. Downgraded to Skim version 1.4.20 and everything is working great.

**Comment by yitzchak** [comment]
Awesome! Hopefully they will fix it soon.

**Comment by justinriddoch** [comment]
Hopefully they will! Thankfully though I can just specify my Skim path as /Applications/Skim-1.4.20.app‎ for atom-latex, and continue to use the updated Skim version for everything else.                                                                                                                                                                                                                 From: Tarn BurtonSent: Monday, October 31, 2016 3:05 PMTo: thomasjo/atom-latexReply To: thomasjo/atom-latexCc: Justin Riddoch; AuthorSubject: Re: [thomasjo/atom-latex] SyncTex Not Working with Skim (#287)Awesome! Hopefully they will fix it soon.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thomasjo/atom-latex","title":"thomasjo/atom-latex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thomasjo/atom-latex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yitzchak in #287: Awesome! Hopefully they will fix it soon."}],"action":{"name":"View Issue","url":"https://github.com/thomasjo/atom-latex/issues/287#issuecomment-257388952"}}}

**Comment by yitzchak** [comment]
@justinriddoch Skim just updated to v1.4.23.

/cc @thomasjo

**Comment by thomasjo** [comment]
This has been fully resolved in Skim v1.4.23.
