### ISSUE TITLE
Output Directory cleaning does not work if directory is set outside of "project"

### ISSUE THREAD

**Issue by flg** [thomasjo/atom-latex#290]
If I set OutputDirectory to "build": build works, opening the result works, clean (alt+crtl+c) works.

If I set OutputDirectory to "../build": build works, opening the result works, clean does not work (no file is deleted).

If I set OutputDirectory to "/some/absolute/path/build": build works but message parsing fails ("Parsing of log files failed", opening the result fails (no message), clean does not work (no file is deleted).

**Comment by yitzchak** [comment]
I have reproduced this issue. We changed the output directory argument passing and relative directories are now preferred. I'll look into the clean algorithm and see what is going on.

**Comment by yitzchak** [comment]
@flg This should be fixed in the next version.

**Comment by flg** [comment]
Great, thanks a lot. I tried to clone master and test it but Atom complains about not finding 'lodash' which is apparently a known issue. Is there any way I can get an early fix for this?

**Comment by yitzchak** [comment]
You probably need to do an package install also. If you want to try the code out I would do the following in a terminal.

```bash
apm uninstall latex
apm install thomasjo/atom-latex
```

This will install directly from the repo and install dependencies.

We will probably do a release in a day or two, btw.

**Comment by flg** [comment]
Thanks for the answer.

With the latest update (10 minutes ago), here's what I have:

With a relative path (e.g. ../build/somewhere): everything works but the cleaning.
With an absolute path (e.g. /same/folder/): build is invoked, but parsing of log files fails, opening of successful result fails, and cleaning does not work.

**Comment by yitzchak** [comment]
@flg The absolute path may not work yet with a build. As for the relative build, did you change any of the settings in `latex.cleanPatterns`?

**Comment by flg** [comment]
No, cleanPatterns has the default value.

I quickly strace'd atom while invoking the clean command, and it is not even trying to remove the produced files (whereas I can see calls to unlink on those file if I leave the outputDirectory blank).

I can do some more testing if it is useful.

**Comment by yitzchak** [comment]
Do you have a sample document so I can see what kind of files are getting produced?

**Comment by flg** [comment]
I made a test from scratch. outputDirectory is set to "../../tmp/latex".

In an empty directory, i create test.tex with the following contents:
```
\documentclass{article}
\begin{document}
Test test
\end{document}
```
Latex build from Atom generates: test.aux, test.fdb_latexmk, test.fls, test.log, test.pdf
Then I invoke latex clean and nothing happens.

**Comment by yitzchak** [comment]
If you still have the master branch checkout out please try `git checkout fix-output-path`. I made some fixes to path resolution there.

**Comment by flg** [comment]
I tried with the fix-output-path branch and everything seems to work now. Both with relative and absolute path. Good job and thanks a lot for your responsiveness.

**Comment by yitzchak** [comment]
Awesome! Thank you for helping us out with testing and debugging.
