### ISSUE TITLE
Not building: Parsing of log files failed.

### ISSUE THREAD

**Issue by Wadka** [thomasjo/atom-latex#298]
Issue:
Atom-Latex 0.39.1 won't build. Error Message: Parsing of log files failed. Works with textify, but not with latexmk. Am I the only one experiencing this issue?

Installation:
Using Miktex 2.9, pdflatex command works anywhere with no issues. Strawberry Perl and latexmk are installed. Building works everywhere as well, since I added the Directory to my path variable.
Building works with choosing textify in the config. Correctly shows deprecated message though, so I really want it to work with latexmk.

System:
Windows 10 64bit on Surface Pro 4

**Comment by yitzchak** [comment]
Do you have `latex.outputDirectory` set in settings?

**Comment by Wadka** [comment]
Not set. Tried with "pdf" and "C:\pdf". Same error output.

**Comment by yitzchak** [comment]
Try to do a clean, then a rebuild.

**Comment by Wadka** [comment]
Tried Latex clean with ctrl + alt + c, then build. Same error. I have no Viewer, like summatraPDF installed. I figured that won't be an issue for Building though

**Comment by yitzchak** [comment]
Set your logging level to "info" then run `latex:check-runtime` and look in the log in status bar, what does it say?

**Comment by Wadka** [comment]
Did that. Here is the Output:
No PDF capable openers were found.
latexmk check succeeded. Found Version 4.48.
Rscript check failed with Code 1 and Response "The Command Rscript is either mispelled or could not be found".
No PS capable openers were found.
No DVI capable openers were found.

**Comment by yitzchak** [comment]
I am worried that `texify` left behind some stuff. Try running `latexmk -pdf foo.tex` from the command line in the project directory.

**Comment by Wadka** [comment]
tried Building with cmd line first with the following command: `latexmk -pdf ueb1.tex`. Made changes to the tex file and tried to build with atom-latex. No error Output, but no changes where made to any out files and the pdf. Cleaned with ctrl + alt + c, works well build again, same parsing error shows up.

**Comment by yitzchak** [comment]
Is there an `uebl.log` being produced? Any error messages in there or any console error messages?

**Comment by Wadka** [comment]
The console only Outputs warnings like "blabla overfull or blub is too small". Running latexmk in the command line produces the attached .log file (had to Change the fileending for the uploading tool)
[ueb1.txt](https://github.com/thomasjo/atom-latex/files/579402/ueb1.txt)

**Comment by yitzchak** [comment]
This could be related to #297. It will get merged and released in a day or so.

**Comment by yitzchak** [comment]
@Wadka We just published v0.40.0, please let us know if the issue still exists.

**Comment by taylorpaul** [comment]
I had this same issue on Windows 10 64-Bit SP3.  I had to switch from using the $PATH variable to explicitly adding `C:\texlive\2016\bin\win32` which is the default install location. I had already added that to my $PATH but I guess it couldn't find it. So, at least on a comparable system now running 0.40.0 it is working.

**Comment by yitzchak** [comment]
@taylorpaul `%SystemDrive%\texlive\2016\bin\win32` is automatically added to the path so it should have worked without your intervention. What is `latex.texPath` currently set to? And what is your Windows `Path` environment variable set to? Just want to make sure we don't have a bug lurking here.

**Comment by Wadka** [comment]
@taylorpaul as @yitzchak already mentioned default install directories are added automatically in my case 'C:\Program Files\MiKTeX 2.9\miktex\bin\x64'. But I of Course tried to set it manually as well, but that had no effect.

**Comment by Wadka** [comment]
@yitzchak I just installed v0.40.0 but the error unfortunately still persists.

**Comment by yitzchak** [comment]
@Wadka Can you give me a rundown of your `latex` settings?

**Comment by Wadka** [comment]
I assumed you meant the latex Settings within atom-latex. See the attached file.

[atom_latex_settings.txt](https://github.com/thomasjo/atom-latex/files/583574/atom_latex_settings.txt)

**Comment by taylorpaul** [comment]
@yitzchak Here is a look at my windows `PATH` and the last line was automatically added as you stated :

![image](https://cloud.githubusercontent.com/assets/14099359/20188940/e0d82292-a72f-11e6-8ea5-20fee386cd3a.png)

As for `latex.texPath`, I set this in settings as mentioned above since $PATH wasn't working:

![image](https://cloud.githubusercontent.com/assets/14099359/20189095/854c6f86-a730-11e6-9f2c-154ff4faa41b.png)

Did you mean for me to check elsewhere for this variable? I don't have anything like that set in my env variables for windows.

**Comment by yitzchak** [comment]
@taylorpaul What happens if you set `TeX Path` to an blank?

**Comment by taylorpaul** [comment]
@yitzchak when I set it to blank the  `Parsing of log files failed.`  error returns.

**Comment by taylorpaul** [comment]
So it now works with the $PATH variable. The error was a miss configuration on my end!

I had MiKTex installed but it wasn't on my path and I thought everything was pointed to use TexLive. But when I went to PowerShell and entered the `latex` command it was still pointing to MiKTex.  So I just completely uninstalled MikTex as I was planning on using TexLive per the recommendation of your README.md. 

Sorry for the confusion, but maybe this narrows things down to a MiKTex issue on windows?

**Comment by yitzchak** [comment]
@taylorpaul Glad its working now!

**Comment by yitzchak** [comment]
@Wadka did you install `latexmk` through MiKTeX's package manager `mpm`, or did you install via some other method?

**Comment by yitzchak** [comment]
@Wadka We just released v0.41.0 which has slightly better error reporting for `latexmk` failures. Let us know what happens upon upgrade.

**Comment by Wadka** [comment]
@yitzchak I uninstalled Atom, because it did not perform well on my Surface, so I can't help you with that anymore. But maybe I'm the only one having this Problem dunno. As it seems no other Windows user is bringing up this issue

**Comment by thomasjo** [comment]
Since we longer have any way of knowing whether this is still a problem the original reporter, but has been shown to resolve the same (or similar) problem for another reporter, I'm closing this issue as resolved.

**Comment by huckl3b3rry87** [comment]
I am on UBUNTU 16.04 and I just installed TexLive on this computer for the first time so that I could try out LaTeX with Atom and I got this same error:
``
Parsing of log files failed.
```
I never had MikTex on this machine (and it is not windows). Any ideas?

**Comment by Wadka** [comment]
@huckl3b3rry87 I use atom-latex on fedora 25 and had no such issues. I didn't change the standard path settings and it worked just fine.
