### ISSUE TITLE
Clear without deleting PDF

### ISSUE THREAD

**Issue by fruitloop** [thomasjo/atom-latex#307]
Hi, I like the clear shortcut I hate it however that I have to move my PDF first since it gets deleted on clear as well.

I would love a checkbox in the settings tab that allows me to keep my PDF file on clear. I'm good with the PDF being deleted right before the build though.

Best regards
Roland

**Comment by yitzchak** [comment]
Have you tried configuring `Clean Patterns` in the settings page and removing `**/*.pdf` from the list?

**Comment by fruitloop** [comment]
Well that was fast. Thanks for clearing that up. I totally missed that line. That of course fixes my problem.

**Comment by yitzchak** [comment]
Awesome. Glad you got it worked out.
