### ISSUE TITLE
Permanent compilation error after triggering a build while it's building 

### ISSUE THREAD

**Issue by karyon** [thomasjo/atom-latex#314]
atom 1.13.0-beta5, atom-latex 0.41.0, miktex on windows 10, using xelatex 

to reproduce:
1. do a clean
2. press ctrl-alt-b
3. press ctrl-alt-b while the first build is still running
4. a red "latex log" appears with an error message like this:
![2016-12-08 16_32_15-foo-thesis tex c__projects_masterthesis atom](https://cloud.githubusercontent.com/assets/1891915/21015892/ec32dcc8-bd63-11e6-9577-d738fbb1a92c.png)
or this:
![2016-12-08 16_33_42-foo-thesis tex c__projects_masterthesis atom](https://cloud.githubusercontent.com/assets/1891915/21015945/20ac31f2-bd64-11e6-828c-00dd79e9e744.png)

there's still stuff running in the background though, because half a minute later "latex log" turns yellow (sometimes, it even turns blue and doesn't display any of the warnings i usually see) and my pdf-viewer pops up.

it also happened that i couldn't build the document at all after this happened, the "latex log" would appear in red after a second or so, in those cases only a clean helped.

**Comment by yitzchak** [comment]
Did you let the build complete after pressing the first <kbd>ctrl</kbd>-<kbd>alt</kbd>-<kbd>b</kbd>?

**Comment by karyon** [comment]
i didn't, somehow i failed to mention that. edited the OP.

**Comment by yitzchak** [comment]
This works as intended. Executing the second <kbd>ctrl</kbd>-<kbd>alt</kbd>-<kbd>b</kbd> attempts to halt the first build which results in an error message.

I'll look into the user interface a little bit and see if it is possible to clarify the current build status.

**Comment by karyon** [comment]
i'll repeat that the latex log after the second build finishes is sometimes empty, and that sometimes the build permanently errors whenever i try to build the document again, and only a clean followed by a build fixes it. are you sure this is intended behavior?

**Comment by yitzchak** [comment]
That probably do to a race condition in writing to the log. I'll look into it to see if it can be fixed.

**Comment by baggepinnen** [comment]
This is still an error. A latex clean fixes the issue, but just waiting does not.
Atom: 1.18.0
atom-latex: latest
