### ISSUE TITLE
autocomplete for local files \includegraphics \include \input (etc.)

### ISSUE THREAD

**Issue by maxheld83** [thomasjo/atom-latex#32]

**Comment by JorgeGT** [comment]
[LaTeXTools](https://github.com/SublimeText/LaTeXTools) does autocomplete as well and it's open source. Maybe it helpsl? :)

**Comment by yitzchak** [comment]
At the moment we are keeping `latex` focused on the building/processing of LaTeX documents. For auto-completion functionality I would suggest [latex-autocomplete](https://atom.io/packages/latex-autocomplete) or [latexer](https://atom.io/packages/latexer).
