### ISSUE TITLE
Add support for zathura viewer

### ISSUE THREAD

**Issue by sidahmed-malaoui** [thomasjo/atom-latex#324]
Please add the support to `zathura` viewer under linux.

**Comment by yitzchak** [comment]
Thanks for the feature request! We will look into it.

**Comment by sidahmed-malaoui** [comment]
Thanks, you are awesome devs.

**Comment by yitzchak** [comment]
@sidahmed-malaoui This feature has been added and will be in the next version.

**Comment by sidahmed-malaoui** [comment]
Like I've said, you are awesowe :)

**Comment by yitzchak** [comment]
Thanks for the compliments! And thanks again for the feedback.
