### ISSUE TITLE
Opening pdf outside of Atom fails

### ISSUE THREAD

**Issue by cbcoutinho** [thomasjo/atom-latex#332]
Hi @thomasjo,

Thanks for creating such a great tool, it's been working great as an editor in Atom.

Issue i'm running into now is that automatically opening the resulting pdf file outside of Atom fails on Linux/Gnome/OpenSUSE with Okular. Okular gives me the following error:

    Could not open file:///path/to/doc.pdf%23src:30 /path/to/doc.tex

It looks like Atom is asking Okular to open both the generated pdf and the tex file at the same time, which obviously won't work. Manually opening the pdf works perfectly - the generated document is fine, it's just the automatic opening from Atom that has an issue.

I'm on Atom 1.13.0 at atom-latex 0.42.1

Much appreciated!

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

The path to the source document is need for SyncTeX and failure might indicated that Okular has changed something. We'll look into it.

**Comment by yitzchak** [comment]
Looks like Okular has changed their url handling. I have a fix in the works.

**Comment by cbcoutinho** [comment]
Thanks for taking care of this so quickly, and looking forward to the update.

Cheers!

**Comment by yitzchak** [comment]
@cbcoutinho Just released the patch. Let us know if it works.

**Comment by cbcoutinho** [comment]
Just updated, works great. Thanks for the help!

**Comment by yitzchak** [comment]
My Awesome!
