### ISSUE TITLE
"ctrl-alt-b does nothing" updated

### ISSUE THREAD

**Issue by GiorgioYoung** [thomasjo/atom-latex#334]
I am having a problem similar to the one described here
https://github.com/thomasjo/atom-latex/issues/71

Except for me cntrl-alt-b does exactly what key bindings says it should do, toggle back to previous word from wherever cursor is. It does not appear I have a latex build option. How do I make one or fix this? Thanks!

**Comment by yitzchak** [comment]
I would check the binding of <kbd>ctrl</kbd>-<kbd>alt</kbd>-<kbd>b</kbd> using the keybinding resolver activated by <kbd>ctrl</kbd>-<kbd>.</kbd> (assuming you are on Windows/Linux). If <kbd>ctrl</kbd>-<kbd>alt</kbd>-<kbd>b</kbd> is bound to something else you can always create your own binding in your keymap file.

In any case the `latex:build` command should also be accessible from the Packages menu.

**Comment by GiorgioYoung** [comment]
Ah I should absolutely have specified I am on a macintosh. It is definitely accessible, but cumbersome to have to click around. I will try and replace the keymap binding, although I screwed this up last night.

**Comment by yitzchak** [comment]
Glad you got it working.
