### ISSUE TITLE
Shell Escape setting doesn't seem to be respected

### ISSUE THREAD

**Issue by FHeilmann** [thomasjo/atom-latex#336]
No matter what I set the "Enable shell escape" checkbox to, the call to latexmk does not include it.

`latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 "inline_python_test.tex"`

Running above command from a terminal with an added "-shell-escape" produces the expected result, while the execution from within atom fails due to a command that cannot be executed because of the restriction disabled by -shell-escape.

Running 0.42.2 version of the package and atom 1.13.0

**Comment by yitzchak** [comment]
Thank for reporting the issue!

What OS and TeX distribution are you using?

**Comment by FHeilmann** [comment]
Damn, please disregard,

i realized I had atom-latextools enabled as well and that was actually the package causing the problems.

Closing

**Comment by yitzchak** [comment]
No worries. Glad you got it working.
