### ISSUE TITLE
[Question] Support for BibTeX?

### ISSUE THREAD

**Issue by andrewmfiorillo** [thomasjo/atom-latex#337]
Hi!

I want to start using atom-latex for all of my TeX writing needs, but to do this I would need to be able to run BibTeX. It's not altogether clear to me how to do this, or whether it can be done, with the current application. The usual compile-with-bibliography operation I'm used to looks like:
`pdflatex` -> `bibtex` -> `pdflatex` -> `pdflatex`

Can you suggest a conventional, or workaround, solution to integrate BibTeX? 

My environment is Windows 7 x64. I'm running TeX Live (x86) and am using version 0.42.0 of atom-latex.

Thank you!

**Comment by yitzchak** [comment]
BibTeX should work out of the box with `latex` since it uses `latexmk` which detects and run BibTeX or Biber as needed. In other words, it should just work.

**Comment by andrewmfiorillo** [comment]
Digging through the generated log file, there seems to be no mention of BibTeX. The docs for `latexmk` say that the `-bibtex` flag is true by default, but it may be worth trying to play around with the arguments.

Is there a way to explicitly specify the arguments for `latexmk` during a build?

Thanks for helping me out with this!

**Comment by yitzchak** [comment]
The `latexmk` documentation is often misleading, IMHO. Often they say options are default when they are not really really default. In fact the `-bibtex-cond` is the default flag.

Usually specifying the backend (`bibtex` or `biber`) will cause the right program to be run automatically with `-bibtex-cond`. I would try something simple first. For instance, with `foo.tex` 

```latex
\documentclass{article}

\usepackage[backend=bibtex]{biblatex}
\bibliography{foo}{}

\begin{document}
``I was here'' said Kilroy ~\cite{wibble}.
\printbibliography
\end{document}
```

and `foo.bib`

```bibtex
@misc {
  wibble,
  author = "Quux Kilroy",
  title = "I Was There and Everywhere",
  year = "1945"
}
```

**Comment by andrewmfiorillo** [comment]
Success! It turns out that neither `biblatex` nor `biber` come included with the "medium" installation of TeX Live. Calling `latexmk` with the `-bibtex` argument threw no warnings, but after installing those packages my citations appear hunky dory.

Thanks again for your help!

**Comment by yitzchak** [comment]
Awesome! Glad you got it working. I'll dig into the `latexmk` code and see if there is way to see if `bibtex` or `biber` calls failed.

**Comment by Sleepincoffee** [comment]
I use MikeTex & Atom, Copy above code can work, but I change foo.bib ,then run it the content not change. What's wrong? and how to use other bib in another floder. Thanks

**Comment by andrewmfiorillo** [comment]
Do you have a cached version of the bib file in your directory? If so, it's
possible that BibTex is not actually running but using a cached version.

I had no success until I switched to Tex Live.

--

Typed on a mobile keyboard. Please forgive errors, if any.

**Comment by theslyprofessor** [comment]
Hey guys, I am having problems. What's really strange is that it compiles fine if I keep retrying to rebuild, but I get several intermittent errors in the process which is annoying. I am using this workflow:

```
	\usepackage{apacite}
	\bibliographystyle{apacite}
	\usepackage[strings]{underscore}
```

However, I get these errors. 
```
./Rhythm and Speech.aux:87: Missing \endcsname inserted.
<to be read again> 
                   \unhbox 
l.87 ...erman\ \BBA{} Prince}{{\APACyear {1977}}}}
                                                  
./Rhythm and Speech.aux:87: Missing \endcsname inserted.
<to be read again> 
                   \unhbox 
l.87 ...erman\ \BBA{} Prince}{{\APACyear {1977}}}}
```

Thanks,
Nakul
