### ISSUE TITLE
compile fail-Something's wrong--perhaps a missing \item.

### ISSUE THREAD

**Issue by dosplay** [thomasjo/atom-latex#338]
I use it to compile my latex file in my laptop. But it cause an error and shows
"Something's wrong--perhaps a missing \item."
The same file in my another pc, it works well. I don't know what's wrong with this package.
p.s. *.bbl file is empty in laptop, but is normal in another pc.

**Comment by yitzchak** [comment]
Do you have an example? Sounds like a typo in your document or a missing LaTeX package, maybe?

**Comment by yitzchak** [comment]
Closing assuming issue is a missing LaTeX package. Will reopen if needed.
