### ISSUE TITLE
Latex compiles and opens xdv-file

### ISSUE THREAD

**Issue by smanull** [thomasjo/atom-latex#339]
Thanks for all your work on the excellent latex-package for Atom. Since a recent TexLive-Update (I guess the update of latexmk is responsible), the compilation of my tex-file additionally creates a *.xdv file and automatically opens it with Skim. An alternative test with TextMate as desired compiled a PDF and no xdv. Is there any chance to react on that (supposed) change in latexmk?

My specs: Engine: xelatex, Output format: pdf, PDF producer: dvipfmx (but also dvipdf doesn't change anything)

Thanks a lot!

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

The recent `latexmk` update has changed the way that XeLaTeX and LuaLaTeX are used so we will probably have to adjust the code a bit. We'll take a look shortly.

**Comment by Nil-Zil** [comment]
Same problem. It reports me a "No opener can be found to open *.xdv file".
My specs: Engine: xelatex, Output format: pdf, PDF producer: xdvipfmx

**Comment by yitzchak** [comment]
Just merged the fix. Will push out a patch release shortly.

**Comment by yitzchak** [comment]
Released. Let us know how it works.

**Comment by smanull** [comment]
Thank you so much for your unbelievably fast response and handling! This is why I love the Atom community! I already updated, tried and it works perfectly. I also added the *.xdv to cleaning pattern, which perhaps you would like to add in the default pattern. 

Since we are talking, I just wanted to spotlight briefly on this thread here: https://discuss.atom.io/t/keybinding-for-italic-bold-text-in-latex/25701 I don't dare to open an issue for that, but if you would like to implement the useful shortcuts in your latex package, feel free. It works for me and is quite convenient.

All the best!!

**Comment by yitzchak** [comment]
@smanull Glad it works!

Right now we trying are keeping this package focused on compiling and viewing the resulting documents from LaTeX. There are several other packages to do editing, autocomplete, etc.  You probably want to look at [latex-autocomplete](https://atom.io/packages/latex-autocomplete) or [latexer](https://atom.io/packages/latexer). There are also other [packages](https://atom.io/packages/search?q=latex) to do hyperlinking, inline help, etc.

Just be careful with `latex-plus` and `latextools` as they have overlapping functionality with this package and may cause problems.

**Comment by Nil-Zil** [comment]
Also works, thank you for your help!
