### ISSUE TITLE
Only build on saving .tex files

### ISSUE THREAD

**Issue by joernschellhaas** [thomasjo/atom-latex#342]
As an enhancement of #150 it would be great if build on save was limited to some file types (e. g. .tex)

Additionally/alternatively, there could be a `%!TEX buildonsave = true` directive or similar.

**Comment by yitzchak** [comment]
Thank you for the feature request! We'll look into it.

**Comment by yitzchak** [comment]
This enhancement will be in the next version (based on file extension).
