### ISSUE TITLE
Building with output directory misses _.synctex.gz

### ISSUE THREAD

**Issue by cbcoutinho** [thomasjo/atom-latex#344]
I have set an output directory for all my LaTeX files so that after a successful build I'm left with only a .tex file and associated .pdf file in the current directory. This works great, and keeps the directory less cluttered, but there is still an extra .synctex.gz binary that remains. I can't see any reason why this can't also go into the build directory

Is there a reason this file needs to be at the same location as the TeX file?

**Comment by yitzchak** [comment]
The synctex.gz file is needed to support [SyncTeX](http://mactex-wiki.tug.org/wiki/index.php/SyncTeX) and must be in the same directory as the PDF file. If you don't use SyncTeX you can disable it in the settings page.

**Comment by cbcoutinho** [comment]
Oh gotcha. Thanks for the reply
