### ISSUE TITLE
issue with sumatraPDF inverse search

### ISSUE THREAD

**Issue by clsmt** [thomasjo/atom-latex#347]
I am using win 7, Atom 1.14.2 (portable version, no install), sumatraPDF 3.1.2.

After compiling any .tex file, sumatraPDF is automatically opened. But the inverse search won't work.
Alongside the compliled pdf file, two more tabs in sumatraPDF opens, one says "Error loading C:\path-to-Atom\\(x86)\Atom\atom.exe "%f.%l"". Now, my atom is in the C:\path-to-Atom\ folder, not in C:\path-to-Atom\\(x86)\Atom\. In fact this folder doesn't exist.
The other opened tab says "Error loading C:\path-to-Atom\Files", which doesn't exist.

If I now correct the inverse search path in sumatraPDF manually, inverse search will work temporarily. But next time I compile something in atom and open sumatraPDF again, it stops working.

If I installed atom in the system, everything works.

**Comment by clsmt** [comment]
Oh.... I think I know the direct reason for this bug now.
It's because my path to Atom contains an empty space in D:\Program Files\...
Then, when latex package invoke sumatra, in the inverse search path it renders D:\Program. That's it.
If I place Atom somewhere with no white space in the path, everything works.

**Comment by m0nhawk** [comment]
You can simply wrap the path to the Atom in SumatraPDF with quotes. So, with this it will work:

    "C:\path-to-Atom\(x86)\Atom\atom.exe" "%f.%l"

**Comment by clsmt** [comment]
Unfortunately no. I used the quote marks by default, and it does not fix it. 
I mentioned that you can manually fix it one time, but the next time you open up SumatraPDF, it will still fail. Maybe this is because synctex or atom is feeding the wrong path to SumatraPDF?

**Comment by yitzchak** [comment]
@clsmt `atom-latex` is going to reset the inverse search command each time a new document is opened. 

Can you check on a few things for us?

1. Restart Atom
2. Verify that `sumatra` is explicitly selected as the opener in the settings page.
3. Compile a LaTeX document and open resulting PDF from Atom.
4. Get the current setting of the inverse sync option.
5. Try inverse sync. iIf it doesn't work, what setting does work?

**Comment by clsmt** [comment]
@yitzchak 
1. Restarted atom many times. Tested on multiple machines. I cleaned .atom and texlive and reinstalled everything to confirm.
2. Yes.
3. Did it - 
4. Let me make this extra clear again.
In SumatraPDF, it should be 
`"D:\Program Files\Atom\Atom.exe" "%f.%l"` This is where my Atom is.
but now just 
`"D:\Program` Double quote at the beginning, missing the rest. 
At the same time, there is a separate tab opened in Sumatra with the title 
`atom.exe"  "%f.%l"` (yes I got the quotes right.)
In this tab there is nothing but an error message
`Error loading D:\Program Files\Atom\Files\Atom\atom.exe" "%f:%l"`
This path does not exist. Before D:\ there is no double quote, but there is a double quote at the end of the path.
5. Does not work obviously. Manually set the path to "D:\Program Files\Atom\Atom.exe" "%f.%l" would work one time. But next time open SumatraPDF it will go back to square one. 
If I move Atom to "D:\Atom\", without a white space in the path, things go smoothly without any problem.
6. I am using atom windows x64 1.15.0 zip. Texlive 2016. Windows 7. 

You are right, I think the package is feeding the inverse search path everytime SumatraPDF is opened.

**Comment by yitzchak** [comment]
Thanks @clsmt 

I'll try to reproduce and find a fix. I'll let you know if we need more info.

**Comment by yitzchak** [comment]
@clsmt I have reproduced the bug and put a fix into #357 which will be merged soon. Thanks for reporting the isssue!

**Comment by clsmt** [comment]
@yitzchak Thanks a lot for the fix!
