### ISSUE TITLE
$ character switch the colours to math mode even inside lstlisting environment

### ISSUE THREAD

**Issue by Barbrousse** [thomasjo/atom-latex#352]
The [lstlisting environment](https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings) allow the use of non-formatted text in latex documents, therefore the content of this environment shouldn't be parsed as latex syntax which is correctly done by this plugin. 

Although using the '$' in this environment doesn't produce any mistake during the compilation of the document but switch the colour syntax for the remaining text.

This leads in showing the post-lstlisting text mode with the maths mode colours and the maths mode with text mode colours. 

The following screenshot show the text inside Atom and the compiled document in an attempt to clarify my explanation :
 
![latexatomplugin](https://cloud.githubusercontent.com/assets/5922463/24019949/0c0c909a-0a92-11e7-9804-40f8a415281c.png)

Let me know if I can help on this.

**Comment by yitzchak** [comment]
I think you probably want the [language-latex](https://github.com/area/language-latex) package. It does the syntax highlighting in Atom. This one does the compilation.

**Comment by Barbrousse** [comment]
My bad, thanks for your quick response.

**Comment by yitzchak** [comment]
No worries. Cheers!
