### ISSUE TITLE
How to properly setup Evince with Synctex?

### ISSUE THREAD

**Issue by dmohns** [thomasjo/atom-latex#353]
I am having troubles to get a functional working environment with Atom + Evince incl Synctex. I have read through https://github.com/thomasjo/atom-latex/issues/162 and https://github.com/thomasjo/atom-latex/issues/279 but to no avail. As a user it's not really clear to me what is the correct way to setup Evince as viewer.

**Problems:**
- With setting Opener Evince opens PDF in pdf-view (Side note: In this case Synctex works)
- With setting Opener xdg-open opens PDF in Evince without functional Synctex
- With setting Opener custom and provide `/usr/bin/evince` as Custom PDF view path opens PDF in Evince without functional Synctex support

**Setup:**
- Atom 1.15.0, installed latex 0.42.3 and pdf-view 0.56.0
- Evince 3.22.1

**Questions:**
- What is the intended way to setup Evince?
- What is the best way for me to provide more information about my problem?

**Comment by yitzchak** [comment]
To force Evince usage make sure the `Custom Opener` field in blank and select `evince` as the opener in the opener drop down. If this still does not work then please try the following:

1. Set the logging level to `info`.
2 Run `latex:check-runtime` and look in the message panel to see if Evince was found.

**Comment by dmohns** [comment]
`latex:check-runtime` yields
```
latexmk check succeeded. Found version 4.45.
The following PDF capable openers were found: pdf-view, xdg-open.
The following PS capable openers were found: xdg-open.
The following DVI capable openers were found: xdg-open.
Rscript check failed with code 127 and response of "/bin/sh: Rscript: command not found
".
```
Apparently it cannot detect the Evince installation, which would explain the behavior. How can I find further information about **why** this happens?

PS: How can I copy/paste from the LaTeX log window?

**Comment by yitzchak** [comment]
Can you update to v0.42.4 please? I made a few changes to the Evince opener that probably won't fix your problem but provide better opening/disposal of the Evince window.

Our Evince opener implementation depends upon `dbus-native` which depends upon several modules, most notably `abstract-socket` which is compiled node module. Can you look in `~/.atom/packages/latex/node_modules` to make sure that those got installed?

Also, what distribution of Linux are you running?

P.S. copying the log window doesn't work yet.

**Comment by dmohns** [comment]
Problem still present after upgrade to to v0.42.4.

I do see a `dbus-native` folder in `~/.atom/packages/latex/node_modules` but I do *not* see a folder `abstract-socket`. I also checked for other dependencies of `dbus-native`, namely `event-stream`, `put` and `xml2js`, all of them are present.

I am running Solus 2017.01.01.

**Comment by yitzchak** [comment]
Since `abstract-socket` is a compiled module lets try the following in a shell in `~/.atom/packages/latex`

```bash
apm install --check
apm install --verbose
```

**Comment by dmohns** [comment]
From `apm install --check` we have
```
$ apm install --check
Checking for native build tools ✓
```
and from `apm install --verbose` yields a massive log. Most noteworthy is probably
```
> abstract-socket@1.1.0 install ~/.atom/packages/latex/node_modules/abstract-socket
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/share/atom/resources/app/apm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/usr/share/atom/resources/app/apm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/usr/share/atom/resources/app/apm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.9.16
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd ~/.atom/packages/latex/node_modules/abstract-socket
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN install:abstract-socket@1.1.0 abstract-socket@1.1.0 install: `node-gyp rebuild`
npm WARN install:abstract-socket@1.1.0 Exit status 1
latex@0.42.4 ~/.atom/packages/latex
├─┬ babel-eslint@7.2.0 
│ ├─┬ babel-code-frame@6.22.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@3.0.1 
│ ├─┬ babel-traverse@6.23.1 
│ │ ├── babel-messages@6.23.0 
│ │ ├─┬ babel-runtime@6.23.0 
│ │ │ ├── core-js@2.4.1 
│ │ │ └── regenerator-runtime@0.10.3 
│ │ ├─┬ debug@2.6.3 
│ │ │ └── ms@0.7.2 
│ │ ├── globals@9.16.0 
│ │ └─┬ invariant@2.2.2 
│ │   └── loose-envify@1.3.1 
│ ├─┬ babel-types@6.23.0 
│ │ └── to-fast-properties@1.0.2 
│ └── babylon@6.16.1 
├─┬ snazzy@6.0.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├── minimist@1.2.0 
│ ├─┬ readable-stream@2.2.6 
│ │ ├── buffer-shims@1.0.0 
│ │ ├── core-util-is@1.0.2 
│ │ ├── isarray@1.0.0 
│ │ ├── process-nextick-args@1.0.7 
│ │ ├── string_decoder@0.10.31 
│ │ └── util-deprecate@1.0.2 
│ ├─┬ standard-json@1.0.2 
│ │ └─┬ concat-stream@1.6.0 
│ │   └── typedarray@0.0.6 
│ └── text-table@0.2.0 
└─┬ standard@8.6.0 
  ├─┬ eslint@3.10.2 
  │ ├── doctrine@1.5.0 
  │ ├─┬ escope@3.6.0 
  │ │ ├─┬ es6-map@0.1.5 
  │ │ │ ├── d@1.0.0 
  │ │ │ ├── es5-ext@0.10.15 
  │ │ │ ├── es6-iterator@2.0.1 
  │ │ │ ├── es6-set@0.1.5 
  │ │ │ ├── es6-symbol@3.1.1 
  │ │ │ └── event-emitter@0.3.5 
  │ │ ├── es6-weak-map@2.0.2 
  │ │ └─┬ esrecurse@4.1.0 
  │ │   └── estraverse@4.1.1 
  │ ├─┬ espree@3.4.0 
  │ │ ├── acorn@4.0.4 
  │ │ └─┬ acorn-jsx@3.0.1 
  │ │   └── acorn@3.3.0 
  │ ├── estraverse@4.2.0 
  │ ├─┬ file-entry-cache@2.0.0 
  │ │ ├─┬ flat-cache@1.2.2 
  │ │ │ ├── circular-json@0.3.1 
  │ │ │ ├─┬ del@2.2.2 
  │ │ │ │ ├─┬ globby@5.0.0 
  │ │ │ │ │ ├─┬ array-union@1.0.2 
  │ │ │ │ │ │ └── array-uniq@1.0.3 
  │ │ │ │ │ └── arrify@1.0.1 
  │ │ │ │ ├── is-path-cwd@1.0.0 
  │ │ │ │ ├─┬ is-path-in-cwd@1.0.0 
  │ │ │ │ │ └── is-path-inside@1.0.0 
  │ │ │ │ ├── pify@2.3.0 
  │ │ │ │ └─┬ pinkie-promise@2.0.1 
  │ │ │ │   └── pinkie@2.0.4 
  │ │ │ ├── graceful-fs@4.1.11 
  │ │ │ └── write@0.2.1 
  │ │ └── object-assign@4.1.1 
  │ ├── ignore@3.2.6 
  │ ├── imurmurhash@0.1.4 
  │ ├─┬ inquirer@0.12.0 
  │ │ ├── ansi-escapes@1.4.0 
  │ │ ├─┬ cli-cursor@1.0.2 
  │ │ │ └─┬ restore-cursor@1.0.1 
  │ │ │   ├── exit-hook@1.1.1 
  │ │ │   └── onetime@1.1.0 
  │ │ ├── cli-width@2.1.0 
  │ │ ├── figures@1.7.0 
  │ │ ├─┬ readline2@1.0.1 
  │ │ │ ├── code-point-at@1.1.0 
  │ │ │ ├─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │ └── number-is-nan@1.0.1 
  │ │ │ └── mute-stream@0.0.5 
  │ │ ├── run-async@0.1.0 
  │ │ ├── rx-lite@3.1.2 
  │ │ └── string-width@1.0.2 
  │ ├─┬ is-my-json-valid@2.16.0 
  │ │ ├── generate-function@2.0.0 
  │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ └── is-property@1.0.2 
  │ │ └── jsonpointer@4.0.1 
  │ ├─┬ is-resolvable@1.0.0 
  │ │ └── tryit@1.0.3 
  │ ├─┬ json-stable-stringify@1.0.1 
  │ │ └── jsonify@0.0.0 
  │ ├─┬ levn@0.3.0 
  │ │ ├── prelude-ls@1.1.2 
  │ │ └── type-check@0.3.2 
  │ ├── natural-compare@1.4.0 
  │ ├─┬ optionator@0.8.2 
  │ │ ├── deep-is@0.1.3 
  │ │ ├── fast-levenshtein@2.0.6 
  │ │ └── wordwrap@1.0.0 
  │ ├── path-is-inside@1.0.2 
  │ ├── pluralize@1.2.1 
  │ ├── progress@1.1.8 
  │ ├─┬ require-uncached@1.0.3 
  │ │ ├─┬ caller-path@0.1.0 
  │ │ │ └── callsites@0.2.0 
  │ │ └── resolve-from@1.0.1 
  │ ├─┬ shelljs@0.7.7 
  │ │ ├── interpret@1.0.1 
  │ │ └─┬ rechoir@0.6.2 
  │ │   └─┬ resolve@1.3.2 
  │ │     └── path-parse@1.0.5 
  │ ├── strip-bom@3.0.0 
  │ ├── strip-json-comments@1.0.4 
  │ ├─┬ table@3.8.3 
  │ │ ├─┬ ajv@4.11.5 
  │ │ │ └── co@4.6.0 
  │ │ ├── ajv-keywords@1.5.1 
  │ │ ├── slice-ansi@0.0.4 
  │ │ └─┬ string-width@2.0.0 
  │ │   └── is-fullwidth-code-point@2.0.0 
  │ └─┬ user-home@2.0.0 
  │   └── os-homedir@1.0.2 
  ├── eslint-config-standard@6.2.1 
  ├── eslint-config-standard-jsx@3.2.0 
  ├── eslint-plugin-promise@3.4.2 
  ├─┬ eslint-plugin-react@6.7.1 
  │ └── jsx-ast-utils@1.4.0 
  ├── eslint-plugin-standard@2.0.1 
  └─┬ standard-engine@5.2.0 
    ├─┬ deglob@2.1.0 
    │ ├── run-parallel@1.1.6 
    │ └── uniq@1.0.1 
    ├── find-root@1.0.0 
    ├── get-stdin@5.0.1 
    ├── home-or-tmp@2.0.0 
    ├── minimist@1.2.0 
    └─┬ pkg-config@1.1.1 
      └── debug-log@1.0.1 
```
and
```
$ make
bash: make: command not found
```
Aha!
Vanilla Solus comes with close to no building tools. Installing those and running `apm install --verbose` fixes the Problem. 

Thanks so much!

Will close now but it arises some follow-up questions:
- Shouldn't `apm install --check` raise some sort of error?
- Shouldn't the installation via Atom interface raise an error?
(If so, what would be the places to report those?)
- Should there be a small note under Prerequisites of atom-latex?

**Comment by yitzchak** [comment]
Glad you got it fixed. At a minimum we will add a note to the opener documentation that a build environment is required for Evince support.

**Comment by simeonvar** [comment]
I have similar problem when trying to get my atom check on run time when run: 
`apm install --verbose`
(node:4695) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Checking for native build tools ✓
(node:4739) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/lib64/electron-1.6/node',
gyp verb cli   '/usr/lib64/atom/app/apm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--runtime=electron',
gyp verb cli   '--target=1.6.9',
gyp verb cli   '--dist-url=https://atom.io/download/electron',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.4.0 | linux | x64
gyp verb command install []
gyp verb install input version string "1.6.9"
gyp verb install installing version: iojs-1.6.9
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
1.6.9
gyp info ok 
Installing modules npm WARN enoent ENOENT: no such file or directory, open '/home/userblabla/package.json'
npm WARN userblabla No description
npm WARN userblabla No repository field.
npm WARN userblabla No README data
npm WARN userblabla No license field.
✓
➜  ~ apm install --verbose
(node:5073) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/lib64/electron-1.6/node',
gyp verb cli   '/usr/lib64/atom/app/apm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--runtime=electron',
gyp verb cli   '--target=1.6.9',
gyp verb cli   '--dist-url=https://atom.io/download/electron',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.4.0 | linux | x64
gyp verb command install []
gyp verb install input version string "1.6.9"
gyp verb install installing version: iojs-1.6.9
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
1.6.9
gyp info ok 
Installing modules npm WARN enoent ENOENT: no such file or directory, open '/home/userblabla/package.json'
npm WARN userblabla No description
npm WARN userblabla No repository field.
npm WARN userblabla No README data
npm WARN userblabla No license field.
✓
