### ISSUE TITLE
win7 error"No registered LaTeX builder can process..."

### ISSUE THREAD

**Issue by happygaoxiao** [thomasjo/atom-latex#358]
I have installed TeX live 2016 ,Atom ,and its three packages(latex, pdf-view and language-latex) in Win7 SP1. TeX distribution's binaries are in "D:\Program Files\texlive\2016\bin\win32". 

I wonder if I should install TeX live in its default file directory ? System environment variable Path is in existence. But I still can't build LaTex and view the pdf. The bottom of Atom shows" No registered LaTeX builder can process..."

I have read the same issue, but it's for MiKTeX. I open up a command prompt and executing latexmk -v. It shows "Latexmk, John Collins, 22April 2016,Version 4.45". In the Tex live file directory ,the TeXworks editor can work well and build pdf.

I am a newcomer for Atom and LaTex.  I have searched answers for several hours but in vain. Thanks for your help!

**Comment by yitzchak** [comment]
I would install in the default location. You can probably make it work with the install in `Program Files` but it will take more work.

**Comment by happygaoxiao** [comment]
Thanks for your help！ I will try to install the Tex live in its default location tomorrow.  I have expected to save  the storage space for my SSD， so Tex live was installed in D:\Program Files.

**Comment by happygaoxiao** [comment]
@yitzchak The _Tex Path_ is correctly set to "D:\Program Files\texlive\2016\bin\win32", but I don't know  why it doesn't work to bulid LaTex.

**Comment by happygaoxiao** [comment]
I really need some help. I have uninstalled the Tex live and reinstalled it in "D:\texlive\2016\bin\win32". The _Tex Path_ is set to "D:\texlive\2016\bin\win32". The system environment variable is also correct. But Atom still can't build _LaTex_ . It shows "No registered LaTeX builder can process C:\Users\gaoxiao\Desktop\LaTex\test01". 
    What should I do? @thomasjo @Focus  I am sorry to bother you,  but I have no choice.

**Comment by yitzchak** [comment]
Does your document have a '.tex' file extension?

**Comment by happygaoxiao** [comment]
It works!!! It's so stupid of me to do these things. Thanks a lot for your guidance.

**Comment by yitzchak** [comment]
Glad you got it working!
