### ISSUE TITLE
TypeError: old path must be a string

### ISSUE THREAD

**Issue by Sturgelose** [thomasjo/atom-latex#36]
I'm having an issue when compiling in Windows.

I get the next error, and it doesn't build.

Uncaught TypeError: old path must be a string fs.js:580fs.renameSync 
fs.js:580fsPlus.moveSync c:\ProgramData\chocolatey\lib\Atom.0.141.0\tools\Atom\resources\app\node_modules\fs-plus\lib\fs-plu…:221
module.exports.moveResult latex.coffee:123
(anonymous function) latex.coffee:66
(anonymous function) latexmk.coffee:19
exithandler child_process.js:736
emit events.js:110
maybeClose child_process.js:1013
ChildProcess._handle.onexit child_process.js:1085

Any idea how to fix this? 

Thanks!

**Comment by uwap** [comment]
Actually the bug just appeared for me under arch linux. It seem to appear pretty arbitrarily. Disabling the Move Result To Source Directory setting seem to fix it though.

**Comment by thomasjo** [comment]
I hope this was just fixed in v0.18.0. Would be great if either of you could confirm. Have been unable to reproduce this exact error, but I believe it is related to the bug I just patched.

**Comment by thomasjo** [comment]
Since I haven't heard anything new, I'm going to assume this was fixed in v0.18.0.
