### ISSUE TITLE
Feature Request: Cite suggestions from BibTex and shortkeys

### ISSUE THREAD

**Issue by tomrunia** [thomasjo/atom-latex#361]
This is not an issue but a question (or feature request). I am very happy with this plugin for Atom, but coming from SublimeText with the LaTeXTools plug-in some features would make this plug-in even better I believe. 

1. Is there a possibility to add suggestions/auto-completion for BibTex references? With LaTeXTools you would always get a list of available references in your `.bib` when opening the `\cite` tag. Currently using this plugin I always have to switch to the bib file and copy the citation key which makes citing a little more cumbersome. 

1. Is there a way to automatically insert `\emph`, `\textbf` and other formatting options? In SublimeText using the LaTeX plugin I could simple `CTLR+L, CTRL+E` press to insert `\emph` for example. 

Thanks in advance for answering my question! Keep up the good work with the plugin :+1:

**Comment by yitzchak** [comment]
Some of the compiler packages for Atom have taken the omnibus approach that Sublime's LaTeX tools has taken, but we are currently trying to keep this package focused on the compilation phase.

Autocompletion and editing assist is then provided by several other packages in Atom. See below for a list of packages that I have found to be useful (in no particular order).

- [latex-autocomplete](https://atom.io/packages/latex-autocomplete) &mdash; general autocompletion
- [latexer](https://atom.io/packages/latexer) &mdash; reference, citation and environment autocompletion
- [latex-hyperclick](https://atom.io/packages/latex-hyperclick) &mdash; hyperclick support for subfiles and references
- [language-latex](https://atom.io/packages/language-latex) &mdash; syntax highlighting
- [preview-inline](https://atom.io/packages/preview-inline) &mdash; inline previewing of equations
- [document-outline](https://atom.io/packages/document-outline) &mdash; document outline using sections, parts, etc.
- [linter-chktex](https://atom.io/packages/linter-chktex) &mdash; syntax error/warnings using linter
- [linter-spell-latex](https://atom.io/packages/linter-spell-latex) &mdash; spell checking using linter

**Comment by tomrunia** [comment]
Thanks for the quick and complete response! Regarding the BibTex suggestions the `latexer` package works like a charm! The shortkeys for inserting the formatting options are not yet working using of the plug-in you mention, but I guess I can also add manual shortkeys for inserting them.

**Comment by yitzchak** [comment]
Glad to be of help!
