### ISSUE TITLE
Feature Request: Only build on save for compilable .tex files

### ISSUE THREAD

**Issue by arewm** [thomasjo/atom-latex#362]
This is an extension of #342, but I figured that it is probably better to have its own issue.

I often make LaTeX documents by separating section into their own .tex files. If I enable build on save, it fails when saving these files because they are not a fully defined files. Would it be possible to have some directive (i.e. in a comment) that I can put into the top of a linked file to point to the main document that should be compiled upon save?

**Comment by yitzchak** [comment]
This is accomplished by using [TeX magic](https://github.com/thomasjo/atom-latex#overriding-build-settings) comments. At the top of your sub-document insert the line (where `master.tex` is the name of your rool document)

```latex
%!TeX root = master.tex
```

**Comment by arewm** [comment]
Thanks, I missed that. Works like a charm!

**Comment by yitzchak** [comment]
Awesome! Glad you got it sorted.
