### ISSUE TITLE
Feature request: arara integration

### ISSUE THREAD

**Issue by uomoinverde** [thomasjo/atom-latex#363]
Hi!

Thank you for the exceptional work done on this Atom plugin: it really helps me, in typesetting my notes and my bachelor thesis.

Are you going to integrate your plugin with [arara](https://github.com/cereda/arara)?
I think it would be a nice feature to implement and to improve automation in the LaTeX workflow, for ones using Atom.

Best regards. :-)

Filippo

**Comment by yitzchak** [comment]
Closing as this is a duplicate of #4. Please feel free to follow discussion there.
