### ISSUE TITLE
0.43.0 keeps removing the output PDF

### ISSUE THREAD

**Issue by salehliam** [thomasjo/atom-latex#373]
Hello Thomas, 

I've just installed your package with MikTex and see that have the same problem which was mentioned before with 0.23.3. 

https://github.com/thomasjo/atom-latex/issues/80

Best regards!

**Comment by thomasjo** [comment]
Thanks for the report. I will attempt to reproduce this. In the meantime, would you please share some additional details about your setup. Specifically, your version of Atom, this package, as well as Windows and MikTeX versions.

**Comment by salehliam** [comment]
Hi Thomas!

That's my setup

Windows 10 
MiKTeX-pdfTeX  (MiKTeX 2.9.6300 64-bit)
Atom 1.17.1 ia32 

Updated Atom today to its latest version, but problem still occurrs.

**Comment by yitzchak** [comment]
@salehliam Can you tell us what you have setting you have in the "Settings" page for `latex`.

**Comment by salehliam** [comment]
@yitzchak If you mean 'Engine', pdflatex is selected.

**Comment by yitzchak** [comment]
@salehliam What other settings do you have there? Specifically, what are the following set to?

- TeX Path
- Enable Shell Escape
- Enable SyncTeX
- Enable Extended Build Mode
- Output Directory
- Move Result to Source Directory
- Build on Save
- Open Result after Successful Build
- Open Result in Background

**Comment by salehliam** [comment]
@yitzchak @thomasjo
I reinstalled my whole environment for a completely different reason. Set up Latex, Perl and Atom + latex plugin again and everything works absolutely fine this time. I conclude that plugin itself  wasn't the problem in this case. Thank you for all your help.

**Comment by yitzchak** [comment]
No problem. Glad you got it working!
