### ISSUE TITLE
Command failed: arara IEEE_Flyback_aux_supply -v 'arara' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by MarkoPet1991** [thomasjo/atom-latex#374]
Hi all, 

I'm trying to build .tex file and I obtain the following error:

`Command failed: arara IEEE_Flyback_aux_supply -v
'arara' is not recognized as an internal or external command,
operable program or batch file.`

Do you know what could be the problem here? I'm using TexLive. I already tried uninstalling arara and installing it again but it is not possible to uninstall it.

**Comment by yitzchak** [comment]
We don't currently support arara but only latexmk (currently). Please see #4.
