### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by thomasjo** [thomasjo/atom-latex#377]
This issue represents a very early intention to begin planning a v1.0 release of the package.

![celebrate](https://cloud.githubusercontent.com/assets/3622/26633144/b1eb40ea-4612-11e7-9087-0edc635d8315.gif)

Some features and functionality that exist now might be removed if they are considered not very useful, too problematic, etc. After v1.0 it is extremely unlikely that any feature will ever be removed, or significantly changed. Therefore the features that make it into v1.0 need to be rock solid, and useful to the vast majority of users. Features that are removed due to stability concerns or similar, might get reintroduced at a later time.

However, if some features are truly useful, but only to a minority of users, such a feature might be extracted and reintroduced via a potential provider-based extensibility architecture instead of being removed outright.

---
- [ ] Revisit every single feature, and determine its usefulness, stability, and maintenance cost.
- [ ] Ensure every single feature is documented, and that the documentation is up to date.
- [ ] Ensure every single feature is covered by stable, cross-platform automated tests.
- [ ] Make sure that the package works out of the box without configuration (both automatic and manual) on the most common, standard platform installations using TeX Live.

**Comment by yitzchak** [comment]
Woot woot!!!

![lucy](https://cloud.githubusercontent.com/assets/1247961/26659766/3ba2e9fe-4641-11e7-9a86-1e5d1785d460.gif)
