### ISSUE TITLE
TeXification failed with status code 255

### ISSUE THREAD

**Issue by Joinyy** [thomasjo/atom-latex#380]
Atom tells me: 

> TeXification failed with status code 255 and output of "File::Path version 2.08 required--this is only version 1.07 at c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl line 131. BEGIN failed--compilation abortet at c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl line 131. C:\texlive\2016\bin\win32\runscript.tlu:679: command failed with exit code 255: perl.exe c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl -interaction=nonstopmode -f -cd -file-line-error -g -pdf "C:\Users\...\doc.tex" "

I have configured the Latex package to use pdflatex, so I don't know why there is some latexmk in the error. Also if I call the pdflatex executable from the command line on that file from anywhere in the system it succeeds. My Texlive 2016 installation is completely up to date and the /bin/ is in $PATH as I can see every time I compile my documents from the cmd.

**Comment by yitzchak** [comment]
We currently use `latexmk` as the compiler. It takes care of `pdflatex` calls. I would try checking the `latexmk` version with

```bash
latexmk -v
```

to make sure you have the most recent version.

**Comment by Joinyy** [comment]
Seems to be a perl problem on my machine...

**Comment by d4n1elchen** [comment]
@Joinyy I have the same problem. Could you please share the solution?

**Comment by d4n1elchen** [comment]
Ok, I fixed it by running the repair option of perl installer.
