### ISSUE TITLE
Cleanup causes kernel panic

### ISSUE THREAD

**Issue by stefan-balke** [thomasjo/atom-latex#381]
Hi,

thanks for the package. On my iMac, I sometimes get a kernel panic when working on an SMB share and trying to clean temporary files. I think this is a rare constellation since I couldn't reproduce this error on any other machine. However, I think it is due to the synchronous deletion. Any objections in using `fs.unlink()` instead?

Thanks.

**Comment by yitzchak** [comment]
Thanks for the suggestion! We will look into it.
