### ISSUE TITLE
Using 'nomencl' package in Atom

### ISSUE THREAD

**Issue by Vivleeys** [thomasjo/atom-latex#382]
Anyone have any success generating nomenclatures? I am a new user and when trying to build this code below, the page remains blank, and I can't seem to make it generate a .nls file either. 

I have seen on forums that there's a way to change the build settings to this: 
makeindex <filename>.nlo -s nomencl.ist -o <filename>.nls
but I'm not sure where you would do that on this package? 

Thanks.
***********************CODE*******************************

\documentclass{article}
\usepackage[utf8]{inputenc}

\usepackage{amssymb}

\usepackage{nomencl}
\makenomenclature

%% This code creates the groups
% -----------------------------------------
\usepackage{etoolbox}
\renewcommand\nomgroup[1]{%
  \item[\bfseries
  \ifstrequal{#1}{P}{Physics Constants}{%
  \ifstrequal{#1}{N}{Number Sets}{%
  \ifstrequal{#1}{O}{Other Symbols}{}}}%
]}
% -----------------------------------------

\begin{document}
\mbox{}

\nomenclature[P]{$c$}{Speed of light in a vacuum inertial system}
\nomenclature[P]{$h$}{Plank Constant}
\nomenclature[P]{$g$}{Gravitational Constant}
\nomenclature[N]{$\mathbb{R}$}{Real Numbers}
\nomenclature[N]{$\mathbb{C}$}{Complex Numbers}
\nomenclature[N]{$\mathbb{H}$}{Quaternions}
\nomenclature[O]{$V$}{Constant Volume}
\nomenclature[O]{$\rho$}{Friction Index}

\printnomenclature

\end{document}

**Comment by yitzchak** [comment]
The nomenclature build setting is a custom rule that must be passed to `latexmk` via a resource file. If you have `Enable Extended Build Mode` activated in the settings page for the `latex` package that rule will be added automatically. I tried building your document with that setting activated and it build just fine (at least on Linux/TeX Live).

**Comment by Vivleeys** [comment]
Yes I did see nomencl mentioned there so I have it activated as well :/

**Comment by yitzchak** [comment]
What OS and TeX distribution do you have? Also, what other settings do you for this package?

You might also try running `makeindex` from the command line, where `foo` is the name of your file.

```bash
makeindex foo.nlo -s nomencl.ist -o foo.nls
```

**Comment by yitzchak** [comment]
Closing. Will reopen if needed.
