### ISSUE TITLE
Autocompletion for .Rnw files in knitr

### ISSUE THREAD

**Issue by sumandoc** [thomasjo/atom-latex#389]
Hi there,

This atom package is really working great. Many thanks.

Can we add autocompletion for at least *LaTeX* part ( and if possible for R part as well just like Rstudio does) in **knitr** in **.Rnw** files?  It would greatly accelerate the workflow and productivity.

Rstudio provides R autocompletion in .Rnw files but fails for the latex part !!

Best regards,

**Comment by yitzchak** [comment]
We are currently trying to keep this package focused on the compilation phase.

Autocompletion and editing assist is then provided by several other packages in Atom. The only package that I know of that does knitr autocompletion is [latexer](https://atom.io/packages/latexer).

Below is a list of packages that I have found to be useful (in no particular order) for LaTeX/knitr editing.

- [autocomplete-bibtex](https://atom.io/packages/autocomplete-bibtex) &mdash; autocomplete-plus to fill-in keys from bibtex, citeproc JSON, and citeproc YAML files.
- [bibtex-helper](https://atom.io/packages/bibtex-helper) &mdash; autocompletes BibTeX citation formats
- [bibtex-snippets](https://atom.io/packages/bibtex-snippets) &mdash; snippets for BibTeX entries
- [document-outline](https://atom.io/packages/document-outline) &mdash; document outline for MarkDown, LaTeX, ReStructured Text, AsciiDoc and knitr using sections, parts, etc.
- [language-knitr](https://atom.io/packages/lang-knitr) &mdash; syntax highlighting
- [language-latex](https://atom.io/packages/language-latex) &mdash; syntax highlighting
- [latex-autocomplete](https://atom.io/packages/latex-autocomplete) &mdash; general autocompletion
- [latex-hyperclick](https://atom.io/packages/latex-hyperclick) &mdash; hyperclick support for subfiles and references
- [latexer](https://atom.io/packages/latexer) &mdash; reference, citation and environment autocompletion for LaTeX, MarkDown, R-MarkDown and knitr.
- [linter-chktex](https://atom.io/packages/linter-chktex) &mdash; syntax error/warnings using linter
- [linter-spell-latex](https://atom.io/packages/linter-spell-latex) &mdash; spell checking using linter
- [preview-inline](https://atom.io/packages/preview-inline) &mdash; inline previewing of equations

**Comment by thomasjo** [comment]
As explained by @yitzchak, the goal if this package is to handle the actual compilation of LaTeX (and by extension Knitr) documents. Autocompletion, syntax highlighting, etc, is done via other community packages. Seems like [latexer](https://atom.io/packages/latexer) does what you want — give it a try, and let us know how it worked out for you.
