### ISSUE TITLE
Error while closing pdf-file

### ISSUE THREAD

**Issue by Leithian** [thomasjo/atom-latex#390]
Whenever I close the adobe-reader-window that was opened after building the .pdf-file I recieve the error "An error occurred while trying to run "*Filepath to the .pdf" (1)." The pdf-build finished without errors and everything looks fine until I close the window of adobe reader.
Has anyone experienced something similar or is this normal? I couldn't find anything in the forums.
Thanks

**Comment by thomasjo** [comment]
Can you elaborate on where the reported error shows up? Does it show up within Atom, within Adobe Reader, or somewhere else? Also since you are using Adobe Reader, I am assuming you are using Windows? It would be great if you could provide more details such as operating system, Atom version, latex package version, etc. Perhaps even screenshots of the error message, or any other relevant information that can help us track down the problem.

Thanks :bowing_man:

**Comment by Leithian** [comment]
I'm sorry.
Im on Atom 1.19.0 beta1 on Windows 10 (ver. 1511) with TeX Live (no updates available there, if I'm right latex itself has the version 43315). The error pops up in the LaTeX Log in Atom, as shown in the screenshot, but only after I close the adobe window. It didn't do anything else than display an error message and I got around it by using a pdf-viewer in Atom, I just thought it might be interesting to know for you.
Is there anything else you need to know?
![atom latex error](https://user-images.githubusercontent.com/6052614/27480967-b47403aa-581a-11e7-812e-60661b849f3f.png)

**Comment by yitzchak** [comment]
I think this is related to #119 and the DDE nature of the Adobe Reader. If it is, then there is probably nothing we can do about it.

**Comment by Leithian** [comment]
I wasn't sure if it was related as it happened when closing, but since it can easily be solved by installing a pdf-viewer in Atom and even if not it's just a message and nothing else it's no problem you can't do anything about it, I just thought it might be interesting, also for others experiencing the same issue.

**Comment by yitzchak** [comment]
Completely understand and we appreciate the feedback.

Just FYI, if you want an external viewer you might consider looking at [Sumatra](https://www.sumatrapdfreader.org/free-pdf-reader.html). I can't attest to its functionality since I am not a Windows user, but I know that is commonly used.
