### ISSUE TITLE
Textification failed with status code 1, parsing of log files failed

### ISSUE THREAD

**Issue by gomezabeatriz** [thomasjo/atom-latex#392]
Hi everyone.

I am trying to install atom+live tex on Windows 7.

I have installed latex packege, but I got the folowwing error when I am trying to rub a latex file

![image](https://user-images.githubusercontent.com/15079859/27543506-a644d936-5a8a-11e7-89f3-7412c671b01b.png)

As it is possible to see in the image, I can not select the builder either!

Anyone could help me?

Kind Regards.

Beatriz.

**Comment by gomezabeatriz** [comment]
Hi yitzchack,

Sorry for my ignorance, but I do not know how to execute those commands in windows.

**Comment by gomezabeatriz** [comment]
The compiler was incorrectly installed, I have installed it again and it works.

Thank you very much!

**Comment by yitzchak** [comment]
@gomezabeatriz Glad you got it working.
