### ISSUE TITLE
Build command not working in Windows 

### ISSUE THREAD

**Issue by sumandoc** [thomasjo/atom-latex#394]
Hi there,

I am on Windows 10, 64 bit system with `Atom 1.18.0 64 bit` with `latex 0.44` package installed.

I am able to compile the tex file from LaTeX menu but however **ctrl + alt + b** shortcut is not working in my system.

Any help in this regard?

Best regards,
Suman

**Comment by yitzchak** [comment]
Do you have a working installation of `latexmk`? You can verify by executing `latexmk -v` from a command shell or by setting the logging level to `info` and running the `latex:check-runtime` command.

**Comment by yitzchak** [comment]
Disregard the previous comment. I misread your issue report. My apologies.

I would start by checking the key bindings in the `Keybindings` setting page to make sure that there is not a conflict with another package. The bindings for this package depend on the grammar for the current file containing `latex`. Basically that means that you need `language-latex` installed and you should see `LaTeX` as the file grammar in the status bar.

**Comment by yitzchak** [comment]
@sumandoc Were you able to resolve this?

**Comment by sumandoc** [comment]
Yes I was able to resolve my issue with your help. Many thanks.

**Comment by yitzchak** [comment]
Great!
