### ISSUE TITLE
Other compiler support (arara)

### ISSUE THREAD

**Issue by aleks223** [thomasjo/atom-latex#4]
Hi,

Would it be possible to let the user choose it's compiler?

For instance I do find arara much more flexible than latexmk in term of latex engine etc.

**Comment by thomasjo** [comment]
Pull request #98 added support for a `texify` (MiKTeX) based builder, so we now have another builder we should serve well as an example of how to introduce e.g. `arara` support.

**Comment by brandondube** [comment]
Is there a clean way to work with Arara with this package?  I have tried placing "arara" in the custom engine field and get an immediate compile error with nothing having happened at all.

**Comment by yitzchak** [comment]
@brandondube Supporting Arara would require writing a builder class like the ones for `latexmk` and `texify`. We have done some initial research into the issue and how it would be implemented and determined that it is going to be difficult to implement. In other words, it is probably not going to happen soon. Until then we will probably leave the issue open unless we determine that is not possible or not going happen.

**Comment by kenNash** [comment]
Just a polite +1 for arara support. ;-)

**Comment by simon123h** [comment]
Any thoughts on having no build tool at all, so just an engine? I'm compiling with a plain `pdflatex document.tex`. Shouldn't this be covered by the package as well?

**Comment by yitzchak** [comment]
@simon123h We are currently exploring the possibility of using a JavaScript based builder. This would be equivalent to calling `pdflatex` directly and detecting the need for multiple compilation without relying on an external builder like `latexmk`. Please see #367.
