### ISSUE TITLE
Auto-completion issues

### ISSUE THREAD

**Issue by trentks** [thomasjo/atom-latex#403]
I can't get to the bottom of what's causing this - but with this package, _atom-latex_, and the only other latex package, _language-latex_, installed on several systems there is a conflict for auto-complete. To elaborate if you type in something like:

`\begin{item` you'll get the popup to select the autocomplete for \begin{itemize}, if you hit enter it will autocomplete to:

    \begin{\begin{itemize}
      \item 
    \end{itemize}}

It's like there's two packages trying to autocomplete this - but I can't find which two are doing it, this happens for all autocompletions. To my mind it's required to have the _language-latex_ plugin as without it you don't get syntax highlighting.

Any ideas?

**Comment by yitzchak** [comment]
`latex` doesn't have any auto complete functionality. You are probably havibg problems with `language-latex` snippets. I usually turn them off then use an actual auto complete package such as `latexer` or `latex-autocomplete`.

**Comment by trentks** [comment]
Thanks!

Man this was driving me insane. I had to disable the entire _snippets_ package as I couldn't find a way to just disable the _language-latex_ snippets, only time will tell what repercussions there are for having done this. I've used the _latex-autocomplete_ package and it's now all working great. I had no idea the snippets package was even a thing.

**Comment by yitzchak** [comment]
Glad we could help.
