### ISSUE TITLE
Log report (on bottom bar) appears on non-latex files

### ISSUE THREAD

**Issue by lzkelley** [thomasjo/atom-latex#406]
I'm not sure if this is a bug or feature request, but currently the log report (build status, errors, warnings, info --- see pic) appears even when a non-latex file is open.  It would be great if the latex report did not appear in that case.

![screen shot 2017-08-30 at 11 09 31 am](https://user-images.githubusercontent.com/3839265/29879728-ee100fa8-8d73-11e7-8206-a49d630207fb.png)

**Comment by yitzchak** [comment]
Thanks for feature request! We'll look into it.

**Comment by eboracus** [comment]
I just came here to report this same issue. It seems that it is currently necessary to disable/enable the entire package to have it only appear at appropriate times. 😞

Dissapointed to see the stale bot has been by for a visit, could it be requested to make this 'fresh' again? (I almost submitted a duplicate issue through missing this one).

**Comment by aubreyz** [comment]
I'd +1 this issue. The appearance of the bottom Latex toolbar in every context in atom is the only real beef I have with this package which does a great and uncomplicated job.
