### ISSUE TITLE
Support pythontex in latexmk

### ISSUE THREAD

**Issue by ChristopherChudzicki** [thomasjo/atom-latex#407]
I saw that atom-latex's latexmk supports sagetex, which is great! Would it be possible to support `pythontex`, too? (https://github.com/gpoore/pythontex)

**Comment by thomasjo** [comment]
This should be possible if you enable _"Extended Build Mode"_ in the package settings, and include PythonTeX wiring in your `.latexmkrc` file. An example of this can be found in the official latexmk example files: [example_rcfiles/pythontex-latexmkrc](http://mirror.hmc.edu/ctan/support/latexmk/example_rcfiles/pythontex-latexmkrc)

I haven't got time to actually verify this right now, but definitely possible via manual user intervention.

An alternative approach is to switch from the latexmk builder to DiCy, which I believe has built-in support for PythonTeX. DiCy is the creation of @yitzchak, so he can verify whether this is the case though.

**Comment by yitzchak** [comment]
PythonTeX support ([change log](https://github.com/yitzchak/dicy/blob/master/CHANGELOG.md)) will be in the next version of [DiCy](https://github.com/yitzchak/dicy) which will be released ASAP. I just have a few things to clean up and then I'll do a PR to update the version in `atom-latex`.

**Comment by ChristopherChudzicki** [comment]
Awesome, thanks for pointing me to [example_rcfiles/pythontex-latexmkrc](http://mirror.hmc.edu/ctan/support/latexmk/example_rcfiles/pythontex-latexmkrc). The only edit I made was to change `pythontex.py` to `pythontex`.

@yitzchak  DiCy sounds cool. Glad you'll support PythonTeX soon!

**Comment by yitzchak** [comment]
@ChristopherChudzicki latex@0.47.0 includes the updated DiCy builder that supports PythonTeX.

**Comment by yitzchak** [comment]
Closing since since it also possible to configure manually using latexmkrc files and is supported out of the box with DiCy.

Thanks again for the suggestion.

**Comment by SamuelCabralCruz** [comment]
Awesome guys! I think I just spent about 2 hours trying to figure it out. Until I found this issue.
