### ISSUE TITLE
Output Directory not working on Windows 10

### ISSUE THREAD

**Issue by maecky** [thomasjo/atom-latex#409]
First of all, I want to say thank you for the awesome work you are doing. I like the plugin a lot but today I ran into an issue:

I want my generated files to be redirected to a folder called "build". Therefore, I put "build" into the "Output Directory" settings.

On Windows 10 with Latesmk version 4.52c this is not working. The folder gets created in my project but then an error occurs:
```
TeXification failed with status code 2 and output of "Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version 4.52c.

Latexmk: making output directory 'build'

Cannot write file 'build/S:\Documents\LatexTemplates\Report\main.aux'
"
Parsing of log files failed.
```

The odd thing is, the S:\Documents\LatexTemplates\Report\build got created but after that, somehow the path gets messed up?

**Comment by yitzchak** [comment]
This could be a `latexmk` bug. The most recent version ([change log](http://personal.psu.edu/jcc8/latexmk/versions.html)) has a note about changing the handling of output directories. Given that I would suggest upgrading if possible.

**Comment by maecky** [comment]
Thanks for your answer. I did update latexmk, the issue stays the same. Tried it with texlive and miktex (manually installed the latest version of latexmk).

**Comment by yitzchak** [comment]
Is `S:` a network drive or a removable drive?

You could also try executing `latexmk` from the command line to help determine if it is a `latexmk` or a `atom-latex` issue. From a command shell try:

```sh
S:
cd Documents\LatexTemplates\Report
latexmk -pdf -outdir=build main.tex
```

**Comment by maecky** [comment]
Sorry for the late response:

`S:` is a VeraCrypt volume.

I tried your suggested command from a command line. From there everything works perfectly fine (except the PDF file stays in the `build` folder but I suppose that's supposed to be?).
That means, it seems to be an `atom-latex` issue?

**Comment by yitzchak** [comment]
Is the VeraCrypt volume a physical drive?

Also, can you try using the DiCy builder so we can see if the issue is builder specific?

**Comment by maecky** [comment]
No, the VeraCrypt volume is a file that is mounted.

The DiCy builder works (sometimes). All files are generated in the .build folder and then 3 files are copied to the root:
main.pdf
main.gz
main.yaml

If I delete the .build folder and the generated files, I have to restart Atom - otherwise, the files aren't created again. There is no error message, it just doesn't work after deleting the files and folders.

**Comment by avonmoll** [comment]
I'm getting a similar issue on Windows 7. I was getting status code 1 (could not find scriptEngine: perl.exe), but after adding perl path to atom-latex settings I'm getting status code 2 with a similar error as OP.

Basically it looks like latexmk prepends the build directory instead of appending:
`Cannot write file 'build/C:\Users\-----\-----\manuscript.aux'`

Running `latexmk manuscript.tex -pdf -auxdir=dir` works fine from terminal.
