### ISSUE TITLE
Uncaught TypeError: Cannot read property 'outputFilePath' of undefined

### ISSUE THREAD

**Issue by dengemann** [thomasjo/atom-latex#41]
Hi 

trying to compile LaTeX I run into the following issue:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.168.0
**System**: Mac OS X 10.10.1
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'outputFilePath' of undefined

```
At /Users/denisaengemann/.atom/packages/latex/lib/latex.coffee:63

TypeError: Cannot read property 'outputFilePath' of undefined
  at /Users/denisaengemann/.atom/packages/latex/lib/latex.coffee:63:24
  at /Users/denisaengemann/.atom/packages/latex/lib/builders/latexmk.coffee:17:9
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Socket.<anonymous> (child_process.js:1177:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -0:05.5 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:01.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:01.9 core:cancel (atom-text-editor.editor.mini)
     -0:00.0 latex:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  },
  "latex": {
    "openResultInBackground": true,
    "texPath": "/usr/texbin/"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
color-picker, v1.2.6
language-latex, v0.4.1
latex, v0.14.0
linter, v0.9.1
linter-flake8, v1.2.0
minimap, v3.5.4
monokai, v0.9.0
selection-count, v1.6.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by palm86** [comment]
I'm getting this as well.

**Comment by thomasjo** [comment]
I'm having trouble reproducing this. Can you provide a minimal working example file that reproduces the problem on your end.

---
As a side note, there is a minor regression in the current version that simply explained means that if you invoke the *Build* command on an unsupported filetype, the result in this specific error. Therefore, make sure you're only trying to invoke the command if the currently active file has the extension `.tex` (or `.lhs` if you're using v0.15.0).

**Comment by cfriedline** [comment]
Same here.  Happy to help debug.

**Comment by dengemann** [comment]
@thomasjo It's as simple as trying to compile a LaTeX file, disappointingly I cannot give any additional hint. It just does not seem to recognize my path settings. That's weirde, from the same terminal from which I start Atom I can flawlessly run latex manually.

**Comment by palm86** [comment]
Minimal (not) working example that reproduces the problem:

\documentclass{article}

\begin{document}
  Hallo
\end{document}

**Comment by glampr** [comment]
I'm also experiencing this issue when trying to build a file that is not the main tex file but has a 
```
%!TEX root = ...some...path...
```
directive on the first line, which should indicate the relative or absolute path of the main tex file that should instead be compiled. When I build that file directly it works fine.

**Comment by arynhard** [comment]
@dengemann, @palm86, @cfriedline, @glampr : I had a lot of similar problems with this package. The developer has done a great job thus far but I needed a lot of fixes/changes and couldn't wait for merging of pull requests. I have forked this repo and made quite a bit of changes to it. The package https://atom.io/packages/texlicious is available as an alternative. @glampr, I am not sure if this package will fix your issue but if you give it a try and send me any error outputs I can look into it.

**Comment by arynhard** [comment]
@glampr: see http://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding. The problem is that  `%!TEX root` is specific to TeXShop and TeXWorks (according to this answer), but this shouldn't be hard to implement.

**Comment by thomasjo** [comment]
@arynhard @glampr Magic comments (e.g. `%!TEX root ...`) is already supported via [MagicParser](https://github.com/thomasjo/atom-latex/blob/eb775996c39c31772ea7b7c43f119587b9ca05dc/lib/parsers/magic-parser.coffee) (used in [MasterTexFinder](https://github.com/thomasjo/atom-latex/blob/eb775996c39c31772ea7b7c43f119587b9ca05dc/lib/master-tex-finder.coffee)).

I suspect the problem you guys are seeing is related to what @nscaife discovered in https://github.com/thomasjo/atom-latex/issues/46 — a bug in the log parsing implementation related to reliance on *"Output written on ..."*.

**Comment by ioquatix** [comment]
Having this problem too, straight out of the box, using texlive with macports.

**Comment by thomasjo** [comment]
I just published v0.18.0 that should resolve this problem. Well, the underlying problem is unlikely fixed (most likely incorrect `texPath` setting), but the error should be gone.

**Comment by thomasjo** [comment]
@ioquatix Where does MacPorts install TeX Live to? You'll need to configure the *TeX Path* (`texPath`) setting to point to the `bin` folder. The default on OS X is `/usr/texbin/` when TeX Live is installed via binary package.

**Comment by jbreitbart** [comment]
Just as a note: I had the same issue that is reported here (at least atom claimed it to be), however I just didn't have latexmk installed ( sudo apt-get install latexmk on Ubuntu).

@thomasjo Can you add a check if latexmk is available?

**Comment by thomasjo** [comment]
@jbreitbart I will see if I can come up with a sensible way of detecting this cross-platform. Not exactly a trivial problem, but I'll create a feature issue for it, so progress can be tracked. Good idea by the way — I really need to improve the user experience, especially with regards to the initial setup to ensure the system is "ready to rock".

**Comment by asansli** [comment]
Uncaught TypeError: Cannot read property 'outputFilePath' of undefined
For Ubuntu 14.x users here is solution

sudo apt-get install latexmk

After all you get rid of that error.

**Comment by igor25** [comment]
Hi @thomasjo ,

Thanks for your efforts! But I am still getting this problem, on both PCs I work on (both Win 8.1). I tried manually specifying the tex path either through the interface or by editing 'config.cson' but with no luck:

texPath: "C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin"

Can I simply hard-code this path somewhere in the code? If I run latexmk manually, it works just fine (the tex path is also in my %PATH%). So, reinstalling latexmk (on Win through MikTeX package manager) didn't do anything to resolve this. 

Thanks very much!

Best,

Igor

**Comment by nscaife** [comment]
@igor25 I use MikTeX on Win8.1 and I haven't had any issues.  Which error message are you getting?  I am away from my workstation for a few days, but I'm happy to check my setup for you when I get back.

**Comment by igor25** [comment]
Thanks, much appreciated! I'm getting this error:

    C:\Users\Igor\.atom\packages\latex\lib\latex.coffee:48
    Hide Stack TraceShow Stack Trace
    TypeError: Cannot read property 'outputFilePath' of undefined
      at C:\Users\Igor\.atom\packages\latex\lib\latex.coffee:48:14
      at C:\Users\Igor\.atom\packages\latex\lib\builders\latexmk.coffee:18:9
      at ChildProcess.exithandler (child_process.js:756:5)
      at ChildProcess.emit (events.js:119:17)
      at maybeClose (child_process.js:1013:16)
      at Process.ChildProcess._handle.onexit (child_process.js:1085:5)

In case it is helpful, here's my config.cson:

    "*":
      editor:
        invisibles: {}
      core:
        themes: [
          "atom-dark-ui"
          "atom-dark-syntax"
        ]
      latex:
        texPath: "C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin"
      "exception-reporting":
        userId: "756ff701-88bc-6cbc-4666-41be470220f2"
      welcome:
        showOnStartup: false

**Comment by thomasjo** [comment]
I've tried setting up a working MiKTeX 2.9 environment on a Windows 7 VM, but not had any luck getting the package to interop with MiKTeX's `latexmk`. I will return to it at some point, but for the time being the only officially supported TeX distribution is TeX Live, which is available for all platforms.

**Comment by nscaife** [comment]
Sorry for the delay!  This was a little tricky to track down.  First, for clarity, the exception occurs when looking for the _log_ file, which does not exist because `latexmk` is failing to run (which is the actual problem).  I am using the 64-bit build of MiKTeX and it looks like you are using the 32-bit build, @igor25.  It likely doesn't matter, but there will be some path differences in my examples below; for example, my `latexmk` is at `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\latexmk.exe`.

If the `texPath` config option is set, the package completely replaces the `PATH` system environment variable with the contents of this option when calling `latexmk`.  The problem is that the MiKTeX `latexmk` on Windows requires Perl, which requires an additional path.  I simulated the package's behavior and a fix in a command prompt window and you can see the problem:

![latexmk](https://cloud.githubusercontent.com/assets/644072/6579721/66a67a4e-c722-11e4-8294-452018224737.gif)

A simple solution is to just add Perl to the `texPath` config.  In this case, mine would be:

`texPath: "C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;c:\\perl64\\site\\bin;c:\\perl64\\bin"`

I tested the above and it works for me.  However, the reason it works on my system by default is that I _do not_ set the `texPath` variable.  Instead, I put the MiKTeX binary directory in my Windows default Windows system path.  The LaTeX package just uses the default path if one is not provided, and both Perl and `latexmk` exist on this path.

@thomasjo `latexmk` exits with error code 1 when this happens, but it doesn't look like the error handler on [latexmk.coffee:17](https://github.com/thomasjo/atom-latex/blob/master/lib/builders/latexmk.coffee#L17) gets called on my system.  When stepping through this in the debugger, it doesn't stop on the test.  The error handling might be broken, but I'm not sure because the debugger skips over the test like it's not there.

**Comment by thomasjo** [comment]
I believe this has been resolved. If this is still a problem, just let me know and I'll re-open.
