### ISSUE TITLE
Cleanup fails if files are hidden

### ISSUE THREAD

**Issue by mjclarke94** [thomasjo/atom-latex#412]
If your document is initialised as a git repo and atom is set to hide files in .gitignore in the viewer, the cleanup command fails to delete these files.

**Comment by yitzchak** [comment]
Thank for you for the issue report! We'll look into it.

**Comment by yitzchak** [comment]
I have not been able to reproduce this. What is your setting for `cleanPatterns` and what the names of the files that are being missed?

**Comment by hendrikbl** [comment]
I think what @mjclarke94 means is setting a hidden folder as the output directory. I experienced the same with `Clean Patterns` set to default and `Output Folder` set to `.build`. Building works fine but cleaning Fails with the warning `File needs to be saved to disk before it can be proceeded`.

**Comment by yitzchak** [comment]
Thanks @hendrikbl! I have reproduced this and have a fix in the works.
