### ISSUE TITLE
Tries to open dvi when output format is pdf

### ISSUE THREAD

**Issue by HorstBort** [thomasjo/atom-latex#418]
After successful build with pdflatex, viewer is opened with wrong file name, .dvi instead if .pdf.

Atom 1.20.1
latex 0.47.0
Ubuntu 16.04

**Comment by HorstBort** [comment]
Never mind, seems to have been a broken latexmk-config. Running latex:clean and then build again resolved this for me.

**Comment by Foggalong** [comment]
@HorstBort I just had this exact same issue! Your fix solved the problem for me too, thanks for posting it once you'd worked it out :)

**Comment by paulkernstock** [comment]
Put me on the list as well.
