### ISSUE TITLE
Warning/Error bars persist after successful compilation

### ISSUE THREAD

**Issue by gnat79** [thomasjo/atom-latex#419]
Atom 1.20.1, on OSX.
Once I create an error, I can fix it and the visual marker adjacent to line numbers remains after I recompile. This can be annoying because it still makes me think I have errors at first glance, and it's harder to tell if I've fixed it, especially if I have multiple errors and only fixed some of them.

![screen shot 2017-09-22 at 10 13 52 am](https://user-images.githubusercontent.com/11506551/30748609-cd98042a-9f7e-11e7-8f08-54046cf12b74.png)

See line 72 on the screenshot, and notice there are 0 errors in at the bottom compilation status.

The same holds for warning messages.

I can remove the marker (after noticing that it persists) by changing the line(s) where it occurs.

**Comment by yitzchak** [comment]
Thanks for reporting the issue! I have reproduced it and have a fix in the works.
