### ISSUE TITLE
DiCy/core update broke LaTeX compilation in 0.48

### ISSUE THREAD

**Issue by amyspark** [thomasjo/atom-latex#424]
With 0.48, each time I try to compile a LaTeX document, I get the following stacktrace (extracted from the LaTeX log w/Dev Tools):

```
[ApplyOptions(load;initialize;)] Ignoring attempt to set unknown option `ignoreCache` to a value of `false`
[LoadAndValidateCache(load;initialize;)] Skipping load of build cache since no version tag was found in the cache.
[ApplyOptions(load;execute;)] Ignoring attempt to set unknown option `ignoreCache` to a value of `false`
[DiCy] TypeError: Cannot read property 'includes' of undefined
at /Users/amalia/.atom/packages/latex/node_modules/@dicy/core/lib/Rules/BibToGls.js:33:124
at Generator.next (<anonymous>)
at step (/Users/amalia/.atom/packages/latex/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /Users/amalia/.atom/packages/latex/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
at F (/Users/amalia/.atom/packages/linter-htmlhint/node_modules/core-js/library/modules/_export.js:35:28)
at /Users/amalia/.atom/packages/latex/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
at Function.isApplicable (/Users/amalia/.atom/packages/latex/node_modules/@dicy/core/lib/Rules/BibToGls.js:34:7)
at /Users/amalia/.atom/packages/latex/node_modules/@dicy/core/lib/Rule.js:106:61
at Generator.next (<anonymous>)
at step (/Users/amalia/.atom/packages/latex/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)</div><div>    
at /Users/amalia/.atom/packages/latex/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13</div><div>    
at process._tickCallback (internal/process/next_tick.js:103:7)
```

`git bisect` tells me this bug was introduced by 10a240cd0a719319240704e282f08581462b305b.

**Comment by amyspark** [comment]
Cleaning all temporary files using `LaTeX: Clean` removes the exception but not the `ignoreCache` error.
Manually deleting `.dicy.yaml` and `<file name>-cache.yaml` solves the issue.

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

The `ApplyOptions` and `LoadAndValidateCache` messages are just warning messages so they shouldn't break the build. `ignoreCache` got removed in v0.10.0 and I haven't added a deprecation mechanism in DiCy yet. I'll add an issue to the DiCy repo to track it.

The `TypeError` is probably what is breaking the build. It looks like Bib2Gls is missing a guard conditional. I'll add one and release a patch shortly.

**Comment by yitzchak** [comment]
Looks the option validator is also setting the wrong message severity. Causing the `ApplyOptions` message to break the build also. Fix forthcoming.

**Comment by yitzchak** [comment]
Updated DiCy with a patch. Should be fixed for future installs/upgrades of atom-latex.
