### ISSUE TITLE
Settings don't set

### ISSUE THREAD

**Issue by GaseousClay** [thomasjo/atom-latex#425]
Hi,

I am wondering why the settings that I have specified do not work. I am using a Mac. I changed the default opener to custom and I entered the file path for my custom PDF application, but it keeps trying to open it in Skim. I have also de-selected Open Result after Successful Build, but it continues to open results. None of the settings seem to work, and I have tried restarting Atom, and restarting the files I am writing. Thank you.

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

Can you tell me what your settings in `atom-latex` are and also can you me what other non-core Atom packages you have installed?
