### ISSUE TITLE
Feature Request: Keyboard shortcut for "Toggle Log"

### ISSUE THREAD

**Issue by Nerdnussbutter** [thomasjo/atom-latex#426]
Thanks for this great extension! It is my favorite extension by far. 

However, I would like to toggle the log panel with a keyboard shortcut. Since recently, there have been circular arrow buttons (.atom-dock-toggle-button) that allowed me to toggle the panel, but I deactivated them because they are annoyingly close to the scroll bars. Hence the only way to close the panel is the "X" button at the far right, which is hard to reach on a 21:9 monitor. 

Thank you for your effort. Best regards,
Jonas

**Comment by thomasjo** [comment]
Thanks for the suggestion, but we are not going to add any more default keyboard shortcuts at this point. 

You can however easily configure this on your machine by adding something like the following to your `~/.atom/keymap.cson` file

``` cson
'atom-workspace':
  'alt-l': 'latex:toggle-log'
```

---
For further details on customizing keybindings, see the following
1. http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings
2. http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/

**Comment by Nerdnussbutter** [comment]
Thank you, that was very helpful!
