### ISSUE TITLE
latex 0.48.0

### ISSUE THREAD

**Issue by Sokolov57** [thomasjo/atom-latex#427]
build@unknown – Cannot find module '/home/username/.atom/packages/latex/node_modules/abstract-socket/build'

Just installed it, dindu nuffin
It says though
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

**Comment by yitzchak** [comment]
There should be a rebuild packages button in the status bar or the packages page in settings. Please try rebuilding then restarting Atom.

**Comment by Sokolov57** [comment]
Thx, that worked perfectly.
Sorry for vain issue.

**Comment by yitzchak** [comment]
No worries. Glad I could help.
