### ISSUE TITLE
Error to use xelatex engine

### ISSUE THREAD

**Issue by Hatuw** [thomasjo/atom-latex#429]
Hi, I tried to use "xelatex" engine for "Latex" compling but it didn't work. It used "latexmk" whatever I set. Some logs may help for fixing the issus:
latexmk: The script engine could not be found.
latexmk: Data: scriptEngine="perl.exe"
tks~

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

`latexmk` is the default builder used. It will call XeLaTeX for you. I assume that you are using the MiKTeX distribution since that script error is fairly common there. If this is so then this is probably a duplicate of #404.
