### ISSUE TITLE
latexmx:error in initializing file

### ISSUE THREAD

**Issue by ekoepplin** [thomasjo/atom-latex#435]
Hi,

I have an error I cant really solve since there are no similar cases out there. Appreciate any help!

Latex: 0.49

Mac: 10.12.5
ATOM: 1.21.1
Latex: 0.49
Latex distribution: mactex 20170524
<img width="1433" alt="error_tex" src="https://user-images.githubusercontent.com/18237090/32184921-1dc72966-bd9e-11e7-97b7-2c5235cc1ffe.png">

**Comment by yitzchak** [comment]
Thanks for reporting the issue.

Try turning `Enhanced Build Mode` off in the settings page.

**Comment by hugeme** [comment]
hi @yitzchak, that worked like a charm, at least for the example.tex, thank you!

**Comment by yitzchak** [comment]
Can you try running `latexmk --version` from the terminal so we know what version is having problems with the extended build rules?

**Comment by hugeme** [comment]
Its `Latexmk, John Collins, 19 Jan. 2017. Version 4.52c`

**Comment by yitzchak** [comment]
Thanks. Marking as bug.
