### ISSUE TITLE
How Can I change default viewer application after executing "build"

### ISSUE THREAD

**Issue by lks21c** [thomasjo/atom-latex#436]
Hi, I'm starting using atom-latex which feels so good.
Thanks for making this app.

I'm just wondering  whether I change default viewer application after executing "build".
I've got a laptop and desktop and both are Ubuntu 14.04.
I also installed the sample packages to use latex which are atom-latex and pdf-viewer and texlive-full.

But, On the laptop, after "build" step, pdf shows up in the atom pdf-viewer.
On the other hand, after "build" step, pdf shows up in documenter viewer(native application on Ubuntu)

So I tried to figure out where I can change settings like default pdf viewer, but I couldn't find it.

Could you give me any advise to work on?
Thanks.

**Comment by lks21c** [comment]
Sorry, I was able to change default viewer by switching "Opener" in settings after writing this article.

I close this issue but, I won't delete this for anyone who wonder this kinda issue.

Thanks.

**Comment by thomasjo** [comment]
Thanks for opening the issue; it tells us that we have some work to do on the documentation. I have some visions for how to improve this aspect, and this issue will definitely help guide that effort. Will leave the issue closed, but I will label it as `documentation` to make it easier to find later on.
