### ISSUE TITLE
latexmk check failed with code 1

### ISSUE THREAD

**Issue by EdsonArchela** [thomasjo/atom-latex#437]
Hi,
plugin is not working for miktex distribution. I've used it in pycharm so the problem is not the distribution. It says the script engine could not be found. latexmk: Data: scriptEngine="perl.exe". I believe in miktex that file has another name (perltex)

**Comment by yitzchak** [comment]
This is a fairly common issue with MiKTeX. Please see #404. Some have found reinstalling `latexmk` or putting the perl path in the `TeX path` setting to work.

**Comment by yitzchak** [comment]
Closing since this is a duplicate.
