### ISSUE TITLE
How to pass latexmk an argument?

### ISSUE THREAD

**Issue by phlegx** [thomasjo/atom-latex#438]
Hi!
I want to set latexmk to put all aux files in a tmp directory like this `latexmk -auxdir=./tmp`. How can I achieve this? Thx

**Comment by yitzchak** [comment]
This is not currently supported since the `auxdir` is a MiKTeX only setting. You can override any setting to `latexmk` by using a `.latexmkrc` file either in the project directory or in your home directory. For instance, using the following contents should set the aux directory.

```perl
$aux_dir = "./tmp";
```

**Comment by phlegx** [comment]
Thx @yitzchak! I will give it a try.
