### ISSUE TITLE
ctrl+alt+b not doing anything.

### ISSUE THREAD

**Issue by pairwiseseq** [thomasjo/atom-latex#440]
I have consulted 
[Issue #71 ](https://github.com/thomasjo/atom-latex/issues/71)
[Issue #334 ](https://github.com/thomasjo/atom-latex/issues/334)

and it seems my problem may be different.

I have already opened Key Binding Resolver  `ctrl+.` I see `latex:build` when I press `ctrl+alt+b` at the top of the list. Note that I am trying to execute _Build_ on a .tex file. 

**I am on Atom Version 1.20.0-betaa0, latex 0.49.0, and pdf-view 0.59.0, texlive version 2017.**

I have added the full path of pdf-view in `Custom PDF Viewer Path` option setting. Note that when I manually click `Build` via Package>Latex>Build drop-down menu, everything executes fine. `ctrl+alt+b` is not the only shortcut that doesn't work - all of the default atom-latex shortcuts do not work.

I am on Unbuntu Xenial 16.04 LTS on Samsung Chromebook Pro.

One thing I noticed is, if I type `ctrl+,` in the Key Binding Resolver, the shortcut for Atom settings pops up correctly and it's highlighted in green with a check mark next to the shortcut. However `ctrl+alt+b` or any atom-latex shortcuts, the shortcut is not highlighted in green and there is a greyed out X mark next to it.

**Comment by yitzchak** [comment]
Thank for reporting the issue!

Is the `.tex` file a LaTeX document? In other words does it have a `\documentclass`? Also, do you have [language-latex](http://atom.io/packages/language-latex) installled?

**Comment by pairwiseseq** [comment]
`\documentclass` is defined as `{article}` and I do not have language-latex installed as I felt I did not need syntax highlighting.

**Comment by yitzchak** [comment]
The keyboard shortcuts are activated by a latex grammar scope from a syntax highlighting package. Please see [Syntax Highlighting](https://github.com/thomasjo/atom-latex#syntax-highlighting) for details.

**Comment by pairwiseseq** [comment]
Brilliant, thank you! I will consult your advice and get back to this appropriately.

**Comment by yitzchak** [comment]
Glad you got it working!

**Comment by caexsura** [comment]
Hi, I'm having this same problem except that I did already have language-latex installed. I tried uninstalling, restarting atom, and reinstalling.

Key binding resolver will not recognize when I type "ctrl-alt-b". The farthest is reads is "ctrl-alt", but any other letter appears (e.g. "ctrl-alt-s"), but is greyed out. Not sure if this is more of an atom issue.
