### ISSUE TITLE
Magic TeX comments are not interpreted in TikZ files

### ISSUE THREAD

**Issue by raimund-schluessler** [thomasjo/atom-latex#444]
Magic TeX comments are not interpreted in TikZ files. If I have a TikZ file and set the TeX comment to `%	!TEX root = main.tex` in order to have the main file being compiled, after starting the compilation I get the output `The file does not appear to be a valid source file.`

If I rename the Tikz file to `*.tex`, the TeX comment works. This used to be different in previous versions of the package, but I don't know when exactly this broke. Was this change by accident or intentional?

Please also see the minimal (not) working example. If you rename tikz to tex, the main file will be compiled when starting compilation on the external file.

MWE:
file `main.tex`:
```
\documentclass[]{article}

\usepackage{pgfplots}

\begin{document}
Magic TeX comments are not interpreted in TikZ files.

\input{external.tikz}

\end{document}
```

file `external.tikz`:
```
%	!TEX root = main.tex
\begin{tikzpicture}

\draw [-,style=-, line width=0.5mm] (0,0) -- ++(8,0);

\end{tikzpicture}%
```

**Comment by thomasjo** [comment]
This was definitely not an intentional change. Although, it was never really something that we intentionally supported, so this is not covered by any automated tests or otherwise.

Which LaTeX language package are you using? Does it correctly classify `.tikz` files as LaTeX?

**Comment by raimund-schluessler** [comment]
I use three LaTeX related packages:

[language-latex](https://atom.io/packages/language-latex) in version 1.1.1
[latexer](https://atom.io/packages/latexer) in version 0.3.0
and of course this package here in version 0.49.0

Disabling the other packages does not change anything.

I use Atom 1.23.0-beta1.
