### ISSUE TITLE
Option to hide/remove log entry in statusbar

### ISSUE THREAD

**Issue by cbrnr** [thomasjo/atom-latex#449]
The LaTeX log can already be viewed by opening the bottom bar (if it is closed it can be opened by clicking on the half-circle up arrow button when the mouse is moved towards the statusbar). I prefer a clean non-bloated Atom UI, which is why I find the additional log entry in the statusbar unnecessary and distracting (especially because it also appears when non-LaTeX files are open as reported in #406).

An option to hide/remove the log entry completely in the package settings would be super useful!

**Comment by felixvalin** [comment]
I'm having the same problem, and I find it very annoying to have to disable the whole package just to get the log bar out of the way... 

I would gladly welcome the option to disable the log bar itself instead! Like @cbrnr mentionned

**Comment by chatox** [comment]
As a comment to this, I found the red "stop-sign" and red number zero shown when there are zero errors distracting. If there are zero errors, is is unnecessary to show something in red: it just takes my attention to that area of the screen.

I believe if there are zero errors, no error sign should be shown. The same if there are zero warnings: no warning sign should be shown.

**Comment by chatox** [comment]
Compare how linter shows there are zero errors (left) to how latex shows there are zero errors (right):
![image](https://user-images.githubusercontent.com/1716961/47005319-c9901380-d133-11e8-8bab-4530f96829ea.png)

**Comment by thomasjo** [comment]
@chatox Agreed. Current design is too distracting. I'm hoping to find some time soon to resolve a few outstanding bugs and much needed enhancements. One of the things I plan on doing is dropping the custom log panel and relying on the diagnostics functionality in Atom IDE instead. Less code to maintain, and a more unified user experience.

**Comment by cbrnr** [comment]
Closing since Atom is dead.
