### ISSUE TITLE
DiCy fails to perform "clean" command 

### ISSUE THREAD

**Issue by evfro** [thomasjo/atom-latex#450]
Hi,

I just got a fresh Windows 10 system and installed the latest versions of atom, atom-latex and MikTex.
It seems that DiCy is unable to properly perform `clean` and `sync` commands. For example, hitting `ctrl-alt-c` after a project is built doesn't remove any files (i.e. fls, log, synctex.gz, aux) from the repository. I can reproduce it even on a very simple tex project.

Not sure if this is related, but I also noticed, that build process does not finish if SumatraPDF is used for viewing pdf. Even though the pdf is generated, the Latex processing icon in the bottom pane keeps spinning (until I close SumatraPDF). This doesn't happen with the pdf-view though.

**Comment by yitzchak** [comment]
Thanks for reporting the issues!

The DiCy issues should be resolved by #441 once it is merged. I'll look into the SumatraPDF issue shortly.

**Comment by Evfro** [comment]
Hi! Are there any updates on the issue?
