### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by unitrixx** [thomasjo/atom-latex#451]
Hey,
I have a problem with building from within Atom.
I installed the latest version of TeXLive 2017 which basically works. I compiled a file from the command line and it worked. So I guess that the package just has a problem to find the latexmk.exe . 
When trying to build from within Atom I get the following error:
_TeXification failed with Status Code 1 and Output of "Der Befehl "latexmk" ist entweder falsch geschrieben oder konnte nicht gefunden werden."_
Literally translated that means the command  _"latexmk"_ is either written wrong or could not be found.
The other error logs I get are:
_I can't write on file 'file name.pdf'
Emergency stop
==> Fatal error occured, no output PDF file produced!_

When trying the runtime check I get the errors:
_Rscript check failed with code 1 and response of "Der Befehl "Rscript" ist entweder falsch geschrieben oder konnte nicht gefunden werden."_
It means the same like above. The command is either written wrong or could not be found. For _latexmk_ I get the same error Code and the same response just with switched command names.

I hope there is a way you can help me.

**Comment by unitrixx** [comment]
I forgot to mention I work on Windows 10

**Comment by unitrixx** [comment]
I fixed the problem with not finding <latexmk> but when trying the runtime check I get the same errror for Rscript. 
Also when trying to build the log says:
_I can't write on file 'file Name.pdf'
Emergency stop
==> Fatal error occured, no Output PDF file produced!_

**Comment by EbrahimKaram** [comment]
Hello, 

I'm currently runnning  Tex Live 2018 and on windows 10. 
I installed latexmk using 
`tlmgr install latexmk`

Now in Atom in Runtime I get the following error
![image](https://user-images.githubusercontent.com/10140799/47257440-77822180-d496-11e8-8832-8aa7c8b74520.png)

When I try to Build a document I get the following
![image](https://user-images.githubusercontent.com/10140799/47257449-95e81d00-d496-11e8-943e-981809e0ff19.png)


Please note when I run `latexmk -v`
I get the following 

> Latexmk, John Collins, 7 August 2018. Version 4.59

I guess the library might have changed recently but I'm not sure
