### ISSUE TITLE
Can't use Evince to open PDF

### ISSUE THREAD

**Issue by dinozof** [thomasjo/atom-latex#453]
Hi,

i've changed the setting of Ato-latex to use Evince but every time i compile it, it always says "Using viewer default" and tries to use okular  . I'm sure Evince is found because running latex:check runtime says that evince was found as capable PDF opener.

thanks!

**Comment by rhoeden** [comment]
I'm having this issue as well. I've set "Opener - zathura" in the settings yet it always tries to open with okular.
