### ISSUE TITLE
Request: Perform simple/quick build on save.

### ISSUE THREAD

**Issue by RlndVt** [thomasjo/atom-latex#454]
Currently when using the 'build on save' option is used the complete build sequence is used. However these are usually small changes not requiring a complete rebuild. 

I suggest only issuing a 'pdflatex' (or comparable) command at these 'build on save' intervals. Allowing the user to issue a complete build only when necessary.

**Comment by Evpok** [comment]
What do you mean “a full rebuild”? Latexmk and DiCy only run what has to be run according to your changes, so if those changes really only need a single `pdflatex` run, that's all that will be done.

**Comment by RlndVt** [comment]
I had done some research after commenting and came to the same conclusion, must be something on my end. My bad.
