### ISSUE TITLE
duplicate environnement 

### ISSUE THREAD

**Issue by Goysa2** [thomasjo/atom-latex#455]
I have a problem when I do latex on atom.
When I create an environnement, it automatically duplicates the environnement and I I have twice the environnement. 
I am not sure if it makes sense so I attached a picture, in that case I on did one begin itemize bu it created two..
![photo-git](https://user-images.githubusercontent.com/22686485/36330736-e6f1976e-1338-11e8-96ec-83f97eeae07a.png)

Is it a bug? a feature? or just me who's doing something particular without knowing it?
thanks for your help!

**Comment by thomasjo** [comment]
Hi,

This package has nothing to do with snippets, autocomplete functionality or similar.

Check which language package you are using for LaTeX support (e.g. language-latex), and open an issue on the respective package's GitHub repo.
