### ISSUE TITLE
\emph wrong highlighting

### ISSUE THREAD

**Issue by zicvic** [thomasjo/atom-latex#458]
Not sure what is the cause of this but maybe someone here can help?  When I use \emph the highlighting get wrong and I can't find a solution to fix this. 

![screenshot 2018-03-11 12 31 55](https://user-images.githubusercontent.com/7301918/37252813-5e973dc2-2528-11e8-9a24-4b94e1685dda.png)

**Comment by thomasjo** [comment]
This package has nothing to do with syntax highlighting, snippet autocompletion, and similar. Check which language packages you've installed that provides LaTeX highlighting, and open an issue there.
