### ISSUE TITLE
Uncaught TypeError: old path must be a string

### ISSUE THREAD

**Issue by nscaife** [thomasjo/atom-latex#46]
If log file exists but does not contain the string "Output written on <filename>" (for example, if a previous compile failed), LogParser->parse returns *null*, which gets appended to the project directory.  

For example:

**c:\project** becomes **c:\project\null**, which does not exist, causing an exception during the file move.

**Atom Version**: 0.174.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [latex](https://github.com/thomasjo/atom-latex) package, v0.15.2

### Stack Trace

Uncaught TypeError: old path must be a string

```
At fs.js:580

TypeError: old path must be a string
  at TypeError (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (c:\Users\Nolen\AppData\Local\atom\app-0.174.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:221:17)
  at Object.module.exports.moveResult (c:\Users\Nolen\.atom\packages\latex\lib\latex.coffee:96:8)
  at c:\Users\Nolen\.atom\packages\latex\lib\latex.coffee:39:12
  at c:\Users\Nolen\.atom\packages\latex\lib\builders\latexmk.coffee:19:9
  at ChildProcess.exithandler (child_process.js:736:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1081:5)

```

### Commands

```
 19x -1:43.9 core:page-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:36.7 editor:select-to-first-character-of-line (atom-text-editor.editor)
  2x -1:36.5 core:delete (atom-text-editor.editor)
     -1:35.3 core:save (atom-text-editor.editor)
     -1:32.1 latex:build (atom-text-editor.editor.is-focused)
     -0:32.1 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:24.4 editor:move-to-end-of-screen-line (atom-text-editor.editor)
 22x -0:24.0 core:page-down (atom-text-editor.editor)
  6x -0:22.1 core:move-up (atom-text-editor.editor)
     -0:02.4 core:move-down (atom-text-editor.editor)
     -0:02.0 editor:select-to-first-character-of-line (atom-text-editor.editor)
  2x -0:01.8 core:delete (atom-text-editor.editor)
  2x -0:00.0 latex:build (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
column-select, v0.1.0
hex, v0.3.10
language-latex, v0.4.1
latex, v0.15.2
monokai, v0.10.0
wordcount, v0.13.1

# Dev
latex, v0.15.2
```

/cc @atom/core

**Comment by thomasjo** [comment]
Excellent debugging. Going to attempt to find a reliable way to reproduce this, then fix accordingly.

**Comment by thomasjo** [comment]
@nscaife any chance you can test the newest version, and verify if the problem is resolved or not? I was only able to reliable reproduce this with a regression test, but my assumptions when writing the test might have been incorrect.

**Comment by nscaife** [comment]
I was able to reproduce the issue by successfully compiling a file, then editing the log and removing only the line "Output written on...".  When compiling again, the log isn't rewritten (presumably because the PDF doesn't need to change) but the log parsing would fail.

Looks like it is no longer throwing an exception! I get "LaTeX compilation error" on the status bar and the following message in the console: "TeXification failed with status code 0!"  This seems to fix my issue, at least! Thanks!
