### ISSUE TITLE
How to auto-complete on \cite, \includegraphics, etc

### ISSUE THREAD

**Issue by qazip** [thomasjo/atom-latex#460]
Hello,

Does this package support completion in the \ref{} \cite{} and \includegraphics{} commands? Basically, in includegraphics I want file completion, in cite I want bibtex completion and in ref I want label completion.

LatexTools does all this in sublime-text.

**Comment by yitzchak** [comment]
This does compilation only. See #361 for a list of packages that perform such functions.
