### ISSUE TITLE
How to use for modular projects

### ISSUE THREAD

**Issue by AntoinePrv** [thomasjo/atom-latex#466]
Hello,

Thank you for this great package! I am making a modular Latex project with the structure:
```
/main.tex
/mystyle.sty
/tex
  └  chapter1.tex
  └  chapter2.tex
/img
  └  myimage.png
```

Chapters and the `main.tex` are linked using the `subfiles` Latex package that let me compile chapters one at a time.

Now when I build `chapter1.tex` from within Atom, this doesn't work because the build is done from within the `tex` folder (or so it seems). All the path linking to images or `\usepackage{mystyle}` fail, even if they are used in the `main.tex`.

Using a terminal, the compilation works fine if I compile from the root folder (e.g. `pdflatex tex/chapter1.tex`). Hence:
_How can I define the "execution folder" to be the root folder of the project opened in Atom?_

I tried to play with the `% !TEX` magic but couldn't figure it out.

Thanks for the help.

**Comment by thomasjo** [comment]
@AntoinePrv Sorry about not responding to this earlier. Unless you've already figured it out, you should be able to accomplish what you desire by adding the following to the top of `chapterX.tex` files
``` latex
% !TEX root = ../main.tex
```
