### ISSUE TITLE
DiCy builder didn't work

### ISSUE THREAD

**Issue by m0nhawk** [thomasjo/atom-latex#467]
I get the following error on any file:

```
[CheckForMissingBuildRule(build;finalize;;ysc.tex)] No applicable build rule was found for main source file `presentation.tex`.
```

Example of file:

```
\documentclass{beamer}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

\begin{document}
\end{document}
```

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

I am not able to reproduce with the example that you have given. It looks like DiCy thinks that `presentation.tex` is a main source file. How is that file being included?

**Comment by yitzchak** [comment]
The build rule is referring to `ysc.tex`. Was main source file renamed?

**Comment by m0nhawk** [comment]
Yes, I was renaming the main (and only) source file.

Though, I still have the same error:

![error](https://user-images.githubusercontent.com/8220926/39365899-21f04bec-4a3b-11e8-9347-a185648afd5a.png)

**Comment by yitzchak** [comment]
Try deleting any cache files `*-cache.yaml` and then restart Atom.

**Comment by m0nhawk** [comment]
I narrowed it down to the following:

1. Built some document.
2. Rename current or create a new document in the **same** folder.
3. It won't build anymore, until you remove `*-cache.yaml` and restart Atom.

**Comment by m0nhawk** [comment]
Is there any fix for this?

Removing cache files and restarting Atom every time I need to built the file is unbearable...

**Comment by yitzchak** [comment]
Is it happening other than when you rename the main source file? You can also try doing a "Rebuild".

**Comment by Evpok** [comment]
I am experiencing the same issue, though in my case, the rename happened before I even built it.

**Comment by Exr0n** [comment]
It's been a while since anything happened here, and I am having the same problem. Are there any known fixes or workarounds?

MacOS 10.15.1
Atom 1.41.0 x64
> Electron 4.2.7
> Chrome 69.0.3497.128
> Node v10.11.0
LaTeX 0.50.2

File `final.tex`:
```LaTeX
\begin{document}
x
\end{document}
```

**Comment by scmartin** [comment]
Seeing a similar issue.

Windows 10.1903
Atom 1.45.0 x64

**Comment by MPenaR** [comment]
Not sure how is it working, I was having the same issue, my solution was to go to preferences, 
uncheck `use DiCy`, try to compile it (it won't work with latexmk), check `use DiCy` again and problem solved.
