### ISSUE TITLE
latexmk: Bad command line arguments.

### ISSUE THREAD

**Issue by lyx314** [thomasjo/atom-latex#469]
The Log says,
latexmk: Bad command line arguments.
Parsing of log files failed.

I don't know what's going on here.
Files can still be compiled successfully outside Atom.

- Dell xps 13; Windows 10, 1803;
- LaTeX distribution: TeX Live 2018;
- Atom 1.26.1 with latex 0.50.0
- Latexmk, John Collins, 17 Jan. 2018. Version 4.55;

**Comment by RanSaSK** [comment]
I have the same problem!
