### ISSUE TITLE
Multiple Build Processes

### ISSUE THREAD

**Issue by sbigalke** [thomasjo/atom-latex#471]
Hi, and thank your for this awesome project,

when I hit build while it is already building, I get the following errors and my log is mixed up:
![image](https://user-images.githubusercontent.com/7767091/40058045-3f66cfb6-5850-11e8-8f47-2d8d493ef7e5.png)

If you have a large project with compile times of some seconds or minutes then this happens to me all the time.
Wouldn't be a guard for this a good idea?
Meaning that if a build process is already running, any new build processes will be ignored until the running process is done?!

Doesn't this happen to you also very often?!
In my case, a guard would be a great enhancement for preventing multiple build processes.

**Comment by SolidTux** [comment]
This also happens to me everytime I save before the last build process is finished (I have build on save activated).

**Comment by DavidS3141** [comment]
I use also the auto-build on save option resulting in the build clashes. A guard would be great. Sadly I am not very familiar with developing atom packages. If this seems to you like a less-than-an-hour project and you could point me in the right direction in your code, I would happily give it a try though.

Thanks a lot for your great work, everything else works like a charm.
