### ISSUE TITLE
Cannot clean subdirectory

### ISSUE THREAD

**Issue by PierreMarchand20** [thomasjo/atom-latex#472]
I tried to configure the clean patterns adding `**/*.xdv, **/*.dep, **/*.dpth, **/*.md5, **/*.makefile, **/*.figlist, **/*.fls` to delete temporary files due to tikz externalization. But it does not work, and I do not understand why since it is the same pattern as `.aux` files. 

You can find an example here: https://github.com/PierreMarchand20/atom-latex-test

**Comment by PierreMarchand20** [comment]
As far as I know, there is still an issue

**Comment by lsfinn** [comment]
???
