### ISSUE TITLE
Crash of atom-latex in specific folder

### ISSUE THREAD

**Issue by mic-rigaud** [thomasjo/atom-latex#473]
Hello, 

I find this bug when I try to modify a file Latex. This bug crash atom every time.
I have this problem only on a specific project.
On this project I have on a folder an application in node/meteorjs and on the other folder the documentation in latex. When I try to build the beamer.tex file I got the bug and that crash atom.
However if I define the folder "doc" as root project folder I have no problem. 

Thank you,

![project](https://user-images.githubusercontent.com/19793123/41613776-db473094-73f6-11e8-84d8-9fec9d370793.png)
![atom-latex](https://user-images.githubusercontent.com/19793123/41613782-de3b1860-73f6-11e8-8aee-98b029550889.png)

----------

Steps to reproduce:

1. add "/" or try to build a latex project

You can read following information.

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Linux Mint
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.4

### Stack Trace

Uncaught Error: watch /home/michael/Documents/Programation/Blueberry/doc/Presentation/Biblio.bib ENOSPC

```
At events.js:163

Error: watch /home/michael/Documents/Programation/Blueberry/doc/Presentation/Biblio.bib ENOSPC
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at createFsWatchInstance (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
just type "\"
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-bootstrap4 1.4.0 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.12.0 
atom-latex 0.8.4 
autocomplete-paths 2.12.2 
emmet 2.4.3 
file-header 1.13.9 
file-icons 2.1.21 
highlight-selected 0.13.1 
ide-python 0.10.0 
language-latex 1.1.1 
meteor-api 2.20.0 
meteor-helper 0.29.0 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
project-manager 3.3.6 
tag 0.5.0 
todo-show 2.3.0 
```

**Comment by thomasjo** [comment]
Wrong repository; this repository belongs to the first LaTeX package for Atom, which is simply called `latex`. You'll want to re-open this issue over at https://github.com/James-Yu/Atom-LaTeX.

**Comment by mic-rigaud** [comment]
Ok sorry.
