### ISSUE TITLE
A problem of the compile speed

### ISSUE THREAD

**Issue by RogerDTZ** [thomasjo/atom-latex#477]
When I use this package to compile a Tex code into a PDF file, generally in the first few times the compile progress is really fast. 
But after a moment, or there are some mistake about page overflow, the compile progress would be really slow, and usually causes no responding of atom. 
By contrast with CMD command compiling, these pages problem will not slow down the speed, at least it will not cause no responding.
How can I solve this problem? Because I am more willing to use this tool to compile rather than CMD.

**Comment by thomasjo** [comment]
@RogerDTZ Would you be able to share a small file/project that reproduces the problem? Also if you could provide some more details on how to reproduce the problem in a step-by-step list, that would be very useful. Finally, it would be really great if you could share some details on your computer, such as hardware summary (CPU, RAM, etc), your operating system, and so on. Thanks!
