### ISSUE TITLE
"LaTeX file root not set." and no LaTeX Log

### ISSUE THREAD

**Issue by wwpokenet** [thomasjo/atom-latex#479]
<img width="1367" alt="2018-08-05 11 13 05" src="https://user-images.githubusercontent.com/26547409/43682217-8d7576ea-98a0-11e8-9c4f-4b5c80620ba2.png">
What's wrong with this? Errors occured but no log output? 
BTW, what is the meaning of "LaTeX file root not set?"

**Comment by thomasjo** [comment]
@wwpokenet Would it be possible for you to share a small example file/project that reproduces the problem? That would be extremely helpful in resolving the problem. Thanks!

**Comment by wwpokenet** [comment]
Oh, this time when I create a new file everything looks good😀. Sorry for the interruption.
