### ISSUE TITLE
latexmk: Bad command line arguments. Parsing of log files failed.

### ISSUE THREAD

**Issue by RanSaSK** [thomasjo/atom-latex#486]
When I try to compile my first tex file, the error message says:
latexmk:Bad command line arguments.
Parsing of log files failed.

My environment is:
* Windows 10.0.17134.228
* Atom 1.30.0 x64
* TeX Live 2018
* Latexmk, John Collins, 17 Jan. 2018. Version 4.55
* atom-latex 0.50.0
* atom-language-latex 1.2.0

When I run `Check Runtime`, the messages are like these:
```
Rscript check failed with code 1 and response of " 'Rscript'( here are some garbage characters) ".
```

Also, I can run latexmk to compile tex and show me pdf files. 

So could you tell me what should I do?

**Comment by lyx314** [comment]
You can check if there are unrecognizable characters in your file's path.
I had the same problem from Chinese characters in my file's name.

**Comment by RanSaSK** [comment]
>           You can check if there are unrecognizable characters in your file's path.
> I had the same problem from Chinese characters in my file's name.

Thank you! Problem solved!
