### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by acamara1498** [thomasjo/atom-latex#490]
<img width="1133" alt="screen shot 2018-10-08 at 2 58 25 pm" src="https://user-images.githubusercontent.com/29179201/46628165-b0bba880-cb0a-11e8-8db2-ca8400c00b09.png">

Not sure what this error means, but it won't let me build my .tex files.

**Comment by Aerijo** [comment]
@acamara1498 Is this a recent issue after a time when it once worked, or have you never used this package before?

Also, does the `latexmk` command work in the terminal? You need it installed for this package to work (it comes as part of a full TeX-Live distribution, so you'd have to work out how to get it if you didn't install full TeX-Live).
