### ISSUE TITLE
Build from non-root file

### ISSUE THREAD

**Issue by ChristofV** [thomasjo/atom-latex#497]
I have a project in which my root file contains several imports (\input{certainfile.tex}. I am able to compile (using ctrl-alt-b) my project from my root file perfectly. The content of certainfile.tex is processed in a correct way. However, if I am working in this subfile and I compile, the compilation fails. I need to switch to the root file every time and compile the project there. Is there a way to overcome this problem?

**Comment by thomasjo** [comment]
Yes, this is supported with the magic comment feature, specifically `% TEX root = your-main-file.tex`

Ref: https://github.com/thomasjo/atom-latex/wiki/Overridding-Build-Settings

**Comment by falcondai** [comment]
Thanks for the awesome package. I wonder if we can specify `root` in a known config file (maybe named `_latex.yaml`) instead of prepending the magic comment in _every_ tex file (nice to see an updated preview as I save the current fragment)? Or is it a conscious design decision you made?
