### ISSUE TITLE
Using relative Tex path

### ISSUE THREAD

**Issue by blubbsy** [thomasjo/atom-latex#498]
Hi,

i'm trying to establish atom as my new standard tool in my portable apps (for windows) suit and i'm having trouble to use latex with relativ paths to my texlive/miktex installation. with absolute paths i'm not having any trouble, but with relative paths (.../.../.../miktex/miktex/bin etc.) it never can find the binaries. With absolute paths, there is no prolem, but with relative paths it is not working. Do i have an error or is it the package?

Path: Atom ---> C:\Apps\PortableApps\Atom
Path .atom --> C:\Apps\PortableApps\.atom
Path miktex binary  --> C:\Apps\PortableApps\miktex\miktex\bin
Relative path i want to use ---> ..\..\..\miktex\miktex\bin (3x because if iam not wrong your package will see .atom/packages/latex, so to get out of .atom i have to go back 3x)

BR and thanks,
Blubbsy

**Comment by petKitsune** [comment]
relative path never worked for me on this package
i think it's 'The Full Path to... bla bla' 
but you can put a PATH environment variable in the launcher.ini \Atom\apps\AppInfo\Launcher\
if that makes life easier

something like
[Environment]
TEX=%PAL:PortableAppsDir%\miktex\miktex\bin

i never used this
the launcher.ini manage the path in my config.cson

**Comment by petKitsune** [comment]
I don't know where to put this, so
Thx for adding relative path and all the fish 
great work

**Comment by blubbsy** [comment]
@petKitsune i think you should say thank you to PortableApps.com for this solution ;)

Actually your solution would work for portableapps, which is great. have to try it when i have time :)
