### ISSUE TITLE
Evince opener reports an error

### ISSUE THREAD

**Issue by sergejx** [thomasjo/atom-latex#503]
Evince opener reports an error in the LaTeX Log window: "An error occured while trying to run Evince opener". Evince is launched correctly, but SyncTeX does not work.

I have tried to debug the problem and found that it is caused by `this.getInterface()` call at line 71 in `evince-opener.js`, which throws exception "No such interface found". Because of the exception, rest of the method `getWindow()` is not executed which breaks SyncTeX support.

https://github.com/thomasjo/atom-latex/blob/a94ed9742796234a487e1cb0c8caa5af7fbf4131/lib/openers/evince-opener.js#L71

At this point I have stopped because I don't understand interaction with DBus that this method implements. As a workaround, I have commented out the call.

I'm using Atom 1.33 on Fedora 29 with Gnome 3.30.2.

**Comment by yitzchak** [comment]
This is probably due to a change in the application object path in newer versions of Evince. Old versions call have it as `/org/gtk/Application/anonymous` while new versions have it as `/org/gnome/Evince`.

**Comment by rzeidler** [comment]
Same problem here on Fedora 29. Changing the fdApplicationObject constant as suggested by @yitzchak seems to fix it for me.
https://github.com/rzeidler/atom-latex/commit/8e24ec9800baa99213c6f4ae359552fc4a428b1d

But presumably this would break earlier versions of Gnome.

**Comment by sergejx** [comment]
I can also confirm that replacing value of `fdApplicationObject` as suggested by @yitzchak removes the error message and fixes sync functionality.

It seems, however, that disabling "Open Result in Background" option in settings has no effect now — Evince window takes focus only when first launched and then it remains in background when document  is updated or "Latex: Sync" command is called. So the code for activating the window is probably useless now.

**Comment by khoek** [comment]
I have this problem, too

**Comment by khoek** [comment]
Bump

**Comment by khoek** [comment]
Can reproduce on a plain ubuntu 19.04 installation with `texlive-full` installed.

**Comment by flg** [comment]
Problem is stil here

**Comment by ekce** [comment]
The fix above worked for me. This should probably be updated since it's 2020 now.

**Comment by Doekeb** [comment]
I am using Manjaro Gnome where the default path for Evince is `/usr/bin/evince`. Can I suggest adding an option similar to those in the attached screenshot for the system's Evince path and using this as the value of `fdApplicationObject`?
![image](https://user-images.githubusercontent.com/13689478/117186763-2b273480-ada9-11eb-85bf-a5c0048f9293.png)
