### ISSUE TITLE
Magic Comment stopped working

### ISSUE THREAD

**Issue by Axelfowlie** [thomasjo/atom-latex#505]
I'm currently working with version 0.50.2
Haven't used the package in a while so not sure when the issue appeared.
It used to work on my old machine, but I've got a new laptop since. It's the first time trying the latex package on the new machine.

Magic Comment stopped working for me and I have no idea where to start to look.

I'm simply using % !TEX root = root.tex at the beginning of the file, first line as well.

I can't build from that file, I still have to switch to the root file to compile my tex file successfully.

Any idea what I should look at?

Best regards

**Comment by cmburg** [comment]
Wich OS are you using? I am using Linux and for me the following works:
`% !TEX root = ./root.tex`
The dot indicates the current working directory assuming both files are in it. Otherwise try 
`% !TEX root = ../root.tex` if the nonroot-file is in a subfolder.

**Comment by Axelfowlie** [comment]
I'm using Windows 10 Version 1803 and Strawberry Perl 5, version 28.

I tried the following:
% !TEX root = root.tex
% !TEX root = ./root.tex
% !TEX root = .\root.tex
% !TEX root = C:\absolutePath/root.tex

IIRC I never tried it out on Windows before. My old OS was macOS.

**Comment by Aerijo** [comment]
@cmburg Magic comments are done at the editor level (this package), so it shouldn’t be a setup issue.
