### ISSUE TITLE
Request feature: live preview

### ISSUE THREAD

**Issue by fabiom91** [thomasjo/atom-latex#509]
Hi, I was wondering if it would be possible to implement a live preview of the latex document instead of having to build the document every time. (like what Atom already does with markdown documents).

**Comment by Aerijo** [comment]
@fabiom91 You'd first have to find a Latex engine that supports incremental builds. I know there are some proprietary editors that offer this, like [BaKoMa Text](http://www.bakoma-tex.com/), but their engine is not open source.

Without incremental builds, you would just have to build the whole thing each time. This may be quick for something like a resume, but anything where the build time is non-negligible would just be painfully slow.

And in general, Latex is much harder to parse incrementally than markdown, so I don't expect any inspiration from there.
