### ISSUE TITLE
"Overridding Build Settings" not work

### ISSUE THREAD

**Issue by TimHe95** [thomasjo/atom-latex#515]
### ENV:
```
MacOS 10.14 (18A391)
Atom 1.36.0
atom-latex 0.50.2
```
### Other packages:
`ls /Users/hhc/.atom/packages`
results:
```
autocomplete-python		minimap-highlight-selected
atom-clock			docblockr			pdf-view
atom-language-matlab		file-icons			python-tools
atom-latex			highlight-selected		simplified-chinese-menu
autocomplete-modules		language-latex
autocomplete-paths		minimap
```
### My `main.tex`:
```
% !TEX openResultAfterBuild = false
% !TEX buildOnSave = true

\documentclass[sigconf]{acmart}

\begin{document}
\begin{table}[]
\begin{tabular}{l|llll}
\textbf{}            & \textbf{rep. suc.} & \textbf{perf. down} & \textbf{perf. up} & \textbf{} \\ \hline
1      &                   &                     &                   &           \\
2 &                    &                     &                   &           \\
3 &                    &                     &                   &
\end{tabular}
\end{table}
\end{document}
```
I also add a `yaml` file like in the same directory with `main.tex`:
```
openResultAfterBuild: false
buildOnSave: true
```

### PROBLEM:
**BUT atom still open `Skim` and do not build when I `Ctr+s`**

Thank you for help!

**Comment by thomasjo** [comment]
@TimHe95 Looks like you want to report this error on the [Atom-LaTeX repo](https://github.com/James-Yu/Atom-LaTeX). The repo you opened this issue in is for the [latex package](https://atom.io/packages/latex). Sorry about the naming confusion!

**Comment by thomasjo** [comment]
Wait, I just noticed your other issue and realize you have opened the issue on the correct repository. But since you haven't installed the package properly yet, I'll leave the issue closed since the problem will in all likelihood be resolved when you resolve the installation issue.
