### ISSUE TITLE
Cannot change from latexmk to pdflatex

### ISSUE THREAD

**Issue by miguelarman** [thomasjo/atom-latex#521]
I installed the package earlier today

Still cannot figure out how to compile on my machine (Windows 10 with MikTex and previously pdflatex set up and functionall).

Whenever I try to compile a simple .tex file, it gives two errors:
![program](https://user-images.githubusercontent.com/22821797/57728952-4e74e880-7695-11e9-8d91-a1ee64b5d9bf.png)

![error](https://user-images.githubusercontent.com/22821797/57728935-4157f980-7695-11e9-8796-2fab4d6ad389.png)

My configuration of atom-latex is the following:

![config](https://user-images.githubusercontent.com/22821797/57729025-7ebc8700-7695-11e9-89de-3e17616f8d37.png)

I cannot find a way to select pdflatex as my compiler, because it still tries to compile with latexmk, no matter what I try.

Thanks in advance for your help

**Comment by miguelarman** [comment]
I reinstalled completelly MikTex, and install latexmk and Strawberry Perl. Still same errors, but I can invoque latexmk from the terminal

**Comment by Alex-Linhares** [comment]
This seems relayed to #527
