### ISSUE TITLE
some updates to cleanPatterns fail

### ISSUE THREAD

**Issue by lsfinn** [thomasjo/atom-latex#525]
some updates to cleanPatterns fail. 

I have updated cleanPatterns with the additional pattern "**/*.xmp"; however, clean fails to remove these files. Other updates  (e.g., "**/*.bak0") are cleaned. The order of appearance of the patterns (e.g., before or after, first or last) does not seem to matter.

**Comment by mskoenz** [comment]
I encountered this as well, but after a clean (in my build folder), new build and following clean it worked. I guess it checks if some common file to clean exists as trigger to run all remove comands, and if it is already gone, no cleaning done. But of course I might be wrong on this.

Dont forget the "," between like I did first ^^
