### ISSUE TITLE
atom-latex cannot find latexmk

### ISSUE THREAD

**Issue by AndrSalvi** [thomasjo/atom-latex#527]
Hi! Thanks for your amazing work! I recently switched from Windows to Pop OS and I wished I could continue to use your package. I installed tex-live-full via terminal, atom and the required packages but when I try to build something (in this case a simple "Hello World file) I get the following:

![Screenshot from 2019-10-03 23-57-15](https://user-images.githubusercontent.com/18744288/66169821-ab1f7280-e639-11e9-97a3-211a2b5539e2.png)

I ran `which latexmk` and found out that my TeX installation is in /usr/bin/. I set that on Atom (using the ui) but still no luck. I always get the same error. I tried to run pdflatex from the terminal to build the same tex file and it works. What can I do? I read the I could manually edit the config file but I don't really know what to do once I open it!

Many thanks,
A

**Comment by Alex-Linhares** [comment]
I have this same issue.  After upgrading Linux Mint 20, Atom-Latex broke, unable to find latexmk.  I reinstalled Atom; Reinstalled texlive, and I get the same error.
