### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by alex-bellon** [thomasjo/atom-latex#538]
I'm using the `latex` package in Atom on Manjaro GNOME, and whenever I save a `.tex` file or try to use the Build option from the package menu, nothing happens. I have also tried to Clean and Rebuild, Show Log, etc. and nothing happens/pops up. I've tried compiling my document on the command line and it works fine, so I think the issue is with the plugin.

I've also tried reinstalling the plugin, reinstalling all of my plugins, and completely reinstalling Atom (after manually deleting the package files) to no avail. 

I have this package working on my laptop with all of the same package settings (also running Manjaro) and everything works fine, so I'm not sure what is causing this issue.

**Comment by xliang10** [comment]
Same problem (maybe). In my case, the Build option works sometimes but sometimes not. It produces no errors but just doesn't update the pdf. Clean and Rebuild are tried, nothing changes. It works normally each time I close and reopen Atom, and cannot update the pdf after several times of Build.

**Comment by alex-bellon** [comment]
I actually tried it on my laptop after filing this bug and found it does not work there anymore either. Here are the versions I'm running on both machines:
- atom-latex: `0.50.2` (both)
- Atom: `1.47.0` and `1.50.0`

**Comment by vivi90** [comment]
Same here :-(

## Package
```
0.50.2
```

### Atom
```
Atom    : 1.55.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```

### OS
```
Description:	Manjaro Linux
Release:	21.0
Codename:	Ornara
```

### Kernel
```
Linux 5.11.6-1-MANJARO #1 SMP PREEMPT Thu Mar 11 19:05:51 UTC 2021 x86_64 GNU/Linux
```
