### ISSUE TITLE
Using .latexmkrc files for build

### ISSUE THREAD

**Issue by charlesbaynham** [thomasjo/atom-latex#539]
A good pattern with making a reproducable latex build is to store all your configuration in a `.latexmkrc` file, so that users can reproduce your build exactly by just running `latexmk` without any additional command line options. However atom-latex doesn't seem to notice `latexmkrc` files in the project directory. 

Is there a way to do this? Simply calling `latexmk` in the project directory would suffice.

**Comment by thomasjo** [comment]
First of all, just double checking that you're using the `latex` package and not `atom-latex`. I realize the name of this repo might be confusing given that it belongs to the Atom package named [`latex`](https://atom.io/packages/latex) despite the name.

If you're using the `latex`, then what you're proposing should work. At least it used to work. Latexmk is indeed invoked with the working directory set to the project folder of the file being built.
