### ISSUE TITLE
Error Occurred While Building LaTeX - latexmk not working

### ISSUE THREAD

**Issue by TheOfficialDarthVader** [thomasjo/atom-latex#540]
**What I've done:**

- Installed `atom-latex`
- Installed ActiveState Perl
- Installed `latexmk` using the MikTex Console
- Set the Windows System Environment variables for Perl and MikTex:
    - For Perl: `C:\Perl64\bin`
    - For MikTex: `C:\Program Files\MiKTeX 2.9\miktex\bin` and `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\`

I can confirm that Perl works as I am able to run both it and the `latexmk` script from Command Prompt. I can also use `latexmk` from TexStudio, but this required setting `Commands ($PATH)` to `C:\Perl64\bin`. I can run `pdflatex` as the build engine in `atom-latex`. It is just `latexmk` that is not working.

Given what I had to do to get Perl scripts to work with TexStudio this would seem to suggest the Environment Variables being passed are in some way incorrect. I am aware there is a work around on [Using latexmk with MiKTeX][1]. However, I can't find the Tex Path option in the `atom-latex` settings.

The build log is just a single line:
`> latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf  "Cover Letter"`

So I'm not sure where it is getting hung up, I assume it is an issue with not finding Perl.

[1]: https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-with-MiKTeX

**Comment by thomasjo** [comment]
Did you install `atom-latex` or `latex`? This repo is for the latter — https://atom.io/packages/latex

**Comment by TheOfficialDarthVader** [comment]
I have installed `atom-latex 0.9.1`

**Comment by thomasjo** [comment]
OK, then you need to open this issue on the correct repository: https://github.com/ashthespy/Atom-LaTeX
