### ISSUE TITLE
pdflatex####.fls files remaining after clean

### ISSUE THREAD

**Issue by ajsenko5** [thomasjo/atom-latex#555]
If I try to compile my {filename}.tex document and theres an error, some files with the name 'pdflatex(somenumbers).fls' is generated, and does not go away with a clean. I can't figure out how to add that to the clean patterns (I tried *.fls and that didn't work)

**Comment by KazuhiroHirao** [comment]
In my situation, {name}.fdb_latexmk, {name}.fls, and {name}.synctex.gz remain after a clean. I checked the Clean patterns and found **/*.fls etc. in the line.

**Comment by ajsenko5** [comment]
Yeah I'm gonna be honest, it's not very reproduceable. I changed some settings (mainly having it show everything, not just errors and warnings) and it mostly went away

**Comment by KazuhiroHirao** [comment]
@ajsenko5 It sounds interesting and hopeful. I will continue to use as it is.

**Comment by KazuhiroHirao** [comment]
Now I am using package:latextools to delete contemporary files. It looks overkill, but latextools works well.
