### ISSUE TITLE
Insert `` and '' instead of quotation marks

### ISSUE THREAD

**Issue by bisraelsen** [thomasjo/atom-latex#57]
By default using the quotation mark key will produce a double right quotation mark. This is great except when you want a double left quotation mark.

It would be good to replace the use of quotation mark key with `` or '' depending on which side of a character the cursor is currently on.

**Comment by AlexanderWillner** [comment]
+1 since chktex is often highlighting exactly this issue.

**Comment by iagoba** [comment]
I would take care. I've seen in other editors problems to write \" in order to write something like ö, ü and so on. http://forum.latexing.com/viewtopic.php?f=2&t=105 to cite the one that causes problems to me

**Comment by yitzchak** [comment]
At the moment we are keeping `latex` focused on the building/processing of LaTeX documents. This is more of an editing issue and probably belongs in a package like [latex-autocomplete](https://atom.io/packages/latex-autocomplete) or [latexer](https://atom.io/packages/latexer) if it is not already there.
