### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by dpo** [thomasjo/atom-latex#6]
This is more of a wish list rather than an issue. I wrote a minimalistic LaTeX plugin for SublimeTexT called [MiniLaTeX](https://github.com/dpo/sublime-minilatex) that I think does a few things right. Requiring that all LaTeX documents be Sublime "projects" made multi-file documents processing a breeze. Atom might have a similar concept.

Also I recently happened upon [PDFview](https://atom.io/packages/pdf-view) and it would be great to be able to preview PDF of LaTeX documents directly in Atom, without relying on users having this or that previewer. Also I presume forward and reverse sync could be implemented for PDFview?!

Cheers!

**Comment by nscaife** [comment]
FWIW, basic Atom-based PDF viewing was added in a commit a couple of months ago.  It uses the pdf-view Atom package, which is based on PDF.js.

**Comment by yitzchak** [comment]
Closing since we have support for pdf-view and enhanced project management method via TeX magic comments.
