### ISSUE TITLE
Issue with bibtex file

### ISSUE THREAD

**Issue by ajclarke90** [thomasjo/atom-latex#60]
This was working fine the other day, but now when I compile, all my citep commands are just returning question marks in the pdf. 

I basically compile in atom using this package, then go an bibtex the bib file by hand in terminal, then recompile in atom. 

I'm fairly sure this isn't me doing something completely wrong, because if I compile it all at the command line, or using TexShop, then my references work fine.

**Comment by thomasjo** [comment]
Any chance you can create a simple example that reproduces the problem, and share it as e.g. a git repository (or some such). Will help me debug the problem.

**Comment by ajclarke90** [comment]
https://github.com/ajclarke90/testbib

This is a really basic version of my stuff, I have included the .cls and .bst files as well. I think this is everything that is needed for compilation, if you need anyhting else let me know,.

**Comment by thomasjo** [comment]
Does this look like the expected result?

![image](https://cloud.githubusercontent.com/assets/3622/6447359/e79e64ca-c111-11e4-810e-ce1c4b9bcee5.png)

**Comment by ajclarke90** [comment]
Yes indeed,. Hmm that makes this more weird. 

I'm away from my work machine. Tomorrow I'll try uninstalling the addon, and re-installing it. See if that fixes it, because it looks like it's working as intended.

**Comment by thomasjo** [comment]
It could be an environment thing. What OS are you using? Might be worth updating all TeX packages.

**Comment by ajclarke90** [comment]
I'm running on OSX Yosemite. I'll double check that tomorrow too. I probably haven't updated the base tex for ages.

**Comment by ajclarke90** [comment]
I don't know what was happening with this. As of this morning this seems to be working perfectly. Perhaps something bugged out when I updated a package or something. Sorry to have raised the issue. Thanks for the package!

**Comment by thomasjo** [comment]
Glad to hear the problem has gone away. And no need to apologize; if you think you've found a bug, or want to suggest improvements, new features and so on, open an issue. I'd rather people open tons of issues, than none at all.

**Comment by thelahunginjeet** [comment]
Hi thomasjo:
This is a great package, thanks for writing it! 

I know this is a closed issue but I'm having a similar problem.  All referencing is fine when I compile in atom; however, if I change the default output directory (say to `aux`, in order to avoid cluttering up the main directory) no references can be found.  Could this be because bibtex can't find one of these output files now they have been moved?  Have you ever experienced this behavior?

**Comment by yitzchak** [comment]
@thelahunginjeet I suggest doing a `latex:clean` after changing the output directory.

Also, bibtex doesn't know about output directories. `latexmk` has a limited facility for informing `bibtex` via the `BIBINPUTS` environment variable. It tries to add any subdirectories it can find to `BIBINPUTS`, but this strategy may fail in more complex situations.
