### ISSUE TITLE
Add "getting started" tests on first launch

### ISSUE THREAD

**Issue by nscaife** [thomasjo/atom-latex#62]
As an enhancement, it might be worthwhile to add a getting started page on the first launch of the package.  I'm thinking of a basic checklist-driven workflow that checks:
- `latexmk` found
- PDF reader found
- basic compilation successful (perhaps include a short tex file in the package?)

**Comment by thomasjo** [comment]
Agreed! I started experimenting with something like this on the [diagnostics branch](https://github.com/thomasjo/atom-latex/tree/diagnostics) a few weeks ago, but never finished it. Got lost in making a decision on pure HTML DOM element manipulation or using a template/view package.

I'll try to get some work done on this tomorrow (March 12, 2015).

**Comment by thomasjo** [comment]
Another support request that most likely could have been avoided with this feature request: https://github.com/thomasjo/atom-latex/issues/71#issuecomment-121419630

**Comment by yitzchak** [comment]
A basic collection of tests, including version checks has been added to the next version. The results are currently displayed in the log panel.
