### ISSUE TITLE
Failed to activate the latex package

### ISSUE THREAD

**Issue by thomasjo** [thomasjo/atom-latex#69]
Happens during package upgrade via the settings view (might be caused by other events as well). I suspect it might be caused by not handling package de-activation properly. Will need to find a way to reproduce the bug.

See https://github.com/atom/settings-view/issues/435 for more details.

**Comment by thomasjo** [comment]
Actually turns out that is caused by a bug in Atom Core caused by modules not being "unloaded" properly. See https://github.com/atom/settings-view/issues/416#issuecomment-78471177 for more details outlined by @izuzak.

In this specific case the crash was caused by v0.20.0 consuming the status-bar as a service, so the old `main` module stuck in the module cache did not have the `consumeStatusBar` function. Closing this since this is not a bug that can be handled on our end.

/cc @samuela @davidfokkema

---
*Note: still going to finish the deactivation changes, since the package really should clean up after deactivation to prevent leaking subscriptions etc.*

**Comment by davidfokkema** [comment]
Thanks!

**Comment by samuela** [comment]
:+1: :clap:

**Comment by ioquatix** [comment]
Had this problem when upgrading..

**Comment by dudektria** [comment]
I got this today after an upgrade.

**Comment by dudektria** [comment]
I tried reinstalling the package just to found an [error coming from within Atom itself](https://github.com/atom/atom/issues/12743).
I hope it may help in some way.

**Comment by thomasjo** [comment]
@dudektria Your error is actually a different problem, which is being tracked in https://github.com/atom/atom/issues/11692.

**Comment by jdily** [comment]
Hi, I got this problem after upgrade to the latest version..
Is there anything I can do to fix it, or like the previous comment that I can not do anything?

**Comment by yitzchak** [comment]
@jdily This is an old closed issue from a year and half ago. Please open a new issue and report any symptoms that you are seeing and I'll see if we can fix the situation.

**Comment by gronki** [comment]
This happens to me with Atom 1.5.4

**Comment by edwinksl** [comment]
I am seeing this same problem in Atom 1.32.0-beta0 (beta channel).

**Comment by Evpok** [comment]
@edwinksl I do too, but that's probably another bug

**Comment by delta-one** [comment]
I also got it with Atom 1.31.2 running on Debian Sid.

**Comment by thomasjo** [comment]
@edwinksl You're most likely affected by https://github.com/thomasjo/atom-latex/issues/488.
