### ISSUE TITLE
Space in path name causes build to fail

### ISSUE THREAD

**Issue by ghost** [thomasjo/atom-latex#7]
I just noticed an issue with spaces in the path or filename causing the build to fail.
In that case, the log/aux files will get dumped in the last folder without a space.
For example, trying to build `~/Desktop/folder with space/document.tex` will fail and create error logs in the Desktop folder.

Files with no spaces in their name and path are working fine.

(This might also be the reason for #5 )

**Comment by arorahrsh** [comment]
@thomasjo I seem to be having this same error again. The LaTeX build is failing for a project whose path contains spaces. Whereas, the same project works fine from a non-space path location.

Is it not possible for a build to work properly if the project path contains spaces?
