### ISSUE TITLE
atom-latex might not deal well with \input{} calls

### ISSUE THREAD

**Issue by TheChymera** [thomasjo/atom-latex#72]
This document compiles nicely both with atom-latex AND pdflatex directly from my command line:

```
\documentclass[a4paper,german,english]{article}
\begin{document}
Lala
\end{document}
```

But, this document:

```
\input{header1.tex}
Lala
\end{document}
```

with `header1.tex` containing:

```
\documentclass[a4paper,german,english]{article}
\begin{document}
```

will fail on atom-latex (but not if compiled via pdflatex directly) with this header1.log:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex 2015.3.14)  5 APR 2015 15:58
entering extended mode
 \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**header1.tex
(/home/chymera/docsrc/thesis-proposal/header1.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 18 languages loaded.
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2007/10/19 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)

LaTeX Warning: Unused global option(s):
    [german,english].

(/home/chymera/docsrc/thesis-proposal/header1.aux)
\openout1 = `header1.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
)
! Emergency stop.
<*> header1.tex
               
*** (job aborted, no legal \end found)

 
Here is how much of TeX's memory you used:
 200 strings out of 494401
 2308 string characters out of 6170841
 49100 words of memory out of 5000000
 3543 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 452 hyphenation exceptions out of 8191
 23i,0n,21p,131b,36s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by thomasjo** [comment]
I'm able to reproduce this. Not sure why yet, but I'm trying to figure it out. Thanks!

**Comment by thomasjo** [comment]
Turns out you've uncovered a weakness in `MasterTexFinder`. One I thought about when I accepted the PR for the feature, but never got around to verify and document with tests; since your "master" file does not contain a `\documentclass[..]{..}` declaration, is it assumed to be a partial file, and we search for a suitable master file by scanning for a `documentclass` declaration. One is found in `header.tex`, and thus we try to build it. Of course this is not what you intended to happen.

I will try to figure out a decent solution to the problem. In the meantime you can workaround the issue (and likely improve your workflow) by taking advantage of the *Magic Comments* support in atom-latex. See https://github.com/thomasjo/atom-latex/issues/70#issuecomment-89025737 for an example and more details.

**Comment by TheChymera** [comment]
That's definitely a great feature! Though from the design point of view perhaps the wrong way to solve the problem of calling the compiler in distributed latex documents. Sure, if one file is used by multiple masters, you can default to the "old" way of just compiling the master - but then why should one master only be granted the luxury of easy compiler access from the documents it includes... Do you always remember to delete the first line after you finish editing?

**Comment by nscaife** [comment]
@thomasjo One possible solution might be to add a "Build This" menu option/keybind with this logic:

* If master magic comment:  build the target file
* else: build the file in the active editor

**Comment by thomasjo** [comment]
I just pushed a new release with a feature flag — `latex.useMasterFileSearch` — that allows you to entirely disable the naive search algorithm. I'm hoping that I can sufficiently improve it in the future (or perhaps go a route along the lines of @nscaife's suggestion) such that the flag will no longer be necessary.

**Comment by tzm41** [comment]
I am wondering how to use the feature flag? Because I am having the same issue as well.
