### ISSUE TITLE
Uncaught TypeError: Cannot read property  build  of null

### ISSUE THREAD

**Issue by makow** [thomasjo/atom-latex#79]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 0.198.0 **System**: linux 3.19.0-16-generic **Thrown From**:  latex  https://github.com/thomasjo/atom-latex  package, v0.23.2 ### Stack Trace Uncaught TypeError: Cannot read property  build  of null     At /home/mal/.atom/packages/latex/lib/main.js:22 TypeError: Cannot read property  build  of null at atom-workspace.latexBuild  /home/mal/.atom/packages/latex/lib/main.js:22:23  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent  /usr/share/atom/resources/app.asar/src/command-registry.js:238:29  at CommandRegistry.handleCommandEvent  /usr/share/atom/resources/app.asar/src/command-registry.js:3:61  at CommandRegistry.module.exports.CommandRegistry.dispatch  /usr/share/atom/resources/app.asar/src/command-registry.js:153:19  at EventEmitter. anonymous>  /usr/share/atom/resources/app.asar/src/window-event-handler.js:71:30  at emitOne  events.js:77:13  at EventEmitter.emit  events.js:166:7      ### Commands     -3:00.9.0 settings-view:check-for-package-updates  atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui  -0:42.4.0 core:paste  atom-text-editor.editor.is-focused  2x -0:30.5.0 editor:newline  atom-text-editor.editor.is-focused  -0:29.8.0 core:paste  atom-text-editor.editor.is-focused  4x -0:29.3.0 editor:newline  atom-text-editor.editor.is-focused  2x -0:22 core:save  atom-text-editor.editor.is-focused  -0:00.4.0 latex:build  atom-text-editor.editor.is-focused      ### Config    json { core : { themes :   one-light-ui , one-light-syntax   }, latex : {} }     ### Installed Packages    coffee # User language-latex, v0.6.1 latex, v0.23.2 linter, v0.12.2 linter-chktex, v0.2.0 # Dev No dev packages

**Comment by thomasjo** [comment]
Are you able to reproduce the problem? I believe I fixed this in v0.23.2, and the underlying problem was only triggered after upgrading the package. You might be seeing a different issue though, but would be great if you could let us know if you're able to reproduce, and give the steps required to reproduce as well. Thanks!

**Comment by makow** [comment]
Now fixed, thanks.

**Comment by thomasjo** [comment]
That's great to hear. Sorry about the problem!
