### ISSUE TITLE
0.23.3 is removing the output PDF

### ISSUE THREAD

**Issue by nscaife** [thomasjo/atom-latex#80]
When building the TeX file, I briefly see the PDF appear in the Atom file list on the left, then it disappears.  The log shows that the file is being created successfully.  I'm getting the following errors in the console:

![capture](https://cloud.githubusercontent.com/assets/644072/7577881/9a87cdac-f81b-11e4-9e71-4535d9ea6f31.PNG)

I stepped through the package with the debugger, and it looks like the PDF is removed after the execution of this line:

`fs.moveSync(originalSyncFilePath, syncFilePath);`

**Comment by thedataking** [comment]
I seem to run into the same issue.

**Comment by thomasjo** [comment]
Thanks for reporting this so quickly. Seems like an unintended side-effect of my attempt to work around the breaking change in fs-plus that lead to v0.23.3 [see https://github.com/thomasjo/atom-latex/issues/78#issuecomment-101043492].

**Comment by thomasjo** [comment]
Since the breaking change in `fs-plus` was introduced in v2.8.0, would one or both of you mind navigating to the `latex` package folder and doing something along the lines of

``` bash
$ rm -r node_modules
$ apm install
```
I'm hoping to get a fix published in `fs-plus` itself, but it seems like for the time being I'll have to pin a specific version of it in this package.

**Comment by thomasjo** [comment]
@nscaife @thedataking Are either of you able to consistently reproduce this? I've been unable to reproduce with any of the versions of `fs-plus` from v2.5.0 up until v2.8.0 (inclusive). Since I cannot reproduce it's a little tricky to fix.

**Comment by nscaife** [comment]
@thomasjo I can reproduce it every time.

![latex](https://cloud.githubusercontent.com/assets/644072/7587113/ce6ceb50-f881-11e4-8694-fa949009f080.gif)

**Comment by nscaife** [comment]
Removing the `node_modules` directory and doing `apm install` didn't fix the issue.  I also totally uninstalled Atom and deleted the `.atom` directory and reinstalled -- same issue.

**Comment by thomasjo** [comment]
@nscaife Thanks for the update. I've managed to reproduce the problem when not using the `outputDirectory` option. I'm working on a fix now.

**Comment by nscaife** [comment]
@thomasjo Thanks, as always! :smile:

**Comment by thomasjo** [comment]
Just published v0.23.4 which hopefully resolves the issue. I added some new tests to guard against future regressions.

**Comment by nscaife** [comment]
Working now, thanks again @thomasjo!

**Comment by thedataking** [comment]
Works for me too (after restarting Atom). Thanks for fixing this so quickly @thomasjo!
