### ISSUE TITLE
0.23.3 cannot build tex files

### ISSUE THREAD

**Issue by Chrisplus** [thomasjo/atom-latex#81]
First I would like to thank the author(s) for making this awesome project. It's very useful.

After upgrading to 0.23.3, I cannot build tex files, either by shortcuts or pressing buttons in packages menu. I'm running a ubuntu 15.04 64bit, atom 0.187.0 and pdflatex as the 'engine'. 

running pdflatex in command line will build tex successfully.

P.S. I'm not sure if it is a bug, hope I am clear and it can help.

**Comment by thomasjo** [comment]
Please upgrade to the latest version of Atom, v0.198.0, and let us know if you can reproduce the problem then. It's likely that I should have bumped the supported version range to account for new features in Atom that the package is relying on.

**Comment by Chrisplus** [comment]
upgrade to atom 0.198.0, problem solved.
thanks.

**Comment by thomasjo** [comment]
Great, glad it worked out! Sorry about the problem, I'll try to be more diligent about bumping the version requirement.
