### ISSUE TITLE
Open log when clicking "LaTeX compilation error"

### ISSUE THREAD

**Issue by nscaife** [thomasjo/atom-latex#82]
Is it possible to have the LaTeX log open in a new tab when clicking "LaTeX compilation error" in the status bar?  Currently it opens the Atom developer pane, which is not intuitive.  

In fact, I've caught myself several times today clicking the status bar, expecting it to open the log. :8ball:

**Comment by nscaife** [comment]
Bonus points if it can jump to the error when opening the log! :100:

**Comment by thomasjo** [comment]
Great idea! Opening shouldn't be hard, so I'll see if I can find time to implement that tomorrow. Jumping to the first error would be trivial if my error parsing stuff was halfway decent. I need to improve that stuff soon...

**Comment by myfavouritekk** [comment]
@thomasjo Is there a way to see the actual latex compilation error message for the moment?

**Comment by myfavouritekk** [comment]
@thomasjo Ok, I found the error in the `.log` files. My bad, sorry. Right, showing the error message when clicking the status bar would be really handy.

**Comment by thomasjo** [comment]
Just published v0.24.0.
