### ISSUE TITLE
Consider missing opener executable as an error?

### ISSUE THREAD

**Issue by thomasjo** [thomasjo/atom-latex#85]
See https://github.com/thomasjo/atom-latex/pull/83#issuecomment-104665130.

I think the suggestion makes sense, to consider a missing opener executable (or ill-configured opener path) as an error. Maybe this could/should also be tied into #64?

**Comment by nscaife** [comment]
I think it makes a lot of sense to be in a welcome/getting started pane.  Perhaps it can also put an error in the status bar -- if you click on this error, it takes you to the package's configuration options?

**Comment by thomasjo** [comment]
Extend this to check if the [pdf-view](https://atom.io/packages/pdf-view) package is installed, if `alwaysOpenResultInAtom` is enabled. Perhaps even automatically installing it (after asking the user) as suggested in #96?
