### ISSUE TITLE
fflush() failed (Broken pipe)

### ISSUE THREAD

**Issue by FlyingPumba** [thomasjo/atom-latex#88]
Hi, I'm having troubles now trying to compile with the LaTeX package. The error output is always the same:
```
{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map
!pdfTeX error: pdflatex (file /var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map): fflush() failed (Broken pipe)
 ==> Fatal error occurred, no output PDF file produced!
```
However, I am able to compile the *same* sources from the Terminal using pdflatex.
Additional info: the error persists when closing and re-opening atom. Also, this problem is happening with one project in particular, other projects work just ok.

**Comment by thomasjo** [comment]
It'd be super helpful if you could provide me with a minimal example that reproduces the problem. Hopefully that'll help me track down your problem, and resolve it.

In addition it'd be helpful to know what OS and version you're running. Thanks!

**Comment by FlyingPumba** [comment]
@thomasjo OS is Ubuntu 14.04, Atom version is 0.204.0 and Latex package version is 0.24.0
I'll send you by email a compressed latex project to reproduce the problem.

**Comment by thomasjo** [comment]
Thanks for providing the files necessary to reproduce the issue—I managed to reproduce the problem. However I have no clue what's going wrong. The package doesn't really do anything beyond invoking `latexmk`. Going to invoke it manually using the same parameters as the package to see if I can reproduce it then.

**Comment by thomasjo** [comment]
Good news, I figured out the problem! Turns out Node.js `ChildProcess` by default is started with a maximum buffer size of 200 KB. I bumped the max buffer size to 50 MB—if anyone ever hits that ceiling, I'll add a configuration option :see_no_evil: 

I just pushed v0.24.1 which contains the fix.

**Comment by FlyingPumba** [comment]
:boom: :boom: You rock ! Thanks for the quick fix

**Comment by nscaife** [comment]
@thomasjo this just happened to me on Windows, strangely.  Immediately rebuilding worked.  I haven't been able to reproduce the error, but if I do I'll let you know.
