### ISSUE TITLE
Shortcut for typing math

### ISSUE THREAD

**Issue by pluskid** [thomasjo/atom-latex#89]
Thanks for writing this plugin! I found the shortcut for typing math in the LaTeXPlus package for Sublime Text very convenient. Hope similar features get implemented in this plugin. Specifically, look at the section *AutoMatch pairs* and *Math Commands* in their [user manual](https://github.com/randy3k/Latex-Plus/wiki/User%20Manual). For example, typing `{{{` gives you `\left\{ | \right\}`, and typing `a gives you \alpha, etc.

**Comment by orzechow** [comment]
Before implementing shortcuts for math, I'd love to see auto-completion within the math environment to boost formula typing.
See the [LaTeX Wikibook](https://en.wikibooks.org/wiki/LaTeX/Mathematics) for all math commands as frac, mathbf, left, right, etc.

For example `\frac{}{}` auto-completion is supported within normal text, but actually only makes sense within any kind of math environment:

    \begin[equation}
    \frac{1}{2}
    \end{equation}

or 

    $\frac{1}{2}$

**Comment by yitzchak** [comment]
At the moment we are keeping `latex` focused on the building/processing of LaTeX documents. For auto-completion functionality I would suggest [latex-autocomplete](https://atom.io/packages/latex-autocomplete) or [latexer](https://atom.io/packages/latexer).
