### ISSUE TITLE
bibtex autocompletion

### ISSUE THREAD

**Issue by maxheld83** [thomasjo/atom-latex#9]
I love this (and the many other features of the ST package [Latexing](http://www.latexing.com/).
I personally find build stuff not so important, because I can always go to another editor for the build, ideally at the end of the day (so as to prevent me from building and futzing with details all the time).
Things that make structured entry easier (such as bibtex autocompletion), however, are immensely valuable.
Really wish I were a coder. Might just go back to school for this.

**Comment by thomasjo** [comment]
I never got around to working on this, but support for BibTeX autocompletion is available via
https://atom.io/packages/autocomplete-bibtex

Since a solution exists, I'm closing this issue.
