### ISSUE TITLE
TeXification failed with status code 9

### ISSUE THREAD

**Issue by NicholasGW** [thomasjo/atom-latex#90]
Hey there! Just trying to get this installed and up and running on a Windows machine with MikTeX, although I know it's not officially supported. Currently I'm getting the error listed in the title, and clicking on the error in the bottom right hand of my screen doesn't open a log file :confused: Any ideas?

**Comment by nscaife** [comment]
`latexmk' requires Perl on Windows and IIRC both Perl and MikTeX need to be manually added to the Windows path before it works.

Can you run `latexmk <file.tex>' at a command prompt and see if it works?

**Comment by NicholasGW** [comment]
Nice! That was totally it...I had to download and install Strawberry Perl. After that, it worked. Now to find a way to keep the PDF in sync...opening with Adobe locks the file and then the atom package throws errors :sad

I'll close this now

**Comment by nscaife** [comment]
@NicholasGW glad I could help!  SumatraPDF supports forward and back synching without file locks.  It's what I use.
