### ISSUE TITLE
Show a nice filtered view of the compilation log while compiling

### ISSUE THREAD

**Issue by LucFabresse** [thomasjo/atom-latex#91]
I am just discovering atom and of course this LaTeX package.
Both are great and I want (will ;-)) to use it.
To me, the major obstacle today is the lack of feedback  during the compilation.
I've read that it has been discussed in other feature request but it deserves its own feature request.
 
A first step could be to just open a pane that contains the current compilation log when compiling.
A second step would be to filter the displayed log to only display important things with colors, .... 
A further step would be to allow the user to customize the filtering in preferences (e.g. not showing overflow, ...).
I also would like to have these kind of preferences:
- always displays compilation log (true/false)
- automatically close compilation log if no error (true/false)
...

Thanks for your work on this plugin.

**Comment by WoodyWoodsta** [comment]
I could definitely have this too. Wading through the horrible latex log file is unpleasant! Let alone Latex's nonsensical error output as well :stuck_out_tongue_closed_eyes:

**Comment by MaxNoe** [comment]
Do you know the `texfot` script that comes with texlive? No need to reinvent the wheel.

**Comment by LucFabresse** [comment]
Thanks Max! I did not know that.
so the latex plugin should definitely use that ;-)

**Comment by yitzchak** [comment]
Resolved by #232.
