### ISSUE TITLE
Documentation of the Preferences

### ISSUE THREAD

**Issue by audiophens** [thomasjo/atom-latex#93]
Hi,

I was wondering if there's a documentation concerning the available package options.
In this particular case, I am not sure what `Open Result in Background` means.

Perhaps it's possible to write a short description below all "Open..." options like you did with the other options (e.g. at `User Master File Search`).

Thanks and take care!

**Comment by thomasjo** [comment]
I agree 100%. At this point it's embarrassing I haven't gotten around to writing up any documentation. Hopefully in the next few weeks as things settle down, I can get around to beginning the documentation effort, beginning with configuration options.

Thanks for the nudge!

**Comment by thomasjo** [comment]
I've written up some more detailed documentation specific to configuration on the wiki:
https://github.com/thomasjo/atom-latex/wiki/Configuration
